/**
 * Muscle via points, carried over from the reference model's frames into ours.
 *
 * **Generated by `pnpm generate:via-points`. Do not edit.**
 *
 * A muscle lies along the bones it passes rather than running straight between its attachments,
 * and published models hold it there with via points. Without them the elbow flexors cut through
 * the humerus and their moment arms come out far too large -- biceps peaked at 65 mm against a
 * published 36 to 40.
 *
 * ## Why these are not simply transcribed
 *
 * The reference model states them in its own body frames, and a coordinate lifted from one frame
 * into another means nothing where it lands. So both models are asked for the same *anatomical*
 * construction instead -- the glenohumeral centre, the bone's long axis, the elbow's flexion axis,
 * which is the humerus frame the ISB defines (Wu 2005, 2.3.4) -- and the rotation between the two
 * answers is the disagreement between two conventions and nothing else. Lengths are scaled by the
 * ratio of the two humeri, so a point a third of the way down one lands a third of the way down
 * the other.
 *
 * The transform was measured, not assumed: the two frames differ by 2.7 degrees about the long
 * axis, and the humeri by a factor of 0.9557 in length.
 *
 * Positions are a fraction of the subject's stature, as every other point in this package is, so
 * they scale with the morphology.
 */

/** One point a muscle passes through, in the order it meets them from origin to insertion. */
export interface MuscleViaPoint {
  readonly id: string;
  /** The muscle-tendon unit this point belongs to. */
  readonly unit: string;
  /** Position in the path, ascending from the origin. */
  readonly order: number;
  /** The bone it is fixed to, and moves with. */
  readonly bone: string;
  /** The reference model's own name for it, so the number can be traced back. */
  readonly referenceSite: string;
  /** Bone-local, as a fraction of stature. */
  readonly local: readonly [number, number, number];
}

export const MUSCLE_VIA_POINTS: readonly MuscleViaPoint[] = [
  {
    id: 'biceps_brachii_long_r__via_1',
    unit: 'biceps_brachii_long_r',
    order: 1,
    bone: 'scapula_r',
    referenceSite: 'BIClong_BIClong-P2_r',
    local: [0.0269241, 0.0010808, -0.0082226],
  },
  {
    id: 'biceps_brachii_long_r__via_2',
    unit: 'biceps_brachii_long_r',
    order: 2,
    bone: 'humerus_r',
    referenceSite: 'BIClong_BIClong-P3_r',
    local: [-0.0124603, 0.0915059, -0.0134787],
  },
  {
    id: 'biceps_brachii_long_r__via_3',
    unit: 'biceps_brachii_long_r',
    order: 3,
    bone: 'humerus_r',
    referenceSite: 'BIClong_BIClong-P4_r',
    local: [-0.00675665, 0.0776997, -0.0147062],
  },
  {
    id: 'biceps_brachii_long_r__via_4',
    unit: 'biceps_brachii_long_r',
    order: 4,
    bone: 'humerus_r',
    referenceSite: 'BIClong_BIClong-P5_r',
    local: [-0.0103219, 0.0638761, -0.00867722],
  },
  {
    id: 'biceps_brachii_long_r__via_5',
    unit: 'biceps_brachii_long_r',
    order: 5,
    bone: 'humerus_r',
    referenceSite: 'BIClong_BIClong-P6_r',
    local: [-0.00583986, 0.0366965, -0.00528843],
  },
  {
    id: 'biceps_brachii_long_r__via_6',
    unit: 'biceps_brachii_long_r',
    order: 6,
    bone: 'humerus_r',
    referenceSite: 'BIClong_BIClong-P7_r',
    local: [0.00130594, 0.0127836, -0.00688392],
  },
  {
    id: 'biceps_brachii_long_r__via_7',
    unit: 'biceps_brachii_long_r',
    order: 7,
    bone: 'humerus_r',
    referenceSite: 'BIClong_BIClong-P8_r',
    local: [0.0051481, -0.0178473, -0.008282],
  },
  {
    id: 'biceps_brachii_long_r__via_8',
    unit: 'biceps_brachii_long_r',
    order: 8,
    bone: 'radius_r',
    referenceSite: 'BIClong_BIClong-P10_r',
    local: [-0.0111672, 0.0647817, 0.026178],
  },
  {
    id: 'biceps_brachii_short_r__via_1',
    unit: 'biceps_brachii_short_r',
    order: 1,
    bone: 'scapula_r',
    referenceSite: 'BICshort_BICshort-P2_r',
    local: [0.0293248, -0.0304806, -0.018927],
  },
  {
    id: 'biceps_brachii_short_r__via_2',
    unit: 'biceps_brachii_short_r',
    order: 2,
    bone: 'humerus_r',
    referenceSite: 'BICshort_BICshort-P3_r',
    local: [-0.0110977, 0.0363148, -0.00624202],
  },
  {
    id: 'biceps_brachii_short_r__via_3',
    unit: 'biceps_brachii_short_r',
    order: 3,
    bone: 'humerus_r',
    referenceSite: 'BICshort_BICshort-P4_r',
    local: [-0.00468962, 0.0113169, -0.00760706],
  },
  {
    id: 'biceps_brachii_short_r__via_4',
    unit: 'biceps_brachii_short_r',
    order: 4,
    bone: 'humerus_r',
    referenceSite: 'BICshort_BICshort-P5_r',
    local: [0.0051481, -0.0178473, -0.008282],
  },
  {
    id: 'biceps_brachii_short_r__via_5',
    unit: 'biceps_brachii_short_r',
    order: 5,
    bone: 'radius_r',
    referenceSite: 'BICshort_BICshort-P6_r',
    local: [-0.0119164, 0.0667286, 0.0265833],
  },
  {
    id: 'brachioradialis_r__via_1',
    unit: 'brachioradialis_r',
    order: 1,
    bone: 'radius_r',
    referenceSite: 'BRD_BRD-P2_r',
    local: [0.0241065, 0.0147459, 0.00891193],
  },
  {
    id: 'triceps_brachii_long_r__via_1',
    unit: 'triceps_brachii_long_r',
    order: 1,
    bone: 'humerus_r',
    referenceSite: 'TRIlong_TRIlong-P1b_r',
    local: [-0.029382, 0.0751727, 0.0167196],
  },
  {
    id: 'triceps_brachii_long_r__via_2',
    unit: 'triceps_brachii_long_r',
    order: 2,
    bone: 'humerus_r',
    referenceSite: 'TRIlong_TRIlong-P2_r',
    local: [-0.00655899, 0.016719, 0.0170298],
  },
  {
    id: 'triceps_brachii_long_r__via_3',
    unit: 'triceps_brachii_long_r',
    order: 3,
    bone: 'humerus_r',
    referenceSite: 'TRIlong_TRIlong-P3_r',
    local: [0.00450775, -0.0451327, 0.0239435],
  },
  {
    id: 'triceps_brachii_long_r__via_4',
    unit: 'triceps_brachii_long_r',
    order: 4,
    bone: 'humerus_r',
    referenceSite: 'TRIlong_TRIlong-P4_r',
    local: [0.0109207, -0.0680162, 0.0176203],
  },
  {
    id: 'triceps_brachii_lateral_r__via_1',
    unit: 'triceps_brachii_lateral_r',
    order: 1,
    bone: 'humerus_r',
    referenceSite: 'TRIlat_TRIlat-P2_r',
    local: [0.00634174, 0.00185916, 0.0172918],
  },
  {
    id: 'triceps_brachii_lateral_r__via_2',
    unit: 'triceps_brachii_lateral_r',
    order: 2,
    bone: 'humerus_r',
    referenceSite: 'TRIlat_TRIlat-P3_r',
    local: [0.00450775, -0.0451327, 0.0239435],
  },
  {
    id: 'triceps_brachii_lateral_r__via_3',
    unit: 'triceps_brachii_lateral_r',
    order: 3,
    bone: 'humerus_r',
    referenceSite: 'TRIlat_TRIlat-P4_r',
    local: [0.0109207, -0.0680162, 0.0176203],
  },
  {
    id: 'triceps_brachii_medial_r__via_1',
    unit: 'triceps_brachii_medial_r',
    order: 1,
    bone: 'humerus_r',
    referenceSite: 'TRImed_TRImed-P2_r',
    local: [-0.00397505, -0.00408803, 0.0176635],
  },
  {
    id: 'triceps_brachii_medial_r__via_2',
    unit: 'triceps_brachii_medial_r',
    order: 2,
    bone: 'humerus_r',
    referenceSite: 'TRImed_TRImed-P3_r',
    local: [0.00450775, -0.0451327, 0.0239435],
  },
  {
    id: 'triceps_brachii_medial_r__via_3',
    unit: 'triceps_brachii_medial_r',
    order: 3,
    bone: 'humerus_r',
    referenceSite: 'TRImed_TRImed-P4_r',
    local: [0.0109207, -0.0680162, 0.0176203],
  },
];

/** The points of one unit, in path order. */
export function viaPointsFor(unit: string): readonly MuscleViaPoint[] {
  return MUSCLE_VIA_POINTS.filter((p) => p.unit === unit).sort((a, b) => a.order - b.order);
}
