/**
 * Whether a generated report on disk is the one its script would write now.
 *
 * Each validation report carries the day it was generated, and that line is the only one that is
 * allowed to differ between a report and a rerun of the script that wrote it: a report written
 * yesterday and unchanged since is current today. Everything else in it -- the counts that follow
 * the date on the same line included -- is what the report says, and a difference anywhere in it
 * means the report is stale.
 *
 * The comparison this replaces split each text at the first `Generated ` and compared what came
 * before. Every report says "Generated by `pnpm ...`" in its opening paragraph, so that compared the
 * title and one paragraph of prose and nothing after it: a report whose every number had moved
 * still read as current, and three gates passed on reports that no longer said what the model does.
 */

const DATE_LINE = /^Generated \d{4}-\d{2}-\d{2}\./m;

/** A report with its date line made neutral, and trailing whitespace dropped. */
const normalise = (text) => text.replace(DATE_LINE, 'Generated <date>.').trimEnd();

/**
 * True when `existing` says the same as `fresh` apart from the day it was generated.
 *
 * `existing` may be undefined, for a report that has not been written yet, and that is never
 * current.
 */
export function reportIsCurrent(existing, fresh) {
  if (typeof existing !== 'string') return false;
  return normalise(existing) === normalise(fresh);
}
