/**
 * The ankle and foot muscle parameter set -- ticket N2.4, the last of the lower limb.
 *
 * **Generated by `pnpm generate:ankle-muscles`. Do not edit.** The numbers are extracted from
 * the vendored MyoSuite leg model rather than copied out of it, so the value here and the value in
 * the cited file cannot disagree; CI runs the generator with `--check`.
 *
 * ## Where each half comes from
 *
 * The same split as every other set. *Where a muscle attaches* is ours: Gray's anatomical
 * statement located on this subject by the dataset's own markers. *What a muscle can do* is
 * MyoSuite's. The two lengths are neither -- both are measured against a skeleton -- so both are
 * derived at compile against this one.
 *
 * ## Three of them run straight, because the carried points are worse than none
 *
 * The via points come from a frame correspondence fitted at the femur, and by the ankle they are
 * out by about twenty millimetres -- nothing to a tendon fifty behind the joint, everything to one
 * forty in front of it. Carried, tibialis anterior has a 4 mm dorsiflexion arm where it should
 * have forty. Without them it has 51, against a published forty; the two long extensors come out
 * two to three times what they should, because nothing holds them down against the front of the
 * ankle. The sign is right and the muscle works, which the other answer cannot say. OQ-021.
 *
 * ## What holds these tendons is via points, not surfaces
 *
 * A muscle at the ankle is held off the joint by a retinaculum rather than by bone, and the
 * grooves those bands strap the tendons into are what give these muscles their leverage:
 * fibularis longus turns under the cuboid to reach the sole, flexor hallucis longus runs under
 * the sustentaculum tali, tibialis posterior passes behind the medial malleolus. All nine are
 * pure via-point paths in the source and are carried that way here, which is the right tool --
 * a retinaculum holds a tendon at a place rather than turning it over a radius.
 *
 * ## The four long toe muscles stop at the metatarsals
 *
 * The dataset marks no phalangeal feature on any of the fourteen toe bones, so extensor and
 * flexor digitorum longus and their hallucis counterparts are carried to the head of the
 * metatarsal each runs over. They keep their line through the ankle and have no action at the
 * toes. That is stated rather than hidden, and recorded in OQ-021.
 */

import { cite } from '@bs-humany/hsdl';
import type { MuscleGroup } from './schema.js';

/** Anatomy: which bony feature a muscle attaches to. The sites themselves are cited in M5.3. */
const gray = (muscle: string) => cite('gray1918', `Part IV, Myology: The ${muscle}`);

/** Parameters: the actuator in the vendored leg model they were derived from. */
const myoLegs = (actuator: string) =>
  cite(
    'caggiano2022',
    `myolegs_muscle.xml, actuator general name="${actuator}": gainprm force, and optimal fiber ` +
      'length and tendon slack length derived from gainprm range with lengthrange',
  );

export const ANKLE_MUSCLES: readonly MuscleGroup[] = [
  {
    id: 'triceps_surae_r',
    displayName: 'Triceps surae, soleus, right',
    taTerm: 'Musculus soleus',
    innervation: 'Tibial nerve',
    source: gray('Triceps surae'),
    units: [
      {
        id: 'soleus_r',
        displayName: 'Soleus, right',
        origin: 'soleus_origin_r_soleal_line',
        insertion: 'soleus_insertion_r_calcaneal_tuberosity',
        path: [],
        parameters: {
          maxIsometricForce: 5322.19,
          optimalFiberLength: 0.0440005,
          tendonSlackLength: 0.276756,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoLegs('soleus_r'),
        },
      },
    ],
  },
  {
    id: 'tibialis_anterior_r',
    displayName: 'Tibialis anterior, right',
    taTerm: 'Musculus tibialis anterior',
    innervation: 'Deep fibular nerve',
    source: gray('Tibialis anterior'),
    units: [
      {
        id: 'tibialis_anterior_r',
        displayName: 'Tibialis anterior, right',
        origin: 'tibialis_anterior_origin_r_lateral_surface_of_tibia',
        insertion: 'tibialis_anterior_insertion_r_first_metatarsal_bone',
        path: [],
        parameters: {
          maxIsometricForce: 1152.86,
          optimalFiberLength: 0.0682995,
          tendonSlackLength: 0.240461,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoLegs('tibant_r'),
        },
      },
    ],
  },
  {
    id: 'tibialis_posterior_r',
    displayName: 'Tibialis posterior, right',
    taTerm: 'Musculus tibialis posterior',
    innervation: 'Tibial nerve',
    source: gray('Tibialis posterior'),
    units: [
      {
        id: 'tibialis_posterior_r',
        displayName: 'Tibialis posterior, right',
        origin: 'tibialis_posterior_origin_r_posterior_surface_of_tibia',
        insertion: 'tibialis_posterior_insertion_r_tuberosity_of_navicular_bone',
        path: [
          { kind: 'site', site: 'tibialis_posterior_r__via_1' },
          { kind: 'site', site: 'tibialis_posterior_r__via_2' },
        ],
        parameters: {
          maxIsometricForce: 1434.86,
          optimalFiberLength: 0.0377993,
          tendonSlackLength: 0.280781,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoLegs('tibpost_r'),
        },
      },
    ],
  },
  {
    id: 'fibularis_longus_r',
    displayName: 'Fibularis longus, right',
    taTerm: 'Musculus fibularis longus',
    innervation: 'Superficial fibular nerve',
    source: gray('Fibularis longus'),
    units: [
      {
        id: 'fibularis_longus_r',
        displayName: 'Fibularis longus, right',
        origin: 'fibularis_longus_origin_r_footprint',
        insertion: 'fibularis_longus_insertion_r_first_metatarsal_bone',
        path: [
          { kind: 'site', site: 'fibularis_longus_r__via_1' },
          { kind: 'site', site: 'fibularis_longus_r__via_2' },
          { kind: 'site', site: 'fibularis_longus_r__via_3' },
          { kind: 'site', site: 'fibularis_longus_r__via_4' },
          { kind: 'site', site: 'fibularis_longus_r__via_5' },
        ],
        parameters: {
          maxIsometricForce: 993.42,
          optimalFiberLength: 0.050799,
          tendonSlackLength: 0.332222,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoLegs('perlong_r'),
        },
      },
    ],
  },
  {
    id: 'fibularis_brevis_r',
    displayName: 'Fibularis brevis, right',
    taTerm: 'Musculus fibularis brevis',
    innervation: 'Superficial fibular nerve',
    source: gray('Fibularis brevis'),
    units: [
      {
        id: 'fibularis_brevis_r',
        displayName: 'Fibularis brevis, right',
        origin: 'fibularis_brevis_origin_r_lateral_surface_of_fibula',
        insertion: 'fibularis_brevis_insertion_r_fifth_metatarsal_bone',
        path: [
          { kind: 'site', site: 'fibularis_brevis_r__via_1' },
          { kind: 'site', site: 'fibularis_brevis_r__via_2' },
          { kind: 'site', site: 'fibularis_brevis_r__via_3' },
        ],
        parameters: {
          maxIsometricForce: 496.045,
          optimalFiberLength: 0.0453995,
          tendonSlackLength: 0.147528,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoLegs('perbrev_r'),
        },
      },
    ],
  },
  {
    id: 'extensor_digitorum_longus_r',
    displayName: 'Extensor digitorum longus, right',
    taTerm: 'Musculus extensor digitorum longus',
    innervation: 'Deep fibular nerve',
    source: gray('Extensor digitorum longus'),
    units: [
      {
        id: 'extensor_digitorum_longus_r',
        displayName: 'Extensor digitorum longus, right',
        origin: 'extensor_digitorum_longus_origin_r_footprint',
        insertion: 'extensor_digitorum_longus_insertion_r_head_of_metatarsal_bone',
        path: [],
        parameters: {
          maxIsometricForce: 553.241,
          optimalFiberLength: 0.0693006,
          tendonSlackLength: 0.368875,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoLegs('edl_r'),
        },
      },
    ],
  },
  {
    id: 'extensor_hallucis_longus_r',
    displayName: 'Extensor hallucis longus, right',
    taTerm: 'Musculus extensor hallucis longus',
    innervation: 'Deep fibular nerve',
    source: gray('Extensor hallucis longus'),
    units: [
      {
        id: 'extensor_hallucis_longus_r',
        displayName: 'Extensor hallucis longus, right',
        origin: 'extensor_hallucis_longus_origin_r_anteromedial_surface_of_fibula',
        insertion: 'extensor_hallucis_longus_insertion_r_head_of_metatarsal_bone',
        path: [],
        parameters: {
          maxIsometricForce: 265.537,
          optimalFiberLength: 0.0748004,
          tendonSlackLength: 0.326795,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoLegs('ehl_r'),
        },
      },
    ],
  },
  {
    id: 'flexor_digitorum_longus_r',
    displayName: 'Flexor digitorum longus, right',
    taTerm: 'Musculus flexor digitorum longus',
    innervation: 'Tibial nerve',
    source: gray('Flexor digitorum longus'),
    units: [
      {
        id: 'flexor_digitorum_longus_r',
        displayName: 'Flexor digitorum longus, right',
        origin: 'flexor_digitorum_longus_origin_r_posterior_surface_of_tibia',
        insertion: 'flexor_digitorum_longus_insertion_r_head_of_metatarsal_bone',
        path: [
          { kind: 'site', site: 'flexor_digitorum_longus_r__via_1' },
          { kind: 'site', site: 'flexor_digitorum_longus_r__via_2' },
          { kind: 'site', site: 'flexor_digitorum_longus_r__via_3' },
          { kind: 'site', site: 'flexor_digitorum_longus_r__via_4' },
        ],
        parameters: {
          maxIsometricForce: 332.13,
          optimalFiberLength: 0.0445996,
          tendonSlackLength: 0.378773,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoLegs('fdl_r'),
        },
      },
    ],
  },
  {
    id: 'flexor_hallucis_longus_r',
    displayName: 'Flexor hallucis longus, right',
    taTerm: 'Musculus flexor hallucis longus',
    innervation: 'Tibial nerve',
    source: gray('Flexor hallucis longus'),
    units: [
      {
        id: 'flexor_hallucis_longus_r',
        displayName: 'Flexor hallucis longus, right',
        origin: 'flexor_hallucis_longus_origin_r_posterior_surface_of_fibula',
        insertion: 'flexor_hallucis_longus_insertion_r_head_of_metatarsal_bone',
        path: [
          { kind: 'site', site: 'flexor_hallucis_longus_r__via_1' },
          { kind: 'site', site: 'flexor_hallucis_longus_r__via_2' },
          { kind: 'site', site: 'flexor_hallucis_longus_r__via_3' },
          { kind: 'site', site: 'flexor_hallucis_longus_r__via_4' },
        ],
        parameters: {
          maxIsometricForce: 749.779,
          optimalFiberLength: 0.0526996,
          tendonSlackLength: 0.35434,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoLegs('fhl_r'),
        },
      },
    ],
  },
  {
    id: 'triceps_surae_l',
    displayName: 'Triceps surae, soleus, left',
    taTerm: 'Musculus soleus',
    innervation: 'Tibial nerve',
    source: gray('Triceps surae'),
    units: [
      {
        id: 'soleus_l',
        displayName: 'Soleus, left',
        origin: 'soleus_origin_l_soleal_line',
        insertion: 'soleus_insertion_l_calcaneal_tuberosity',
        path: [],
        parameters: {
          maxIsometricForce: 5322.19,
          optimalFiberLength: 0.0440005,
          tendonSlackLength: 0.276756,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoLegs('soleus_r'),
        },
      },
    ],
  },
  {
    id: 'tibialis_anterior_l',
    displayName: 'Tibialis anterior, left',
    taTerm: 'Musculus tibialis anterior',
    innervation: 'Deep fibular nerve',
    source: gray('Tibialis anterior'),
    units: [
      {
        id: 'tibialis_anterior_l',
        displayName: 'Tibialis anterior, left',
        origin: 'tibialis_anterior_origin_l_lateral_surface_of_tibia',
        insertion: 'tibialis_anterior_insertion_l_first_metatarsal_bone',
        path: [],
        parameters: {
          maxIsometricForce: 1152.86,
          optimalFiberLength: 0.0682995,
          tendonSlackLength: 0.240461,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoLegs('tibant_r'),
        },
      },
    ],
  },
  {
    id: 'tibialis_posterior_l',
    displayName: 'Tibialis posterior, left',
    taTerm: 'Musculus tibialis posterior',
    innervation: 'Tibial nerve',
    source: gray('Tibialis posterior'),
    units: [
      {
        id: 'tibialis_posterior_l',
        displayName: 'Tibialis posterior, left',
        origin: 'tibialis_posterior_origin_l_posterior_surface_of_tibia',
        insertion: 'tibialis_posterior_insertion_l_tuberosity_of_navicular_bone',
        path: [
          { kind: 'site', site: 'tibialis_posterior_l__via_1' },
          { kind: 'site', site: 'tibialis_posterior_l__via_2' },
        ],
        parameters: {
          maxIsometricForce: 1434.86,
          optimalFiberLength: 0.0377993,
          tendonSlackLength: 0.280781,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoLegs('tibpost_r'),
        },
      },
    ],
  },
  {
    id: 'fibularis_longus_l',
    displayName: 'Fibularis longus, left',
    taTerm: 'Musculus fibularis longus',
    innervation: 'Superficial fibular nerve',
    source: gray('Fibularis longus'),
    units: [
      {
        id: 'fibularis_longus_l',
        displayName: 'Fibularis longus, left',
        origin: 'fibularis_longus_origin_l_footprint',
        insertion: 'fibularis_longus_insertion_l_first_metatarsal_bone',
        path: [
          { kind: 'site', site: 'fibularis_longus_l__via_1' },
          { kind: 'site', site: 'fibularis_longus_l__via_2' },
          { kind: 'site', site: 'fibularis_longus_l__via_3' },
          { kind: 'site', site: 'fibularis_longus_l__via_4' },
          { kind: 'site', site: 'fibularis_longus_l__via_5' },
        ],
        parameters: {
          maxIsometricForce: 993.42,
          optimalFiberLength: 0.050799,
          tendonSlackLength: 0.332222,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoLegs('perlong_r'),
        },
      },
    ],
  },
  {
    id: 'fibularis_brevis_l',
    displayName: 'Fibularis brevis, left',
    taTerm: 'Musculus fibularis brevis',
    innervation: 'Superficial fibular nerve',
    source: gray('Fibularis brevis'),
    units: [
      {
        id: 'fibularis_brevis_l',
        displayName: 'Fibularis brevis, left',
        origin: 'fibularis_brevis_origin_l_lateral_surface_of_fibula',
        insertion: 'fibularis_brevis_insertion_l_fifth_metatarsal_bone',
        path: [
          { kind: 'site', site: 'fibularis_brevis_l__via_1' },
          { kind: 'site', site: 'fibularis_brevis_l__via_2' },
          { kind: 'site', site: 'fibularis_brevis_l__via_3' },
        ],
        parameters: {
          maxIsometricForce: 496.045,
          optimalFiberLength: 0.0453995,
          tendonSlackLength: 0.147528,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoLegs('perbrev_r'),
        },
      },
    ],
  },
  {
    id: 'extensor_digitorum_longus_l',
    displayName: 'Extensor digitorum longus, left',
    taTerm: 'Musculus extensor digitorum longus',
    innervation: 'Deep fibular nerve',
    source: gray('Extensor digitorum longus'),
    units: [
      {
        id: 'extensor_digitorum_longus_l',
        displayName: 'Extensor digitorum longus, left',
        origin: 'extensor_digitorum_longus_origin_l_footprint',
        insertion: 'extensor_digitorum_longus_insertion_l_head_of_metatarsal_bone',
        path: [],
        parameters: {
          maxIsometricForce: 553.241,
          optimalFiberLength: 0.0693006,
          tendonSlackLength: 0.368875,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoLegs('edl_r'),
        },
      },
    ],
  },
  {
    id: 'extensor_hallucis_longus_l',
    displayName: 'Extensor hallucis longus, left',
    taTerm: 'Musculus extensor hallucis longus',
    innervation: 'Deep fibular nerve',
    source: gray('Extensor hallucis longus'),
    units: [
      {
        id: 'extensor_hallucis_longus_l',
        displayName: 'Extensor hallucis longus, left',
        origin: 'extensor_hallucis_longus_origin_l_anteromedial_surface_of_fibula',
        insertion: 'extensor_hallucis_longus_insertion_l_head_of_metatarsal_bone',
        path: [],
        parameters: {
          maxIsometricForce: 265.537,
          optimalFiberLength: 0.0748004,
          tendonSlackLength: 0.326795,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoLegs('ehl_r'),
        },
      },
    ],
  },
  {
    id: 'flexor_digitorum_longus_l',
    displayName: 'Flexor digitorum longus, left',
    taTerm: 'Musculus flexor digitorum longus',
    innervation: 'Tibial nerve',
    source: gray('Flexor digitorum longus'),
    units: [
      {
        id: 'flexor_digitorum_longus_l',
        displayName: 'Flexor digitorum longus, left',
        origin: 'flexor_digitorum_longus_origin_l_posterior_surface_of_tibia',
        insertion: 'flexor_digitorum_longus_insertion_l_head_of_metatarsal_bone',
        path: [
          { kind: 'site', site: 'flexor_digitorum_longus_l__via_1' },
          { kind: 'site', site: 'flexor_digitorum_longus_l__via_2' },
          { kind: 'site', site: 'flexor_digitorum_longus_l__via_3' },
          { kind: 'site', site: 'flexor_digitorum_longus_l__via_4' },
        ],
        parameters: {
          maxIsometricForce: 332.13,
          optimalFiberLength: 0.0445996,
          tendonSlackLength: 0.378773,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoLegs('fdl_r'),
        },
      },
    ],
  },
  {
    id: 'flexor_hallucis_longus_l',
    displayName: 'Flexor hallucis longus, left',
    taTerm: 'Musculus flexor hallucis longus',
    innervation: 'Tibial nerve',
    source: gray('Flexor hallucis longus'),
    units: [
      {
        id: 'flexor_hallucis_longus_l',
        displayName: 'Flexor hallucis longus, left',
        origin: 'flexor_hallucis_longus_origin_l_posterior_surface_of_fibula',
        insertion: 'flexor_hallucis_longus_insertion_l_head_of_metatarsal_bone',
        path: [
          { kind: 'site', site: 'flexor_hallucis_longus_l__via_1' },
          { kind: 'site', site: 'flexor_hallucis_longus_l__via_2' },
          { kind: 'site', site: 'flexor_hallucis_longus_l__via_3' },
          { kind: 'site', site: 'flexor_hallucis_longus_l__via_4' },
        ],
        parameters: {
          maxIsometricForce: 749.779,
          optimalFiberLength: 0.0526996,
          tendonSlackLength: 0.35434,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoLegs('fhl_r'),
        },
      },
    ],
  },
];

/** Every unit in the set, flattened, in a stable order. */
export const ANKLE_UNITS = ANKLE_MUSCLES.flatMap((group) => group.units);
