/**
 * The elbow muscle parameter set -- ticket N2.5, and the data the N3.7 demo runs on.
 *
 * **Generated by `pnpm generate:elbow-muscles`. Do not edit.** The numbers are extracted from
 * the vendored MyoSuite arm model rather than copied out of it, so the value here and the value
 * in the cited file cannot disagree; CI runs the generator with `--check`.
 *
 * ## Where each half comes from, and why they come from different places
 *
 * The two halves of a muscle definition have different provenance, and mixing them up would be
 * the easiest mistake to make here.
 *
 * *Where the muscle attaches* is ours. The origin and insertion name attachment sites built in
 * M5.3: Gray's anatomical statement about where a muscle attaches, located on this subject by the
 * dataset's own markers, in this project's bone frames. The source model has its own sites, and
 * they are deliberately not used -- its body frames are its own, and a coordinate lifted from one
 * frame into another is a number that means nothing in the frame it lands in.
 *
 * *What the muscle can do* is MyoSuite's. Peak force, optimal fiber length and tendon slack
 * length are scalars: they do not live in a frame, so they cross without reinterpretation. They
 * are cited to `caggiano2022` naming the file and the actuator, which is the pattern the
 * external validation harness already checks for every range in the skeleton.
 *
 * ## What is not here yet
 *
 * The paths are empty. Every one of these muscles wraps in the source model -- brachialis over a
 * cylinder, both biceps heads over two ellipsoids each -- and the wrap geometry is in MyoSuite's
 * frames, so it needs the same reconciliation the via points do, and a solver that can wrap
 * (N1.4). Until then these are straight lines from origin to insertion, which is wrong about the
 * moment arm near full flexion in the direction of underestimating it. Recorded as OQ-015.
 *
 * Pennation is zero for every unit. That is not a gap: the MuJoCo muscle model has no pennation
 * angle at all, so the conversion folded it into the peak force and the force declared here is
 * already the force along the tendon. What it costs is recorded as OQ-014.
 */

import { cite } from '@bs-humany/hsdl';
import type { MuscleGroup } from './schema.js';

/** Anatomy: which bony feature a muscle attaches to. The sites themselves are cited in M5.3. */
const gray = (muscle: string) => cite('gray1918', `Part IV, Myology: The ${muscle}`);

/** Parameters: the actuator in the vendored arm model they were derived from. */
const myoArm = (actuator: string) =>
  cite(
    'caggiano2022',
    `myoarm_r_muscle.xml, actuator general name="${actuator}": gainprm force, and optimal fiber ` +
      'length and tendon slack length derived from gainprm range with lengthrange',
  );

/**
 * The seven units that cross the elbow, as five anatomical muscles.
 *
 * Both biceps heads and all three triceps heads are separate lines of action, per M-ADR-005: one
 * line through a triceps is not a simplification of a triceps, it is a different muscle with a
 * moment arm the real one does not have.
 */
export const ELBOW_MUSCLES: readonly MuscleGroup[] = [
  {
    id: 'biceps_brachii_r',
    displayName: 'Biceps brachii, right',
    taTerm: 'Musculus biceps brachii',
    innervation: 'Musculocutaneous nerve',
    source: gray('Biceps brachii'),
    units: [
      {
        id: 'biceps_brachii_long_r',
        displayName: 'Biceps brachii, long head, right',
        origin: 'biceps_brachii_origin_r_supraglenoid_tubercle',
        insertion: 'biceps_brachii_insertion_r_radial_tuberosity',
        path: [],
        parameters: {
          maxIsometricForce: 421.718,
          optimalFiberLength: 0.127198,
          tendonSlackLength: 0.276705,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoArm('BIClong'),
        },
      },
      {
        id: 'biceps_brachii_short_r',
        displayName: 'Biceps brachii, short head, right',
        origin: 'biceps_brachii_origin_r_coracoid_process',
        insertion: 'biceps_brachii_insertion_r_radial_tuberosity',
        path: [],
        parameters: {
          maxIsometricForce: 270.82,
          optimalFiberLength: 0.177462,
          tendonSlackLength: 0.181864,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoArm('BICshort'),
        },
      },
    ],
  },
  {
    id: 'brachialis_r',
    displayName: 'Brachialis, right',
    taTerm: 'Musculus brachialis',
    innervation: 'Musculocutaneous nerve',
    source: gray('Brachialis'),
    units: [
      {
        id: 'brachialis_r',
        displayName: 'Brachialis, right',
        origin: 'brachialis_origin_r_anteromedial_surface_of_humerus',
        insertion: 'brachialis_insertion_r_tuberosity_of_ulna',
        path: [],
        parameters: {
          maxIsometricForce: 1168.76,
          optimalFiberLength: 0.0576238,
          tendonSlackLength: 0.0756543,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoArm('BRA'),
        },
      },
    ],
  },
  {
    id: 'brachioradialis_r',
    displayName: 'Brachioradialis, right',
    taTerm: 'Musculus brachioradialis',
    innervation: 'Radial nerve',
    source: gray('Brachioradialis'),
    units: [
      {
        id: 'brachioradialis_r',
        displayName: 'Brachioradialis, right',
        origin: 'brachioradialis_origin_r_lateral_supracondylar_ridge',
        insertion: 'brachioradialis_insertion_r_radial_styloid_process',
        path: [],
        parameters: {
          maxIsometricForce: 272.486,
          optimalFiberLength: 0.101976,
          tendonSlackLength: 0.187076,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoArm('BRD'),
        },
      },
    ],
  },
  {
    id: 'triceps_brachii_r',
    displayName: 'Triceps brachii, right',
    taTerm: 'Musculus triceps brachii',
    innervation: 'Radial nerve',
    source: gray('Triceps brachii'),
    units: [
      {
        id: 'triceps_brachii_long_r',
        displayName: 'Triceps brachii, long head, right',
        origin: 'triceps_brachii_origin_r_infraglenoid_tubercle',
        insertion: 'triceps_brachii_insertion_r_olecranon',
        path: [],
        parameters: {
          maxIsometricForce: 670.069,
          optimalFiberLength: 0.179115,
          tendonSlackLength: 0.120652,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoArm('TRIlong'),
        },
      },
      {
        id: 'triceps_brachii_lateral_r',
        displayName: 'Triceps brachii, lateral head, right',
        origin: 'triceps_brachii_origin_r_posterior_surface_of_humerus',
        insertion: 'triceps_brachii_insertion_r_olecranon',
        path: [],
        parameters: {
          maxIsometricForce: 682.224,
          optimalFiberLength: 0.0636004,
          tendonSlackLength: 0.132373,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoArm('TRIlat'),
        },
      },
      {
        id: 'triceps_brachii_medial_r',
        displayName: 'Triceps brachii, medial head, right',
        origin: 'triceps_brachii_origin_r_posterior_surface_of_humerus',
        insertion: 'triceps_brachii_insertion_r_olecranon',
        path: [],
        parameters: {
          maxIsometricForce: 660.895,
          optimalFiberLength: 0.0513648,
          tendonSlackLength: 0.131368,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoArm('TRImed'),
        },
      },
    ],
  },
];

/** Every unit in the set, flattened, in a stable order. */
export const ELBOW_UNITS = ELBOW_MUSCLES.flatMap((group) => group.units);
