/**
 * The elbow muscle parameter set -- ticket N2.5, and the data the N3.7 demo runs on.
 *
 * **Generated by `pnpm generate:elbow-muscles`. Do not edit.** The numbers are extracted from
 * the vendored MyoSuite arm model rather than copied out of it, so the value here and the value
 * in the cited file cannot disagree; CI runs the generator with `--check`.
 *
 * ## Where each half comes from, and why they come from different places
 *
 * The two halves of a muscle definition have different provenance, and mixing them up would be
 * the easiest mistake to make here.
 *
 * *Where the muscle attaches* is ours. The origin and insertion name attachment sites built in
 * M5.3: Gray's anatomical statement about where a muscle attaches, located on this subject by the
 * dataset's own markers, in this project's bone frames. The source model has its own sites, and
 * they are deliberately not used -- its body frames are its own, and a coordinate lifted from one
 * frame into another is a number that means nothing in the frame it lands in.
 *
 * *What the muscle can do* is MyoSuite's. Peak force, optimal fiber length and tendon slack
 * length are scalars: they do not live in a frame, so they cross without reinterpretation. They
 * are cited to `caggiano2022` naming the file and the actuator, which is the pattern the
 * external validation harness already checks for every range in the skeleton.
 *
 * ## What is not here yet
 *
 * The via points on the scapula and the forearm are. Each unit is held along the humerus by the
 * points `muscleViaPoints.ts` carries over, and turns over the trochlea at the elbow; the source
 * model routes some units through a few further points on the bones either side of that, which
 * would need the same frame construction repeated for those bones.
 *
 * Pennation is zero for every unit. That is not a gap: the MuJoCo muscle model has no pennation
 * angle at all, so the conversion folded it into the peak force and the force declared here is
 * already the force along the tendon. What it costs is recorded as OQ-014.
 *
 * ## Which side of the bone each muscle lies on
 *
 * Every unit turns over the humeral trochlea, and each declares which side it lies on: the three
 * heads of triceps behind the joint axis, the four flexors in front of it. That is an anatomical
 * fact rather than something to work out per tick, and declaring it is what stops a path falling
 * to the other side of the bone as the joint moves -- which would reverse the muscle's moment arm
 * for a tick and turn a flexor into an extensor (muscle spec 4.3).
 *
 * The sides are in the bone's own frame, where +Z is posterior for this dataset: the olecranon
 * fossa sits at z = 0.055 and the coronoid fossa, in front of it, at z = 0.020.
 *
 * They lie against different surfaces, too. The extensors turn over the trochlea, coaxial with
 * the elbow, which is what holds their moment arm at its radius through the range. The flexors
 * never reach it -- measured, their paths pass in front of it and clear it at every angle -- so
 * what they need is the humeral shaft, which they lie along rather than pass through. One surface
 * each: the solver takes one per span until N1.5 adds the multi-surface solve, and a muscle that
 * wants both wants a via point between them, which is the other half of OQ-015.
 */

import { cite } from '@bs-humany/hsdl';
import type { MuscleGroup } from './schema.js';

/** Anatomy: which bony feature a muscle attaches to. The sites themselves are cited in M5.3. */
const gray = (muscle: string) => cite('gray1918', `Part IV, Myology: The ${muscle}`);

/** Parameters: the actuator in the vendored arm model they were derived from. */
const myoArm = (actuator: string) =>
  cite(
    'caggiano2022',
    `myoarm_r_muscle.xml, actuator general name="${actuator}": gainprm force, and optimal fiber ` +
      'length and tendon slack length derived from gainprm range with lengthrange',
  );

/**
 * The seven units that cross the elbow, as five anatomical muscles.
 *
 * Both biceps heads and all three triceps heads are separate lines of action, per M-ADR-005: one
 * line through a triceps is not a simplification of a triceps, it is a different muscle with a
 * moment arm the real one does not have.
 */
export const ELBOW_MUSCLES: readonly MuscleGroup[] = [
  {
    id: 'biceps_brachii_r',
    displayName: 'Biceps brachii, right',
    taTerm: 'Musculus biceps brachii',
    innervation: 'Musculocutaneous nerve',
    source: gray('Biceps brachii'),
    units: [
      {
        id: 'biceps_brachii_long_r',
        displayName: 'Biceps brachii, long head, right',
        origin: 'biceps_brachii_origin_r_supraglenoid_tubercle',
        insertion: 'biceps_brachii_insertion_r_radial_tuberosity',
        path: [
          { kind: 'site', site: 'biceps_brachii_long_r__via_1' },
          { kind: 'site', site: 'biceps_brachii_long_r__via_2' },
          { kind: 'site', site: 'biceps_brachii_long_r__via_3' },
          { kind: 'site', site: 'biceps_brachii_long_r__via_4' },
          { kind: 'site', site: 'biceps_brachii_long_r__via_5' },
          { kind: 'site', site: 'biceps_brachii_long_r__via_6' },
          { kind: 'site', site: 'biceps_brachii_long_r__via_7' },
          { kind: 'site', site: 'biceps_brachii_long_r__via_8' },
          {
            kind: 'wrap',
            surface: 'elbow_trochlea_r',
            preferredSide: { x: 0, y: 0, z: -1 },
            source: gray('Biceps brachii'),
          },
        ],
        parameters: {
          maxIsometricForce: 421.718,
          optimalFiberLength: 0.127198,
          tendonSlackLength: 0.276705,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoArm('BIClong'),
        },
      },
      {
        id: 'biceps_brachii_short_r',
        displayName: 'Biceps brachii, short head, right',
        origin: 'biceps_brachii_origin_r_coracoid_process',
        insertion: 'biceps_brachii_insertion_r_radial_tuberosity',
        path: [
          { kind: 'site', site: 'biceps_brachii_short_r__via_1' },
          { kind: 'site', site: 'biceps_brachii_short_r__via_2' },
          { kind: 'site', site: 'biceps_brachii_short_r__via_3' },
          { kind: 'site', site: 'biceps_brachii_short_r__via_4' },
          { kind: 'site', site: 'biceps_brachii_short_r__via_5' },
          {
            kind: 'wrap',
            surface: 'elbow_trochlea_r',
            preferredSide: { x: 0, y: 0, z: -1 },
            source: gray('Biceps brachii'),
          },
        ],
        parameters: {
          maxIsometricForce: 270.82,
          optimalFiberLength: 0.177462,
          tendonSlackLength: 0.181864,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoArm('BICshort'),
        },
      },
    ],
  },
  {
    id: 'brachialis_r',
    displayName: 'Brachialis, right',
    taTerm: 'Musculus brachialis',
    innervation: 'Musculocutaneous nerve',
    source: gray('Brachialis'),
    units: [
      {
        id: 'brachialis_r',
        displayName: 'Brachialis, right',
        origin: 'brachialis_origin_r_anteromedial_surface_of_humerus',
        insertion: 'brachialis_insertion_r_tuberosity_of_ulna',
        path: [
          {
            kind: 'wrap',
            surface: 'elbow_trochlea_r',
            preferredSide: { x: 0, y: 0, z: -1 },
            source: gray('Brachialis'),
          },
        ],
        parameters: {
          maxIsometricForce: 1168.76,
          optimalFiberLength: 0.0576238,
          tendonSlackLength: 0.0756543,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoArm('BRA'),
        },
      },
    ],
  },
  {
    id: 'brachioradialis_r',
    displayName: 'Brachioradialis, right',
    taTerm: 'Musculus brachioradialis',
    innervation: 'Radial nerve',
    source: gray('Brachioradialis'),
    units: [
      {
        id: 'brachioradialis_r',
        displayName: 'Brachioradialis, right',
        origin: 'brachioradialis_origin_r_lateral_supracondylar_ridge',
        insertion: 'brachioradialis_insertion_r_radial_styloid_process',
        path: [
          { kind: 'site', site: 'brachioradialis_r__via_1' },
          {
            kind: 'wrap',
            surface: 'elbow_trochlea_r',
            preferredSide: { x: 0, y: 0, z: -1 },
            source: gray('Brachioradialis'),
          },
        ],
        parameters: {
          maxIsometricForce: 272.486,
          optimalFiberLength: 0.101976,
          tendonSlackLength: 0.187076,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoArm('BRD'),
        },
      },
    ],
  },
  {
    id: 'triceps_brachii_r',
    displayName: 'Triceps brachii, right',
    taTerm: 'Musculus triceps brachii',
    innervation: 'Radial nerve',
    source: gray('Triceps brachii'),
    units: [
      {
        id: 'triceps_brachii_long_r',
        displayName: 'Triceps brachii, long head, right',
        origin: 'triceps_brachii_origin_r_infraglenoid_tubercle',
        insertion: 'triceps_brachii_insertion_r_olecranon',
        path: [
          { kind: 'site', site: 'triceps_brachii_long_r__via_1' },
          { kind: 'site', site: 'triceps_brachii_long_r__via_2' },
          { kind: 'site', site: 'triceps_brachii_long_r__via_3' },
          { kind: 'site', site: 'triceps_brachii_long_r__via_4' },
          {
            kind: 'wrap',
            surface: 'elbow_trochlea_r',
            preferredSide: { x: 0, y: 0, z: 1 },
            source: gray('Triceps brachii'),
          },
        ],
        parameters: {
          maxIsometricForce: 670.069,
          optimalFiberLength: 0.179115,
          tendonSlackLength: 0.120652,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoArm('TRIlong'),
        },
      },
      {
        id: 'triceps_brachii_lateral_r',
        displayName: 'Triceps brachii, lateral head, right',
        origin: 'triceps_brachii_origin_r_posterior_surface_of_humerus',
        insertion: 'triceps_brachii_insertion_r_olecranon',
        path: [
          { kind: 'site', site: 'triceps_brachii_lateral_r__via_1' },
          { kind: 'site', site: 'triceps_brachii_lateral_r__via_2' },
          { kind: 'site', site: 'triceps_brachii_lateral_r__via_3' },
          {
            kind: 'wrap',
            surface: 'elbow_trochlea_r',
            preferredSide: { x: 0, y: 0, z: 1 },
            source: gray('Triceps brachii'),
          },
        ],
        parameters: {
          maxIsometricForce: 682.224,
          optimalFiberLength: 0.0636004,
          tendonSlackLength: 0.132373,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoArm('TRIlat'),
        },
      },
      {
        id: 'triceps_brachii_medial_r',
        displayName: 'Triceps brachii, medial head, right',
        origin: 'triceps_brachii_origin_r_posterior_surface_of_humerus',
        insertion: 'triceps_brachii_insertion_r_olecranon',
        path: [
          { kind: 'site', site: 'triceps_brachii_medial_r__via_1' },
          { kind: 'site', site: 'triceps_brachii_medial_r__via_2' },
          { kind: 'site', site: 'triceps_brachii_medial_r__via_3' },
          {
            kind: 'wrap',
            surface: 'elbow_trochlea_r',
            preferredSide: { x: 0, y: 0, z: 1 },
            source: gray('Triceps brachii'),
          },
        ],
        parameters: {
          maxIsometricForce: 660.895,
          optimalFiberLength: 0.0513648,
          tendonSlackLength: 0.131368,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoArm('TRImed'),
        },
      },
    ],
  },
];

/** Every unit in the set, flattened, in a stable order. */
export const ELBOW_UNITS = ELBOW_MUSCLES.flatMap((group) => group.units);
