/**
 * The forearm and wrist muscle parameter set -- ticket N2.5.
 *
 * **Generated by `pnpm generate:forearm-muscles`. Do not edit.** CI runs the generator with
 * `--check`.
 *
 * ## What is transcribed here and what is not
 *
 * Peak force is the source's for all eight. So is the fiber length of supinator and anconeus, whose
 * actuators state an operating range the fiber length can be derived from -- and which come out at
 * 36 mm and 26 mm against a published 33 and 27. Those two cite `myoArm`.
 *
 * The other six state no such range, so MuJoCo's default applies and no fiber length can be
 * derived from it: doing so gives 1.1 to 5.6 times published and one tendon of minus 16 mm. What
 * those six do state is a `lengthrange`, and their fiber length is its width over
 * `TYPICAL_NORMALISED_TRAVEL` -- the travel a muscle typically has, measured on the source's
 * units that do state their architecture. It is a stand-in good to about half, and each of those
 * units cites `myoArmStandIn`, which says so. OQ-022 has the argument, the numbers and the
 * licence reason the better source could not be vendored.
 *
 * Both kinds are the number the simulation runs. Compile's `deriveOptimalFiberLength` lengthens a
 * fiber only where the muscle travels further on this skeleton than on the source's (OQ-020), and
 * every one of these eight travels less here, for the reason OQ-022 gives: our wrist's range is
 * short and our forearm attachments sit near their joint axes. The step's other effect, a cap at
 * four fifths of the path, reaches only a short body's anconeus.
 *
 * *Where a muscle attaches* is ours throughout, as everywhere: Gray's anatomical statement located
 * on this subject by the dataset's own markers, and where the dataset marks nothing, measured off
 * the bone.
 *
 * ## Two muscles are missing from this set, and one from the body
 *
 * Beyond the wrist the dataset marks four points: the tubercles of the scaphoid and trapezium, the
 * hook of the hamate, and the base and styloid of the third metacarpal -- and the trapezium's only
 * on the right hand. Extensor carpi radialis brevis ends on the third metacarpal's styloid and
 * flexor carpi ulnaris at the hook of the hamate. Flexor carpi radialis and extensor carpi
 * radialis longus end on the base of the second metacarpal, which the dataset does not mark and
 * `tools/ingest/src/derived.ts` measures off the bone.
 *
 * Extensor carpi ulnaris is in the hand set, not here: it ends on the base of the fifth
 * metacarpal, which had nothing to locate it until derived.ts measured the digit bones. Palmaris
 * longus alone is omitted. It ends in the palmar aponeurosis, soft tissue the dataset does not
 * carry, and the nearest bony point is where flexor carpi radialis already passes. The wrist has
 * two flexors, one radial and one ulnar, and three extensors, two radial here and the ulnar one
 * in the hand set.
 */

import { cite } from '@bs-humany/hsdl';
import type { MuscleGroup } from './schema.js';

/** Anatomy: which bony feature a muscle attaches to. The sites themselves are cited in M5.3. */
const gray = (muscle: string) => cite('gray1918', `Part IV, Myology: The ${muscle}`);

/** Parameters, for an actuator that states its own operating range: both lengths are derived. */
const myoArm = (actuator: string) =>
  cite(
    'caggiano2022',
    `myoarm_r_muscle.xml, actuator name="${actuator}": peak force as stated; fiber length derived ` +
      'from the operating range the actuator states',
  );

/** Parameters, for an actuator that states no operating range: the fiber length is a stand-in. */
const myoArmStandIn = (actuator: string) =>
  cite(
    'caggiano2022',
    `myoarm_r_muscle.xml, actuator name="${actuator}": peak force as stated; fiber length is the ` +
      'stated lengthrange width over TYPICAL_NORMALISED_TRAVEL (0.667), a stand-in good to ' +
      'about half (OQ-022); lengthened at compile only where the muscle travels further here ' +
      'than on the source (OQ-020)',
  );

export const FOREARM_MUSCLES: readonly MuscleGroup[] = [
  {
    id: 'pronator_teres_r',
    displayName: 'Pronator teres, right',
    taTerm: 'Musculus pronator teres',
    innervation: 'Median nerve',
    source: gray('Pronator teres'),
    units: [
      {
        id: 'pronator_teres_r',
        displayName: 'Pronator teres, right',
        origin: 'pronator_teres_origin_r_medial_epicondyle_of_humerus',
        insertion: 'pronator_teres_insertion_r_pronator_tuberosity',
        path: [
          { kind: 'site', site: 'pronator_teres_r__via_1' },
          { kind: 'site', site: 'pronator_teres_r__via_2' },
          { kind: 'site', site: 'pronator_teres_r__via_3' },
        ],
        parameters: {
          maxIsometricForce: 557.2,
          optimalFiberLength: 0.0344243,
          tendonSlackLength: 0.126588,
          pennationAngle: 0,
          source: myoArmStandIn('PT'),
        },
      },
    ],
  },
  {
    id: 'pronator_quadratus_r',
    displayName: 'Pronator quadratus, right',
    taTerm: 'Musculus pronator quadratus',
    innervation: 'Anterior interosseous nerve',
    source: gray('Pronator quadratus'),
    units: [
      {
        id: 'pronator_quadratus_r',
        displayName: 'Pronator quadratus, right',
        origin: 'pronator_quadratus_origin_r_medial_surface_of_ulna',
        insertion: 'pronator_quadratus_insertion_r_anterior_surface_of_radius',
        path: [],
        parameters: {
          maxIsometricForce: 284.7,
          optimalFiberLength: 0.0226202,
          tendonSlackLength: 0.00850706,
          pennationAngle: 0,
          source: myoArmStandIn('PQ'),
        },
      },
    ],
  },
  {
    id: 'supinator_r',
    displayName: 'Supinator, right',
    taTerm: 'Musculus supinator',
    innervation: 'Posterior interosseous nerve',
    source: gray('Supinator'),
    units: [
      {
        id: 'supinator_r',
        displayName: 'Supinator, right',
        origin: 'supinator_origin_r_supinator_crest',
        insertion: 'supinator_insertion_r_lateral_surface_of_radius',
        path: [{ kind: 'site', site: 'supinator_r__via_1' }],
        parameters: {
          maxIsometricForce: 339.132,
          optimalFiberLength: 0.0363066,
          tendonSlackLength: 0.022465,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoArm('SUP'),
        },
      },
    ],
  },
  {
    id: 'anconeus_r',
    displayName: 'Anconeus, right',
    taTerm: 'Musculus anconeus',
    innervation: 'Radial nerve',
    source: gray('Anconeus'),
    units: [
      {
        id: 'anconeus_r',
        displayName: 'Anconeus, right',
        origin: 'anconeus_origin_r_lateral_epicondyle_of_humerus',
        insertion: 'anconeus_insertion_r_olecranon',
        path: [],
        parameters: {
          maxIsometricForce: 262.904,
          optimalFiberLength: 0.0259443,
          tendonSlackLength: 0.0189105,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoArm('ANC'),
        },
      },
    ],
  },
  {
    id: 'flexor_carpi_radialis_r',
    displayName: 'Flexor carpi radialis, right',
    taTerm: 'Musculus flexor carpi radialis',
    innervation: 'Median nerve',
    source: gray('Flexor carpi radialis'),
    units: [
      {
        id: 'flexor_carpi_radialis_r',
        displayName: 'Flexor carpi radialis, right',
        origin: 'flexor_carpi_radialis_origin_r_medial_epicondyle_of_humerus',
        insertion: 'flexor_carpi_radialis_insertion_r_base_of_digit_bone',
        path: [
          { kind: 'site', site: 'flexor_carpi_radialis_path_r_scaphoid_tubercle_of_scaphoid_bone' },
          { kind: 'site', site: 'flexor_carpi_radialis_r__via_1' },
        ],
        parameters: {
          maxIsometricForce: 407.9,
          optimalFiberLength: 0.0534153,
          tendonSlackLength: 0.263817,
          pennationAngle: 0,
          source: myoArmStandIn('FCR'),
        },
      },
    ],
  },
  {
    id: 'flexor_carpi_ulnaris_r',
    displayName: 'Flexor carpi ulnaris, right',
    taTerm: 'Musculus flexor carpi ulnaris',
    innervation: 'Ulnar nerve',
    source: gray('Flexor carpi ulnaris'),
    units: [
      {
        id: 'flexor_carpi_ulnaris_r',
        displayName: 'Flexor carpi ulnaris, right',
        origin: 'flexor_carpi_ulnaris_origin_r_footprint',
        insertion: 'flexor_carpi_ulnaris_insertion_r_hook_of_hamate_bone',
        path: [
          { kind: 'site', site: 'flexor_carpi_ulnaris_r__via_1' },
          { kind: 'site', site: 'flexor_carpi_ulnaris_r__via_2' },
        ],
        parameters: {
          maxIsometricForce: 479.8,
          optimalFiberLength: 0.0589955,
          tendonSlackLength: 0.25796,
          pennationAngle: 0,
          source: myoArmStandIn('FCU'),
        },
      },
    ],
  },
  {
    id: 'extensor_carpi_radialis_r',
    displayName: 'Extensor carpi radialis, right',
    taTerm: 'Musculi extensores carpi radiales',
    innervation: 'Radial nerve, and its posterior interosseous branch for brevis',
    source: gray('Extensor carpi radialis'),
    units: [
      {
        id: 'extensor_carpi_radialis_longus_r',
        displayName: 'Extensor carpi radialis longus, right',
        origin: 'extensor_carpi_radialis_longus_origin_r_lateral_supracondylar_ridge',
        insertion: 'extensor_carpi_radialis_longus_insertion_r_base_of_digit_bone',
        path: [
          {
            kind: 'site',
            site: 'extensor_carpi_radialis_longus_path_r_radius_radial_styloid_process',
          },
          { kind: 'site', site: 'extensor_carpi_radialis_longus_r__via_1' },
          { kind: 'site', site: 'extensor_carpi_radialis_longus_r__via_2' },
        ],
        parameters: {
          maxIsometricForce: 337.3,
          optimalFiberLength: 0.0418006,
          tendonSlackLength: 0.288111,
          pennationAngle: 0,
          source: myoArmStandIn('ECRL'),
        },
      },
      {
        id: 'extensor_carpi_radialis_brevis_r',
        displayName: 'Extensor carpi radialis brevis, right',
        origin: 'extensor_carpi_radialis_brevis_origin_r_lateral_epicondyle_of_humerus',
        insertion:
          'extensor_carpi_radialis_brevis_insertion_r_styloid_process_of_third_metacarpal_bone',
        path: [
          { kind: 'site', site: 'extensor_carpi_radialis_brevis_r__via_1' },
          { kind: 'site', site: 'extensor_carpi_radialis_brevis_r__via_2' },
        ],
        parameters: {
          maxIsometricForce: 252.2,
          optimalFiberLength: 0.0472639,
          tendonSlackLength: 0.241612,
          pennationAngle: 0,
          source: myoArmStandIn('ECRB'),
        },
      },
    ],
  },
  {
    id: 'pronator_teres_l',
    displayName: 'Pronator teres, left',
    taTerm: 'Musculus pronator teres',
    innervation: 'Median nerve',
    source: gray('Pronator teres'),
    units: [
      {
        id: 'pronator_teres_l',
        displayName: 'Pronator teres, left',
        origin: 'pronator_teres_origin_l_medial_epicondyle_of_humerus',
        insertion: 'pronator_teres_insertion_l_pronator_tuberosity',
        path: [
          { kind: 'site', site: 'pronator_teres_l__via_1' },
          { kind: 'site', site: 'pronator_teres_l__via_2' },
          { kind: 'site', site: 'pronator_teres_l__via_3' },
        ],
        parameters: {
          maxIsometricForce: 557.2,
          optimalFiberLength: 0.0344243,
          tendonSlackLength: 0.126588,
          pennationAngle: 0,
          source: myoArmStandIn('PT'),
        },
      },
    ],
  },
  {
    id: 'pronator_quadratus_l',
    displayName: 'Pronator quadratus, left',
    taTerm: 'Musculus pronator quadratus',
    innervation: 'Anterior interosseous nerve',
    source: gray('Pronator quadratus'),
    units: [
      {
        id: 'pronator_quadratus_l',
        displayName: 'Pronator quadratus, left',
        origin: 'pronator_quadratus_origin_l_medial_surface_of_ulna',
        insertion: 'pronator_quadratus_insertion_l_anterior_surface_of_radius',
        path: [],
        parameters: {
          maxIsometricForce: 284.7,
          optimalFiberLength: 0.0226202,
          tendonSlackLength: 0.00850706,
          pennationAngle: 0,
          source: myoArmStandIn('PQ'),
        },
      },
    ],
  },
  {
    id: 'supinator_l',
    displayName: 'Supinator, left',
    taTerm: 'Musculus supinator',
    innervation: 'Posterior interosseous nerve',
    source: gray('Supinator'),
    units: [
      {
        id: 'supinator_l',
        displayName: 'Supinator, left',
        origin: 'supinator_origin_l_supinator_crest',
        insertion: 'supinator_insertion_l_lateral_surface_of_radius',
        path: [{ kind: 'site', site: 'supinator_l__via_1' }],
        parameters: {
          maxIsometricForce: 339.132,
          optimalFiberLength: 0.0363066,
          tendonSlackLength: 0.022465,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoArm('SUP'),
        },
      },
    ],
  },
  {
    id: 'anconeus_l',
    displayName: 'Anconeus, left',
    taTerm: 'Musculus anconeus',
    innervation: 'Radial nerve',
    source: gray('Anconeus'),
    units: [
      {
        id: 'anconeus_l',
        displayName: 'Anconeus, left',
        origin: 'anconeus_origin_l_lateral_epicondyle_of_humerus',
        insertion: 'anconeus_insertion_l_olecranon',
        path: [],
        parameters: {
          maxIsometricForce: 262.904,
          optimalFiberLength: 0.0259443,
          tendonSlackLength: 0.0189105,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoArm('ANC'),
        },
      },
    ],
  },
  {
    id: 'flexor_carpi_radialis_l',
    displayName: 'Flexor carpi radialis, left',
    taTerm: 'Musculus flexor carpi radialis',
    innervation: 'Median nerve',
    source: gray('Flexor carpi radialis'),
    units: [
      {
        id: 'flexor_carpi_radialis_l',
        displayName: 'Flexor carpi radialis, left',
        origin: 'flexor_carpi_radialis_origin_l_medial_epicondyle_of_humerus',
        insertion: 'flexor_carpi_radialis_insertion_l_base_of_digit_bone',
        path: [
          { kind: 'site', site: 'flexor_carpi_radialis_path_l_scaphoid_tubercle_of_scaphoid_bone' },
          { kind: 'site', site: 'flexor_carpi_radialis_l__via_1' },
        ],
        parameters: {
          maxIsometricForce: 407.9,
          optimalFiberLength: 0.0534153,
          tendonSlackLength: 0.263817,
          pennationAngle: 0,
          source: myoArmStandIn('FCR'),
        },
      },
    ],
  },
  {
    id: 'flexor_carpi_ulnaris_l',
    displayName: 'Flexor carpi ulnaris, left',
    taTerm: 'Musculus flexor carpi ulnaris',
    innervation: 'Ulnar nerve',
    source: gray('Flexor carpi ulnaris'),
    units: [
      {
        id: 'flexor_carpi_ulnaris_l',
        displayName: 'Flexor carpi ulnaris, left',
        origin: 'flexor_carpi_ulnaris_origin_l_footprint',
        insertion: 'flexor_carpi_ulnaris_insertion_l_hook_of_hamate_bone',
        path: [
          { kind: 'site', site: 'flexor_carpi_ulnaris_l__via_1' },
          { kind: 'site', site: 'flexor_carpi_ulnaris_l__via_2' },
        ],
        parameters: {
          maxIsometricForce: 479.8,
          optimalFiberLength: 0.0589955,
          tendonSlackLength: 0.25796,
          pennationAngle: 0,
          source: myoArmStandIn('FCU'),
        },
      },
    ],
  },
  {
    id: 'extensor_carpi_radialis_l',
    displayName: 'Extensor carpi radialis, left',
    taTerm: 'Musculi extensores carpi radiales',
    innervation: 'Radial nerve, and its posterior interosseous branch for brevis',
    source: gray('Extensor carpi radialis'),
    units: [
      {
        id: 'extensor_carpi_radialis_longus_l',
        displayName: 'Extensor carpi radialis longus, left',
        origin: 'extensor_carpi_radialis_longus_origin_l_lateral_supracondylar_ridge',
        insertion: 'extensor_carpi_radialis_longus_insertion_l_base_of_digit_bone',
        path: [
          {
            kind: 'site',
            site: 'extensor_carpi_radialis_longus_path_l_radius_radial_styloid_process',
          },
          { kind: 'site', site: 'extensor_carpi_radialis_longus_l__via_1' },
          { kind: 'site', site: 'extensor_carpi_radialis_longus_l__via_2' },
        ],
        parameters: {
          maxIsometricForce: 337.3,
          optimalFiberLength: 0.0418006,
          tendonSlackLength: 0.288111,
          pennationAngle: 0,
          source: myoArmStandIn('ECRL'),
        },
      },
      {
        id: 'extensor_carpi_radialis_brevis_l',
        displayName: 'Extensor carpi radialis brevis, left',
        origin: 'extensor_carpi_radialis_brevis_origin_l_lateral_epicondyle_of_humerus',
        insertion:
          'extensor_carpi_radialis_brevis_insertion_l_styloid_process_of_third_metacarpal_bone',
        path: [
          { kind: 'site', site: 'extensor_carpi_radialis_brevis_l__via_1' },
          { kind: 'site', site: 'extensor_carpi_radialis_brevis_l__via_2' },
        ],
        parameters: {
          maxIsometricForce: 252.2,
          optimalFiberLength: 0.0472639,
          tendonSlackLength: 0.241612,
          pennationAngle: 0,
          source: myoArmStandIn('ECRB'),
        },
      },
    ],
  },
];

/** Every unit in the set, flattened, in a stable order. */
export const FOREARM_UNITS = FOREARM_MUSCLES.flatMap((group) => group.units);
