/**
 * The forearm and wrist muscle parameter set -- ticket N2.5.
 *
 * **Generated by `pnpm generate:forearm-muscles`. Do not edit.** CI runs the generator with
 * `--check`.
 *
 * ## What is transcribed here and what is not
 *
 * Peak force is the source's for all nine. So is the fiber length of supinator and anconeus, whose
 * actuators state an operating range the fiber length can be derived from -- and which come out at
 * 36 mm and 26 mm against a published 33 and 27.
 *
 * The other seven state no such range, so MuJoCo's default applies and no fiber length can be
 * derived from it: doing so gives 1.1 to 5.6 times published and one tendon of minus 16 mm. Those
 * seven carry `fiberLengthFromTravel`, and the compiler works out a fiber length from how far the
 * muscle travels on *this* skeleton, over the travel a muscle typically has. It is a stand-in good
 * to about half and it is labelled as one. OQ-022 has the argument, the numbers and the licence
 * reason the better source could not be vendored.
 *
 * *Where a muscle attaches* is ours throughout, as everywhere: Gray's anatomical statement located
 * on this subject by the dataset's own markers.
 *
 * ## The hand is nearly unmarked, and one muscle is missing because of it
 *
 * Beyond the wrist the dataset marks four points: the tubercles of the scaphoid and trapezium, the
 * hook of the hamate, and the base and styloid of the third metacarpal -- and the trapezium's only
 * on the right hand. Extensor carpi radialis brevis ends exactly where it should; the others end at
 * the nearest marked point along their own anatomy. Extensor carpi ulnaris and palmaris longus are
 * left out for want of anywhere to put them that would leave them a line of their own. The wrist
 * has two flexors, one radial and one ulnar, and two extensors, both radial.
 */

import { cite } from '@bs-humany/hsdl';
import type { MuscleGroup } from './schema.js';

/** Anatomy: which bony feature a muscle attaches to. The sites themselves are cited in M5.3. */
const gray = (muscle: string) => cite('gray1918', `Part IV, Myology: The ${muscle}`);

/** Parameters: the actuator in the vendored arm model they were derived from. */
const myoArm = (actuator: string) =>
  cite(
    'caggiano2022',
    `myoarm_r_muscle.xml, actuator name="${actuator}": peak force as stated. Fiber length from the ` +
      'operating range the actuator states where it has one, and otherwise from the travel ' +
      'measured on this skeleton (OQ-022), which the unit marks with fiberLengthFromTravel',
  );

export const FOREARM_MUSCLES: readonly MuscleGroup[] = [
  {
    id: 'pronator_teres_r',
    displayName: 'Pronator teres, right',
    taTerm: 'Musculus pronator teres',
    innervation: 'Median nerve',
    source: gray('Pronator teres'),
    units: [
      {
        id: 'pronator_teres_r',
        displayName: 'Pronator teres, right',
        origin: 'pronator_teres_origin_r_medial_epicondyle_of_humerus',
        insertion: 'pronator_teres_insertion_r_pronator_tuberosity',
        path: [
          { kind: 'site', site: 'pronator_teres_r__via_1' },
          { kind: 'site', site: 'pronator_teres_r__via_2' },
          { kind: 'site', site: 'pronator_teres_r__via_3' },
        ],
        parameters: {
          maxIsometricForce: 557.2,
          optimalFiberLength: 0.0344243,
          tendonSlackLength: 0.126588,
          pennationAngle: 0,
          source: myoArm('PT'),
        },
      },
    ],
  },
  {
    id: 'pronator_quadratus_r',
    displayName: 'Pronator quadratus, right',
    taTerm: 'Musculus pronator quadratus',
    innervation: 'Anterior interosseous nerve',
    source: gray('Pronator quadratus'),
    units: [
      {
        id: 'pronator_quadratus_r',
        displayName: 'Pronator quadratus, right',
        origin: 'pronator_quadratus_origin_r_medial_surface_of_ulna',
        insertion: 'pronator_quadratus_insertion_r_anterior_surface_of_radius',
        path: [],
        parameters: {
          maxIsometricForce: 284.7,
          optimalFiberLength: 0.0226202,
          tendonSlackLength: 0.00850706,
          pennationAngle: 0,
          source: myoArm('PQ'),
        },
      },
    ],
  },
  {
    id: 'supinator_r',
    displayName: 'Supinator, right',
    taTerm: 'Musculus supinator',
    innervation: 'Posterior interosseous nerve',
    source: gray('Supinator'),
    units: [
      {
        id: 'supinator_r',
        displayName: 'Supinator, right',
        origin: 'supinator_origin_r_supinator_crest',
        insertion: 'supinator_insertion_r_lateral_surface_of_radius',
        path: [{ kind: 'site', site: 'supinator_r__via_1' }],
        parameters: {
          maxIsometricForce: 339.132,
          optimalFiberLength: 0.0363066,
          tendonSlackLength: 0.022465,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoArm('SUP'),
        },
      },
    ],
  },
  {
    id: 'anconeus_r',
    displayName: 'Anconeus, right',
    taTerm: 'Musculus anconeus',
    innervation: 'Radial nerve',
    source: gray('Anconeus'),
    units: [
      {
        id: 'anconeus_r',
        displayName: 'Anconeus, right',
        origin: 'anconeus_origin_r_lateral_epicondyle_of_humerus',
        insertion: 'anconeus_insertion_r_olecranon',
        path: [],
        parameters: {
          maxIsometricForce: 262.904,
          optimalFiberLength: 0.0259443,
          tendonSlackLength: 0.0189105,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoArm('ANC'),
        },
      },
    ],
  },
  {
    id: 'flexor_carpi_radialis_r',
    displayName: 'Flexor carpi radialis, right',
    taTerm: 'Musculus flexor carpi radialis',
    innervation: 'Median nerve',
    source: gray('Flexor carpi radialis'),
    units: [
      {
        id: 'flexor_carpi_radialis_r',
        displayName: 'Flexor carpi radialis, right',
        origin: 'flexor_carpi_radialis_origin_r_medial_epicondyle_of_humerus',
        insertion: 'flexor_carpi_radialis_insertion_r_tubercle_of_scaphoid_bone',
        path: [{ kind: 'site', site: 'flexor_carpi_radialis_r__via_1' }],
        parameters: {
          maxIsometricForce: 407.9,
          optimalFiberLength: 0.0534153,
          tendonSlackLength: 0.263817,
          pennationAngle: 0,
          source: myoArm('FCR'),
        },
      },
    ],
  },
  {
    id: 'flexor_carpi_ulnaris_r',
    displayName: 'Flexor carpi ulnaris, right',
    taTerm: 'Musculus flexor carpi ulnaris',
    innervation: 'Ulnar nerve',
    source: gray('Flexor carpi ulnaris'),
    units: [
      {
        id: 'flexor_carpi_ulnaris_r',
        displayName: 'Flexor carpi ulnaris, right',
        origin: 'flexor_carpi_ulnaris_origin_r_footprint',
        insertion: 'flexor_carpi_ulnaris_insertion_r_hook_of_hamate_bone',
        path: [
          { kind: 'site', site: 'flexor_carpi_ulnaris_r__via_1' },
          { kind: 'site', site: 'flexor_carpi_ulnaris_r__via_2' },
        ],
        parameters: {
          maxIsometricForce: 479.8,
          optimalFiberLength: 0.0589955,
          tendonSlackLength: 0.25796,
          pennationAngle: 0,
          source: myoArm('FCU'),
        },
      },
    ],
  },
  {
    id: 'extensor_carpi_radialis_r',
    displayName: 'Extensor carpi radialis, right',
    taTerm: 'Musculi extensores carpi radiales',
    innervation: 'Radial nerve, and its posterior interosseous branch for brevis',
    source: gray('Extensor carpi radialis'),
    units: [
      {
        id: 'extensor_carpi_radialis_longus_r',
        displayName: 'Extensor carpi radialis longus, right',
        origin: 'extensor_carpi_radialis_longus_origin_r_lateral_supracondylar_ridge',
        insertion: 'extensor_carpi_radialis_longus_insertion_r_metacarpal_base',
        path: [
          { kind: 'site', site: 'extensor_carpi_radialis_longus_r__via_1' },
          { kind: 'site', site: 'extensor_carpi_radialis_longus_r__via_2' },
        ],
        parameters: {
          maxIsometricForce: 337.3,
          optimalFiberLength: 0.0418006,
          tendonSlackLength: 0.288111,
          pennationAngle: 0,
          source: myoArm('ECRL'),
        },
      },
      {
        id: 'extensor_carpi_radialis_brevis_r',
        displayName: 'Extensor carpi radialis brevis, right',
        origin: 'extensor_carpi_radialis_brevis_origin_r_lateral_epicondyle_of_humerus',
        insertion:
          'extensor_carpi_radialis_brevis_insertion_r_styloid_process_of_third_metacarpal_bone',
        path: [
          { kind: 'site', site: 'extensor_carpi_radialis_brevis_r__via_1' },
          { kind: 'site', site: 'extensor_carpi_radialis_brevis_r__via_2' },
        ],
        parameters: {
          maxIsometricForce: 252.2,
          optimalFiberLength: 0.0472639,
          tendonSlackLength: 0.241612,
          pennationAngle: 0,
          source: myoArm('ECRB'),
        },
      },
    ],
  },
  {
    id: 'pronator_teres_l',
    displayName: 'Pronator teres, left',
    taTerm: 'Musculus pronator teres',
    innervation: 'Median nerve',
    source: gray('Pronator teres'),
    units: [
      {
        id: 'pronator_teres_l',
        displayName: 'Pronator teres, left',
        origin: 'pronator_teres_origin_l_medial_epicondyle_of_humerus',
        insertion: 'pronator_teres_insertion_l_pronator_tuberosity',
        path: [
          { kind: 'site', site: 'pronator_teres_l__via_1' },
          { kind: 'site', site: 'pronator_teres_l__via_2' },
          { kind: 'site', site: 'pronator_teres_l__via_3' },
        ],
        parameters: {
          maxIsometricForce: 557.2,
          optimalFiberLength: 0.0344243,
          tendonSlackLength: 0.126588,
          pennationAngle: 0,
          source: myoArm('PT'),
        },
      },
    ],
  },
  {
    id: 'pronator_quadratus_l',
    displayName: 'Pronator quadratus, left',
    taTerm: 'Musculus pronator quadratus',
    innervation: 'Anterior interosseous nerve',
    source: gray('Pronator quadratus'),
    units: [
      {
        id: 'pronator_quadratus_l',
        displayName: 'Pronator quadratus, left',
        origin: 'pronator_quadratus_origin_l_medial_surface_of_ulna',
        insertion: 'pronator_quadratus_insertion_l_anterior_surface_of_radius',
        path: [],
        parameters: {
          maxIsometricForce: 284.7,
          optimalFiberLength: 0.0226202,
          tendonSlackLength: 0.00850706,
          pennationAngle: 0,
          source: myoArm('PQ'),
        },
      },
    ],
  },
  {
    id: 'supinator_l',
    displayName: 'Supinator, left',
    taTerm: 'Musculus supinator',
    innervation: 'Posterior interosseous nerve',
    source: gray('Supinator'),
    units: [
      {
        id: 'supinator_l',
        displayName: 'Supinator, left',
        origin: 'supinator_origin_l_supinator_crest',
        insertion: 'supinator_insertion_l_lateral_surface_of_radius',
        path: [{ kind: 'site', site: 'supinator_l__via_1' }],
        parameters: {
          maxIsometricForce: 339.132,
          optimalFiberLength: 0.0363066,
          tendonSlackLength: 0.022465,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoArm('SUP'),
        },
      },
    ],
  },
  {
    id: 'anconeus_l',
    displayName: 'Anconeus, left',
    taTerm: 'Musculus anconeus',
    innervation: 'Radial nerve',
    source: gray('Anconeus'),
    units: [
      {
        id: 'anconeus_l',
        displayName: 'Anconeus, left',
        origin: 'anconeus_origin_l_lateral_epicondyle_of_humerus',
        insertion: 'anconeus_insertion_l_olecranon',
        path: [],
        parameters: {
          maxIsometricForce: 262.904,
          optimalFiberLength: 0.0259443,
          tendonSlackLength: 0.0189105,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoArm('ANC'),
        },
      },
    ],
  },
  {
    id: 'flexor_carpi_radialis_l',
    displayName: 'Flexor carpi radialis, left',
    taTerm: 'Musculus flexor carpi radialis',
    innervation: 'Median nerve',
    source: gray('Flexor carpi radialis'),
    units: [
      {
        id: 'flexor_carpi_radialis_l',
        displayName: 'Flexor carpi radialis, left',
        origin: 'flexor_carpi_radialis_origin_l_medial_epicondyle_of_humerus',
        insertion: 'flexor_carpi_radialis_insertion_l_tubercle_of_scaphoid_bone',
        path: [{ kind: 'site', site: 'flexor_carpi_radialis_l__via_1' }],
        parameters: {
          maxIsometricForce: 407.9,
          optimalFiberLength: 0.0534153,
          tendonSlackLength: 0.263817,
          pennationAngle: 0,
          source: myoArm('FCR'),
        },
      },
    ],
  },
  {
    id: 'flexor_carpi_ulnaris_l',
    displayName: 'Flexor carpi ulnaris, left',
    taTerm: 'Musculus flexor carpi ulnaris',
    innervation: 'Ulnar nerve',
    source: gray('Flexor carpi ulnaris'),
    units: [
      {
        id: 'flexor_carpi_ulnaris_l',
        displayName: 'Flexor carpi ulnaris, left',
        origin: 'flexor_carpi_ulnaris_origin_l_footprint',
        insertion: 'flexor_carpi_ulnaris_insertion_l_hook_of_hamate_bone',
        path: [
          { kind: 'site', site: 'flexor_carpi_ulnaris_l__via_1' },
          { kind: 'site', site: 'flexor_carpi_ulnaris_l__via_2' },
        ],
        parameters: {
          maxIsometricForce: 479.8,
          optimalFiberLength: 0.0589955,
          tendonSlackLength: 0.25796,
          pennationAngle: 0,
          source: myoArm('FCU'),
        },
      },
    ],
  },
  {
    id: 'extensor_carpi_radialis_l',
    displayName: 'Extensor carpi radialis, left',
    taTerm: 'Musculi extensores carpi radiales',
    innervation: 'Radial nerve, and its posterior interosseous branch for brevis',
    source: gray('Extensor carpi radialis'),
    units: [
      {
        id: 'extensor_carpi_radialis_longus_l',
        displayName: 'Extensor carpi radialis longus, left',
        origin: 'extensor_carpi_radialis_longus_origin_l_lateral_supracondylar_ridge',
        insertion: 'extensor_carpi_radialis_longus_insertion_l_metacarpal_base',
        path: [
          { kind: 'site', site: 'extensor_carpi_radialis_longus_l__via_1' },
          { kind: 'site', site: 'extensor_carpi_radialis_longus_l__via_2' },
        ],
        parameters: {
          maxIsometricForce: 337.3,
          optimalFiberLength: 0.0418006,
          tendonSlackLength: 0.288111,
          pennationAngle: 0,
          source: myoArm('ECRL'),
        },
      },
      {
        id: 'extensor_carpi_radialis_brevis_l',
        displayName: 'Extensor carpi radialis brevis, left',
        origin: 'extensor_carpi_radialis_brevis_origin_l_lateral_epicondyle_of_humerus',
        insertion:
          'extensor_carpi_radialis_brevis_insertion_l_styloid_process_of_third_metacarpal_bone',
        path: [
          { kind: 'site', site: 'extensor_carpi_radialis_brevis_l__via_1' },
          { kind: 'site', site: 'extensor_carpi_radialis_brevis_l__via_2' },
        ],
        parameters: {
          maxIsometricForce: 252.2,
          optimalFiberLength: 0.0472639,
          tendonSlackLength: 0.241612,
          pennationAngle: 0,
          source: myoArm('ECRB'),
        },
      },
    ],
  },
];

/** Every unit in the set, flattened, in a stable order. */
export const FOREARM_UNITS = FOREARM_MUSCLES.flatMap((group) => group.units);
