/**
 * The shoulder girdle muscle parameter set -- what hangs the scapula and pins it to the ribs.
 *
 * **Generated by `pnpm generate:girdle-muscles`. Do not edit.** CI runs the generator with
 * `--check`.
 *
 * Trapezius in three parts from the skull, C7 and the mid-thoracic spine to the clavicle and
 * the scapula; levator scapulae and the two rhomboids from the cervical and upper thoracic spine
 * to the scapula's upper and medial borders; serratus anterior in three parts from the ribs to
 * the same borders from in front; pectoralis minor from the ribs to the coracoid. MyoSuite's arm
 * carries none of them, so the parameters are Seth 2019's, Table 1, from the thoracoscapular
 * shoulder model.
 */

import { cite } from '@bs-humany/hsdl';
import type { MuscleGroup } from './schema.js';

/** Anatomy: which bony feature a muscle attaches to. The sites themselves are cited in M5.3. */
const gray = (muscle: string) => cite('gray1918', `Part IV, Myology: The ${muscle}`);

/** Parameters: the row of Seth 2019's Table 1 they are, force and fibre and tendon as given. */
const seth = (row: string) =>
  cite(
    'seth2019',
    `Table 1, ${row}: max isometric force, optimal fiber length, tendon slack length, pennation`,
  );

export const GIRDLE_MUSCLES: readonly MuscleGroup[] = [
  {
    id: 'trapezius_r',
    displayName: 'Trapezius, right',
    taTerm: 'Musculus trapezius',
    innervation: 'Accessory nerve (XI); C3, C4',
    source: gray('Trapezius'),
    units: [
      {
        id: 'trapezius_upper_r',
        displayName: 'Trapezius, descending part, right',
        origin: 'trapezius_upper_origin_r_external_occipital_protuberance',
        insertion: 'trapezius_upper_insertion_r_acromial_end',
        path: [],
        parameters: {
          maxIsometricForce: 201.6,
          optimalFiberLength: 0.1116,
          tendonSlackLength: 0.027,
          pennationAngle: 0,
          source: seth('Trapezius, Clavicle'),
        },
      },
      {
        id: 'trapezius_middle_r',
        displayName: 'Trapezius, transverse part, right',
        origin: 'trapezius_middle_origin_r_spinous_process_tip',
        insertion: 'trapezius_middle_insertion_r_acromion',
        path: [],
        parameters: {
          maxIsometricForce: 1043,
          optimalFiberLength: 0.1127,
          tendonSlackLength: 0.027,
          pennationAngle: 0,
          source: seth('Trapezius, Scapula superior'),
        },
      },
      {
        id: 'trapezius_lower_r',
        displayName: 'Trapezius, ascending part, right',
        origin: 'trapezius_lower_origin_r_spinous_process_tip',
        insertion: 'trapezius_lower_insertion_r_spine_of_scapula',
        path: [],
        parameters: {
          maxIsometricForce: 884.8,
          optimalFiberLength: 0.103433,
          tendonSlackLength: 0.0334051,
          pennationAngle: 0,
          source: seth('Trapezius, Scapula middle + Trapezius, Scapula inferior'),
        },
      },
    ],
  },
  {
    id: 'levator_scapulae_r',
    displayName: 'Levator scapulae, right',
    taTerm: 'Musculus levator scapulae',
    innervation: 'Dorsal scapular nerve; C3, C4',
    source: gray('Levator scapulae'),
    units: [
      {
        id: 'levator_scapulae_r',
        displayName: 'Levator scapulae, right',
        origin: 'levator_scapulae_origin_r_transverse_process_tip_r',
        insertion: 'levator_scapulae_insertion_r_superior_angle_of_scapula',
        path: [],
        parameters: {
          maxIsometricForce: 280,
          optimalFiberLength: 0.1578,
          tendonSlackLength: 0.019,
          pennationAngle: 0,
          source: seth('Levator scapulae'),
        },
      },
    ],
  },
  {
    id: 'rhomboids_r',
    displayName: 'Rhomboidei, right',
    taTerm: 'Musculi rhomboidei',
    innervation: 'Dorsal scapular nerve',
    source: gray('Rhomboidei'),
    units: [
      {
        id: 'rhomboid_minor_r',
        displayName: 'Rhomboideus minor, right',
        origin: 'rhomboid_minor_origin_r_spinous_process_tip',
        insertion: 'rhomboid_minor_insertion_r_medial_border_of_scapula',
        path: [],
        parameters: {
          maxIsometricForce: 200.2,
          optimalFiberLength: 0.0986,
          tendonSlackLength: 0.015,
          pennationAngle: 0,
          source: seth('Rhomboideus, Superior'),
        },
      },
      {
        id: 'rhomboid_major_r',
        displayName: 'Rhomboideus major, right',
        origin: 'rhomboid_major_origin_r_spinous_process_tip',
        insertion: 'rhomboid_major_insertion_r_medial_border_of_scapula',
        path: [],
        parameters: {
          maxIsometricForce: 407.4,
          optimalFiberLength: 0.1152,
          tendonSlackLength: 0.028,
          pennationAngle: 0,
          source: seth('Rhomboideus, Inferior'),
        },
      },
    ],
  },
  {
    id: 'serratus_anterior_r',
    displayName: 'Serratus anterior, right',
    taTerm: 'Musculus serratus anterior',
    innervation: 'Long thoracic nerve',
    source: gray('Serratus anterior'),
    units: [
      {
        id: 'serratus_anterior_superior_r',
        displayName: 'Serratus anterior, superior part, right',
        origin: 'serratus_anterior_superior_origin_r_outer_surface_at_70',
        insertion: 'serratus_anterior_superior_insertion_r_superior_angle_of_scapula',
        path: [],
        parameters: {
          maxIsometricForce: 387.8,
          optimalFiberLength: 0.0945,
          tendonSlackLength: 0,
          pennationAngle: 0,
          source: seth('Serratus anterior, Superior'),
        },
      },
      {
        id: 'serratus_anterior_middle_r',
        displayName: 'Serratus anterior, middle part, right',
        origin: 'serratus_anterior_middle_origin_r_outer_surface_at_70',
        insertion: 'serratus_anterior_middle_insertion_r_medial_border_of_scapula',
        path: [],
        parameters: {
          maxIsometricForce: 508,
          optimalFiberLength: 0.1538,
          tendonSlackLength: 0.012,
          pennationAngle: 0,
          source: seth('Serratus anterior, Middle'),
        },
      },
      {
        id: 'serratus_anterior_inferior_r',
        displayName: 'Serratus anterior, inferior part, right',
        origin: 'serratus_anterior_inferior_origin_r_outer_surface_at_70',
        insertion: 'serratus_anterior_inferior_insertion_r_inferior_angle_of_scapula',
        path: [],
        parameters: {
          maxIsometricForce: 430,
          optimalFiberLength: 0.1587,
          tendonSlackLength: 0,
          pennationAngle: 0,
          source: seth('Serratus anterior, Inferior'),
        },
      },
    ],
  },
  {
    id: 'pectoralis_minor_r',
    displayName: 'Pectoralis minor, right',
    taTerm: 'Musculus pectoralis minor',
    innervation: 'Medial pectoral nerve',
    source: gray('Pectoralis minor'),
    units: [
      {
        id: 'pectoralis_minor_r',
        displayName: 'Pectoralis minor, right',
        origin: 'pectoralis_minor_origin_r_outer_surface_at_90',
        insertion: 'pectoralis_minor_insertion_r_coracoid_process',
        path: [],
        parameters: {
          maxIsometricForce: 429.8,
          optimalFiberLength: 0.1183,
          tendonSlackLength: 0.032,
          pennationAngle: 0,
          source: seth('Pectoralis minor'),
        },
      },
    ],
  },
  {
    id: 'trapezius_l',
    displayName: 'Trapezius, left',
    taTerm: 'Musculus trapezius',
    innervation: 'Accessory nerve (XI); C3, C4',
    source: gray('Trapezius'),
    units: [
      {
        id: 'trapezius_upper_l',
        displayName: 'Trapezius, descending part, left',
        origin: 'trapezius_upper_origin_l_external_occipital_protuberance',
        insertion: 'trapezius_upper_insertion_l_acromial_end',
        path: [],
        parameters: {
          maxIsometricForce: 201.6,
          optimalFiberLength: 0.1116,
          tendonSlackLength: 0.027,
          pennationAngle: 0,
          source: seth('Trapezius, Clavicle'),
        },
      },
      {
        id: 'trapezius_middle_l',
        displayName: 'Trapezius, transverse part, left',
        origin: 'trapezius_middle_origin_l_spinous_process_tip',
        insertion: 'trapezius_middle_insertion_l_acromion',
        path: [],
        parameters: {
          maxIsometricForce: 1043,
          optimalFiberLength: 0.1127,
          tendonSlackLength: 0.027,
          pennationAngle: 0,
          source: seth('Trapezius, Scapula superior'),
        },
      },
      {
        id: 'trapezius_lower_l',
        displayName: 'Trapezius, ascending part, left',
        origin: 'trapezius_lower_origin_l_spinous_process_tip',
        insertion: 'trapezius_lower_insertion_l_spine_of_scapula',
        path: [],
        parameters: {
          maxIsometricForce: 884.8,
          optimalFiberLength: 0.103433,
          tendonSlackLength: 0.0334051,
          pennationAngle: 0,
          source: seth('Trapezius, Scapula middle + Trapezius, Scapula inferior'),
        },
      },
    ],
  },
  {
    id: 'levator_scapulae_l',
    displayName: 'Levator scapulae, left',
    taTerm: 'Musculus levator scapulae',
    innervation: 'Dorsal scapular nerve; C3, C4',
    source: gray('Levator scapulae'),
    units: [
      {
        id: 'levator_scapulae_l',
        displayName: 'Levator scapulae, left',
        origin: 'levator_scapulae_origin_l_transverse_process_tip_l',
        insertion: 'levator_scapulae_insertion_l_superior_angle_of_scapula',
        path: [],
        parameters: {
          maxIsometricForce: 280,
          optimalFiberLength: 0.1578,
          tendonSlackLength: 0.019,
          pennationAngle: 0,
          source: seth('Levator scapulae'),
        },
      },
    ],
  },
  {
    id: 'rhomboids_l',
    displayName: 'Rhomboidei, left',
    taTerm: 'Musculi rhomboidei',
    innervation: 'Dorsal scapular nerve',
    source: gray('Rhomboidei'),
    units: [
      {
        id: 'rhomboid_minor_l',
        displayName: 'Rhomboideus minor, left',
        origin: 'rhomboid_minor_origin_l_spinous_process_tip',
        insertion: 'rhomboid_minor_insertion_l_medial_border_of_scapula',
        path: [],
        parameters: {
          maxIsometricForce: 200.2,
          optimalFiberLength: 0.0986,
          tendonSlackLength: 0.015,
          pennationAngle: 0,
          source: seth('Rhomboideus, Superior'),
        },
      },
      {
        id: 'rhomboid_major_l',
        displayName: 'Rhomboideus major, left',
        origin: 'rhomboid_major_origin_l_spinous_process_tip',
        insertion: 'rhomboid_major_insertion_l_medial_border_of_scapula',
        path: [],
        parameters: {
          maxIsometricForce: 407.4,
          optimalFiberLength: 0.1152,
          tendonSlackLength: 0.028,
          pennationAngle: 0,
          source: seth('Rhomboideus, Inferior'),
        },
      },
    ],
  },
  {
    id: 'serratus_anterior_l',
    displayName: 'Serratus anterior, left',
    taTerm: 'Musculus serratus anterior',
    innervation: 'Long thoracic nerve',
    source: gray('Serratus anterior'),
    units: [
      {
        id: 'serratus_anterior_superior_l',
        displayName: 'Serratus anterior, superior part, left',
        origin: 'serratus_anterior_superior_origin_l_outer_surface_at_70',
        insertion: 'serratus_anterior_superior_insertion_l_superior_angle_of_scapula',
        path: [],
        parameters: {
          maxIsometricForce: 387.8,
          optimalFiberLength: 0.0945,
          tendonSlackLength: 0,
          pennationAngle: 0,
          source: seth('Serratus anterior, Superior'),
        },
      },
      {
        id: 'serratus_anterior_middle_l',
        displayName: 'Serratus anterior, middle part, left',
        origin: 'serratus_anterior_middle_origin_l_outer_surface_at_70',
        insertion: 'serratus_anterior_middle_insertion_l_medial_border_of_scapula',
        path: [],
        parameters: {
          maxIsometricForce: 508,
          optimalFiberLength: 0.1538,
          tendonSlackLength: 0.012,
          pennationAngle: 0,
          source: seth('Serratus anterior, Middle'),
        },
      },
      {
        id: 'serratus_anterior_inferior_l',
        displayName: 'Serratus anterior, inferior part, left',
        origin: 'serratus_anterior_inferior_origin_l_outer_surface_at_70',
        insertion: 'serratus_anterior_inferior_insertion_l_inferior_angle_of_scapula',
        path: [],
        parameters: {
          maxIsometricForce: 430,
          optimalFiberLength: 0.1587,
          tendonSlackLength: 0,
          pennationAngle: 0,
          source: seth('Serratus anterior, Inferior'),
        },
      },
    ],
  },
  {
    id: 'pectoralis_minor_l',
    displayName: 'Pectoralis minor, left',
    taTerm: 'Musculus pectoralis minor',
    innervation: 'Medial pectoral nerve',
    source: gray('Pectoralis minor'),
    units: [
      {
        id: 'pectoralis_minor_l',
        displayName: 'Pectoralis minor, left',
        origin: 'pectoralis_minor_origin_l_outer_surface_at_90',
        insertion: 'pectoralis_minor_insertion_l_coracoid_process',
        path: [],
        parameters: {
          maxIsometricForce: 429.8,
          optimalFiberLength: 0.1183,
          tendonSlackLength: 0.032,
          pennationAngle: 0,
          source: seth('Pectoralis minor'),
        },
      },
    ],
  },
];

/** Every unit in the set, flattened, in a stable order. */
export const GIRDLE_UNITS = GIRDLE_MUSCLES.flatMap((g) => g.units);
