/**
 * The hip muscle parameter set -- ticket N2.4, the rest of the lower limb.
 *
 * **Generated by `pnpm generate:hip-muscles`. Do not edit.** The numbers are extracted from the
 * vendored MyoSuite leg model rather than copied out of it, so the value here and the value in the
 * cited file cannot disagree; CI runs the generator with `--check`.
 *
 * ## Where each half comes from
 *
 * The same split as every other set. *Where a muscle attaches* is ours: Gray's anatomical
 * statement located on this subject by the dataset's own markers. *What a muscle can do* is
 * MyoSuite's: peak force is a scalar and crosses frames without reinterpretation. The two lengths
 * are neither -- both are measured against a skeleton -- so both are derived at compile against
 * this one, which is where `fittedTendonSlack` and `deriveOptimalFiberLength` explain themselves.
 *
 * ## Twenty-one lines of action
 *
 * Three apiece for the gluteals and four for adductor magnus, because these are the muscles
 * M-ADR-005 was written for. Gluteus medius is the plain case: its front fibres flex and rotate
 * the femur inwards and its back fibres extend and rotate it out, so one line down the middle
 * does neither. Each part arises from the stretch of bone Gray gives it.
 *
 * ## Three of them are not only hip muscles
 *
 * Tensor fasciae latae ends in the iliotibial tract and the tract reaches the tibia; gracilis and
 * sartorius run to the pes anserinus below the knee. They cross two joints, and the moment module
 * reports a muscle against every coordinate it crosses rather than the one it is filed under.
 */

import { cite } from '@bs-humany/hsdl';
import type { MuscleGroup } from './schema.js';

/** Anatomy: which bony feature a muscle attaches to. The sites themselves are cited in M5.3. */
const gray = (muscle: string) => cite('gray1918', `Part IV, Myology: The ${muscle}`);

/** Parameters: the actuator in the vendored leg model they were derived from. */
const myoLegs = (actuator: string) =>
  cite(
    'caggiano2022',
    `myolegs_muscle.xml, actuator general name="${actuator}": gainprm force, and optimal fiber ` +
      'length and tendon slack length derived from gainprm range with lengthrange',
  );

export const HIP_MUSCLES: readonly MuscleGroup[] = [
  {
    id: 'gluteus_maximus_r',
    displayName: 'Gluteus maximus, right',
    taTerm: 'Musculus gluteus maximus',
    innervation: 'Inferior gluteal nerve',
    source: gray('Gluteus maximus'),
    units: [
      {
        id: 'gluteus_maximus_superior_r',
        displayName: 'Gluteus maximus, superior part, right',
        origin: 'gluteus_maximus_origin_r_gluteal_surface_of_ilium',
        insertion: 'gluteus_maximus_insertion_r_gluteal_tuberosity',
        path: [{ kind: 'site', site: 'gluteus_maximus_superior_r__via_1' }],
        parameters: {
          maxIsometricForce: 1293.79,
          optimalFiberLength: 0.147,
          tendonSlackLength: 0.0488403,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoLegs('glmax1_r'),
        },
      },
      {
        id: 'gluteus_maximus_middle_r',
        displayName: 'Gluteus maximus, middle part, right',
        origin: 'gluteus_maximus_origin_r_dorsal_surface_of_sacrum',
        insertion: 'gluteus_maximus_insertion_r_gluteal_tuberosity',
        path: [{ kind: 'site', site: 'gluteus_maximus_middle_r__via_1' }],
        parameters: {
          maxIsometricForce: 1308.46,
          optimalFiberLength: 0.157,
          tendonSlackLength: 0.067887,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoLegs('glmax2_r'),
        },
      },
      {
        id: 'gluteus_maximus_inferior_r',
        displayName: 'Gluteus maximus, inferior part, right',
        origin: 'gluteus_maximus_origin_r_ischial_tuberosity',
        insertion: 'gluteus_maximus_insertion_r_gluteal_tuberosity',
        path: [],
        parameters: {
          maxIsometricForce: 928.184,
          optimalFiberLength: 0.408049,
          tendonSlackLength: -0.25971,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoLegs('glmax3_r'),
        },
      },
    ],
  },
  {
    id: 'gluteus_medius_r',
    displayName: 'Gluteus medius, right',
    taTerm: 'Musculus gluteus medius',
    innervation: 'Superior gluteal nerve',
    source: gray('Gluteus medius'),
    units: [
      {
        id: 'gluteus_medius_anterior_r',
        displayName: 'Gluteus medius, anterior part, right',
        origin: 'gluteus_medius_origin_r_anterior_gluteal_line',
        insertion: 'gluteus_medius_insertion_r_greater_trochanter',
        path: [],
        parameters: {
          maxIsometricForce: 1018.46,
          optimalFiberLength: 0.0729997,
          tendonSlackLength: 0.0558169,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoLegs('glmed1_r'),
        },
      },
      {
        id: 'gluteus_medius_middle_r',
        displayName: 'Gluteus medius, middle part, right',
        origin: 'gluteus_medius_origin_r_outer_lip_of_iliac_crest',
        insertion: 'gluteus_medius_insertion_r_greater_trochanter',
        path: [],
        parameters: {
          maxIsometricForce: 715.019,
          optimalFiberLength: 0.0730005,
          tendonSlackLength: 0.0652487,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoLegs('glmed2_r'),
        },
      },
      {
        id: 'gluteus_medius_posterior_r',
        displayName: 'Gluteus medius, posterior part, right',
        origin: 'gluteus_medius_origin_r_posterior_gluteal_line',
        insertion: 'gluteus_medius_insertion_r_greater_trochanter',
        path: [],
        parameters: {
          maxIsometricForce: 828.084,
          optimalFiberLength: 0.0730003,
          tendonSlackLength: 0.0452328,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoLegs('glmed3_r'),
        },
      },
    ],
  },
  {
    id: 'gluteus_minimus_r',
    displayName: 'Gluteus minimus, right',
    taTerm: 'Musculus gluteus minimus',
    innervation: 'Superior gluteal nerve',
    source: gray('Gluteus minimus'),
    units: [
      {
        id: 'gluteus_minimus_anterior_r',
        displayName: 'Gluteus minimus, anterior part, right',
        origin: 'gluteus_minimus_origin_r_anterior_gluteal_line',
        insertion: 'gluteus_minimus_insertion_r_greater_trochanter',
        path: [],
        parameters: {
          maxIsometricForce: 357.161,
          optimalFiberLength: 0.0680183,
          tendonSlackLength: 0.0161118,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoLegs('glmin1_r'),
        },
      },
      {
        id: 'gluteus_minimus_middle_r',
        displayName: 'Gluteus minimus, middle part, right',
        origin: 'gluteus_minimus_origin_r_footprint',
        insertion: 'gluteus_minimus_insertion_r_greater_trochanter',
        path: [],
        parameters: {
          maxIsometricForce: 392.017,
          optimalFiberLength: 0.0572124,
          tendonSlackLength: 0.0241584,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoLegs('glmin2_r'),
        },
      },
      {
        id: 'gluteus_minimus_posterior_r',
        displayName: 'Gluteus minimus, posterior part, right',
        origin: 'gluteus_minimus_origin_r_inferior_gluteal_line',
        insertion: 'gluteus_minimus_insertion_r_greater_trochanter',
        path: [],
        parameters: {
          maxIsometricForce: 386.063,
          optimalFiberLength: 0.0502034,
          tendonSlackLength: 0.029574,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoLegs('glmin3_r'),
        },
      },
    ],
  },
  {
    id: 'iliopsoas_r',
    displayName: 'Iliopsoas, right',
    taTerm: 'Musculus iliopsoas',
    innervation: 'Femoral nerve, and the lumbar plexus directly for psoas',
    source: gray('Iliopsoas'),
    units: [
      {
        id: 'iliacus_r',
        displayName: 'Iliacus, right',
        origin: 'iliacus_origin_r_iliac_fossa',
        insertion: 'iliacus_insertion_r_lesser_trochanter',
        path: [
          { kind: 'site', site: 'iliacus_path_r_iliopubic_eminence' },
          { kind: 'site', site: 'iliacus_r__via_1' },
        ],
        parameters: {
          maxIsometricForce: 977.408,
          optimalFiberLength: 0.1066,
          tendonSlackLength: 0.0961208,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoLegs('iliacus_r'),
        },
      },
      {
        id: 'psoas_major_r',
        displayName: 'Psoas major, right',
        origin: 'psoas_major_origin_r_vertebral_body',
        insertion: 'psoas_major_insertion_r_lesser_trochanter',
        path: [
          { kind: 'site', site: 'psoas_major_path_r_iliopubic_eminence' },
          { kind: 'site', site: 'psoas_major_r__via_1' },
        ],
        parameters: {
          maxIsometricForce: 1385.41,
          optimalFiberLength: 0.1169,
          tendonSlackLength: 0.0995425,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoLegs('psoas_r'),
        },
      },
    ],
  },
  {
    id: 'adductor_longus_r',
    displayName: 'Adductor longus, right',
    taTerm: 'Musculus adductor longus',
    innervation: 'Obturator nerve',
    source: gray('Adductor longus'),
    units: [
      {
        id: 'adductor_longus_r',
        displayName: 'Adductor longus, right',
        origin: 'adductor_longus_origin_r_pubic_crest',
        insertion: 'adductor_longus_insertion_r_linea_aspera',
        path: [],
        parameters: {
          maxIsometricForce: 881.938,
          optimalFiberLength: 0.1082,
          tendonSlackLength: 0.131799,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoLegs('addlong_r'),
        },
      },
    ],
  },
  {
    id: 'adductor_brevis_r',
    displayName: 'Adductor brevis, right',
    taTerm: 'Musculus adductor brevis',
    innervation: 'Obturator nerve',
    source: gray('Adductor brevis'),
    units: [
      {
        id: 'adductor_brevis_r',
        displayName: 'Adductor brevis, right',
        origin: 'adductor_brevis_origin_r_inferior_pubic_ramus',
        insertion: 'adductor_brevis_insertion_r_pectineal_line_of_femur',
        path: [],
        parameters: {
          maxIsometricForce: 604.625,
          optimalFiberLength: 0.1031,
          tendonSlackLength: 0.0354505,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoLegs('addbrev_r'),
        },
      },
    ],
  },
  {
    id: 'adductor_magnus_r',
    displayName: 'Adductor magnus, right',
    taTerm: 'Musculus adductor magnus',
    innervation: 'Obturator nerve, and the tibial division of the sciatic for the ischial part',
    source: gray('Adductor magnus'),
    units: [
      {
        id: 'adductor_magnus_proximal_r',
        displayName: 'Adductor magnus, proximal part, right',
        origin: 'adductor_magnus_origin_r_inferior_pubic_ramus',
        insertion: 'adductor_magnus_insertion_r_gluteal_tuberosity',
        path: [],
        parameters: {
          maxIsometricForce: 575.376,
          optimalFiberLength: 0.1056,
          tendonSlackLength: 0.040324,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoLegs('addmagProx_r'),
        },
      },
      {
        id: 'adductor_magnus_middle_r',
        displayName: 'Adductor magnus, middle part, right',
        origin: 'adductor_magnus_origin_r_ramus_of_ischium',
        insertion: 'adductor_magnus_insertion_r_linea_aspera',
        path: [],
        parameters: {
          maxIsometricForce: 577.178,
          optimalFiberLength: 0.137701,
          tendonSlackLength: 0.0466272,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoLegs('addmagMid_r'),
        },
      },
      {
        id: 'adductor_magnus_distal_r',
        displayName: 'Adductor magnus, distal part, right',
        origin: 'adductor_magnus_origin_r_ischial_tuberosity',
        insertion: 'adductor_magnus_insertion_r_medial_supracondylar_line',
        path: [],
        parameters: {
          maxIsometricForce: 576.186,
          optimalFiberLength: 0.1772,
          tendonSlackLength: 0.087381,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoLegs('addmagDist_r'),
        },
      },
      {
        id: 'adductor_magnus_ischiocondylar_r',
        displayName: 'Adductor magnus, ischiocondylar part, right',
        origin: 'adductor_magnus_origin_r_ischial_tuberosity',
        insertion: 'adductor_magnus_insertion_r_adductor_tubercle',
        path: [],
        parameters: {
          maxIsometricForce: 564.689,
          optimalFiberLength: 0.1562,
          tendonSlackLength: 0.216343,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoLegs('addmagIsch_r'),
        },
      },
    ],
  },
  {
    id: 'piriformis_r',
    displayName: 'Piriformis, right',
    taTerm: 'Musculus piriformis',
    innervation: 'Nerve to piriformis, from the sacral plexus',
    source: gray('Piriformis'),
    units: [
      {
        id: 'piriformis_r',
        displayName: 'Piriformis, right',
        origin: 'piriformis_origin_r_pelvic_surface_of_sacrum',
        insertion: 'piriformis_insertion_r_greater_trochanter',
        path: [],
        parameters: {
          maxIsometricForce: 819.319,
          optimalFiberLength: 0.0421451,
          tendonSlackLength: 0.0911449,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoLegs('piri_r'),
        },
      },
    ],
  },
  {
    id: 'tensor_fasciae_latae_r',
    displayName: 'Tensor fasciae latae, right',
    taTerm: 'Musculus tensor fasciae latae',
    innervation: 'Superior gluteal nerve',
    source: gray('Tensor fasciae latae'),
    units: [
      {
        id: 'tensor_fasciae_latae_r',
        displayName: 'Tensor fasciae latae, right',
        origin: 'tensor_fasciae_latae_origin_r_footprint',
        insertion: 'tensor_fasciae_latae_insertion_r_tubercle_of_iliotibial_tract',
        path: [
          { kind: 'site', site: 'tensor_fasciae_latae_r__via_1' },
          { kind: 'site', site: 'tensor_fasciae_latae_r__via_2' },
        ],
        parameters: {
          maxIsometricForce: 265.756,
          optimalFiberLength: 0.158036,
          tendonSlackLength: 0.357317,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoLegs('tfl_r'),
        },
      },
    ],
  },
  {
    id: 'gracilis_r',
    displayName: 'Gracilis, right',
    taTerm: 'Musculus gracilis',
    innervation: 'Obturator nerve',
    source: gray('Gracilis'),
    units: [
      {
        id: 'gracilis_r',
        displayName: 'Gracilis, right',
        origin: 'gracilis_origin_r_footprint',
        insertion: 'gracilis_insertion_r_medial_surface_of_tibia',
        path: [{ kind: 'site', site: 'gracilis_r__via_1' }],
        parameters: {
          maxIsometricForce: 280.917,
          optimalFiberLength: 0.2278,
          tendonSlackLength: 0.172014,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoLegs('grac_r'),
        },
      },
    ],
  },
  {
    id: 'sartorius_r',
    displayName: 'Sartorius, right',
    taTerm: 'Musculus sartorius',
    innervation: 'Femoral nerve',
    source: gray('Sartorius'),
    units: [
      {
        id: 'sartorius_r',
        displayName: 'Sartorius, right',
        origin: 'sartorius_origin_r_anterior_superior_iliac_spine',
        insertion: 'sartorius_insertion_r_medial_surface_of_tibia',
        path: [
          { kind: 'site', site: 'sartorius_r__via_1' },
          { kind: 'site', site: 'sartorius_r__via_2' },
          { kind: 'site', site: 'sartorius_r__via_3' },
        ],
        parameters: {
          maxIsometricForce: 245.514,
          optimalFiberLength: 0.403002,
          tendonSlackLength: 0.123998,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoLegs('sart_r'),
        },
      },
    ],
  },
  {
    id: 'gluteus_maximus_l',
    displayName: 'Gluteus maximus, left',
    taTerm: 'Musculus gluteus maximus',
    innervation: 'Inferior gluteal nerve',
    source: gray('Gluteus maximus'),
    units: [
      {
        id: 'gluteus_maximus_superior_l',
        displayName: 'Gluteus maximus, superior part, left',
        origin: 'gluteus_maximus_origin_l_gluteal_surface_of_ilium',
        insertion: 'gluteus_maximus_insertion_l_gluteal_tuberosity',
        path: [{ kind: 'site', site: 'gluteus_maximus_superior_l__via_1' }],
        parameters: {
          maxIsometricForce: 1293.79,
          optimalFiberLength: 0.147,
          tendonSlackLength: 0.0488403,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoLegs('glmax1_r'),
        },
      },
      {
        id: 'gluteus_maximus_middle_l',
        displayName: 'Gluteus maximus, middle part, left',
        origin: 'gluteus_maximus_origin_l_dorsal_surface_of_sacrum',
        insertion: 'gluteus_maximus_insertion_l_gluteal_tuberosity',
        path: [{ kind: 'site', site: 'gluteus_maximus_middle_l__via_1' }],
        parameters: {
          maxIsometricForce: 1308.46,
          optimalFiberLength: 0.157,
          tendonSlackLength: 0.067887,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoLegs('glmax2_r'),
        },
      },
      {
        id: 'gluteus_maximus_inferior_l',
        displayName: 'Gluteus maximus, inferior part, left',
        origin: 'gluteus_maximus_origin_l_ischial_tuberosity',
        insertion: 'gluteus_maximus_insertion_l_gluteal_tuberosity',
        path: [],
        parameters: {
          maxIsometricForce: 928.184,
          optimalFiberLength: 0.408049,
          tendonSlackLength: -0.25971,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoLegs('glmax3_r'),
        },
      },
    ],
  },
  {
    id: 'gluteus_medius_l',
    displayName: 'Gluteus medius, left',
    taTerm: 'Musculus gluteus medius',
    innervation: 'Superior gluteal nerve',
    source: gray('Gluteus medius'),
    units: [
      {
        id: 'gluteus_medius_anterior_l',
        displayName: 'Gluteus medius, anterior part, left',
        origin: 'gluteus_medius_origin_l_anterior_gluteal_line',
        insertion: 'gluteus_medius_insertion_l_greater_trochanter',
        path: [],
        parameters: {
          maxIsometricForce: 1018.46,
          optimalFiberLength: 0.0729997,
          tendonSlackLength: 0.0558169,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoLegs('glmed1_r'),
        },
      },
      {
        id: 'gluteus_medius_middle_l',
        displayName: 'Gluteus medius, middle part, left',
        origin: 'gluteus_medius_origin_l_outer_lip_of_iliac_crest',
        insertion: 'gluteus_medius_insertion_l_greater_trochanter',
        path: [],
        parameters: {
          maxIsometricForce: 715.019,
          optimalFiberLength: 0.0730005,
          tendonSlackLength: 0.0652487,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoLegs('glmed2_r'),
        },
      },
      {
        id: 'gluteus_medius_posterior_l',
        displayName: 'Gluteus medius, posterior part, left',
        origin: 'gluteus_medius_origin_l_posterior_gluteal_line',
        insertion: 'gluteus_medius_insertion_l_greater_trochanter',
        path: [],
        parameters: {
          maxIsometricForce: 828.084,
          optimalFiberLength: 0.0730003,
          tendonSlackLength: 0.0452328,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoLegs('glmed3_r'),
        },
      },
    ],
  },
  {
    id: 'gluteus_minimus_l',
    displayName: 'Gluteus minimus, left',
    taTerm: 'Musculus gluteus minimus',
    innervation: 'Superior gluteal nerve',
    source: gray('Gluteus minimus'),
    units: [
      {
        id: 'gluteus_minimus_anterior_l',
        displayName: 'Gluteus minimus, anterior part, left',
        origin: 'gluteus_minimus_origin_l_anterior_gluteal_line',
        insertion: 'gluteus_minimus_insertion_l_greater_trochanter',
        path: [],
        parameters: {
          maxIsometricForce: 357.161,
          optimalFiberLength: 0.0680183,
          tendonSlackLength: 0.0161118,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoLegs('glmin1_r'),
        },
      },
      {
        id: 'gluteus_minimus_middle_l',
        displayName: 'Gluteus minimus, middle part, left',
        origin: 'gluteus_minimus_origin_l_footprint',
        insertion: 'gluteus_minimus_insertion_l_greater_trochanter',
        path: [],
        parameters: {
          maxIsometricForce: 392.017,
          optimalFiberLength: 0.0572124,
          tendonSlackLength: 0.0241584,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoLegs('glmin2_r'),
        },
      },
      {
        id: 'gluteus_minimus_posterior_l',
        displayName: 'Gluteus minimus, posterior part, left',
        origin: 'gluteus_minimus_origin_l_inferior_gluteal_line',
        insertion: 'gluteus_minimus_insertion_l_greater_trochanter',
        path: [],
        parameters: {
          maxIsometricForce: 386.063,
          optimalFiberLength: 0.0502034,
          tendonSlackLength: 0.029574,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoLegs('glmin3_r'),
        },
      },
    ],
  },
  {
    id: 'iliopsoas_l',
    displayName: 'Iliopsoas, left',
    taTerm: 'Musculus iliopsoas',
    innervation: 'Femoral nerve, and the lumbar plexus directly for psoas',
    source: gray('Iliopsoas'),
    units: [
      {
        id: 'iliacus_l',
        displayName: 'Iliacus, left',
        origin: 'iliacus_origin_l_iliac_fossa',
        insertion: 'iliacus_insertion_l_lesser_trochanter',
        path: [
          { kind: 'site', site: 'iliacus_path_l_iliopubic_eminence' },
          { kind: 'site', site: 'iliacus_l__via_1' },
        ],
        parameters: {
          maxIsometricForce: 977.408,
          optimalFiberLength: 0.1066,
          tendonSlackLength: 0.0961208,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoLegs('iliacus_r'),
        },
      },
      {
        id: 'psoas_major_l',
        displayName: 'Psoas major, left',
        origin: 'psoas_major_origin_l_vertebral_body',
        insertion: 'psoas_major_insertion_l_lesser_trochanter',
        path: [
          { kind: 'site', site: 'psoas_major_path_l_iliopubic_eminence' },
          { kind: 'site', site: 'psoas_major_l__via_1' },
        ],
        parameters: {
          maxIsometricForce: 1385.41,
          optimalFiberLength: 0.1169,
          tendonSlackLength: 0.0995425,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoLegs('psoas_r'),
        },
      },
    ],
  },
  {
    id: 'adductor_longus_l',
    displayName: 'Adductor longus, left',
    taTerm: 'Musculus adductor longus',
    innervation: 'Obturator nerve',
    source: gray('Adductor longus'),
    units: [
      {
        id: 'adductor_longus_l',
        displayName: 'Adductor longus, left',
        origin: 'adductor_longus_origin_l_pubic_crest',
        insertion: 'adductor_longus_insertion_l_linea_aspera',
        path: [],
        parameters: {
          maxIsometricForce: 881.938,
          optimalFiberLength: 0.1082,
          tendonSlackLength: 0.131799,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoLegs('addlong_r'),
        },
      },
    ],
  },
  {
    id: 'adductor_brevis_l',
    displayName: 'Adductor brevis, left',
    taTerm: 'Musculus adductor brevis',
    innervation: 'Obturator nerve',
    source: gray('Adductor brevis'),
    units: [
      {
        id: 'adductor_brevis_l',
        displayName: 'Adductor brevis, left',
        origin: 'adductor_brevis_origin_l_inferior_pubic_ramus',
        insertion: 'adductor_brevis_insertion_l_pectineal_line_of_femur',
        path: [],
        parameters: {
          maxIsometricForce: 604.625,
          optimalFiberLength: 0.1031,
          tendonSlackLength: 0.0354505,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoLegs('addbrev_r'),
        },
      },
    ],
  },
  {
    id: 'adductor_magnus_l',
    displayName: 'Adductor magnus, left',
    taTerm: 'Musculus adductor magnus',
    innervation: 'Obturator nerve, and the tibial division of the sciatic for the ischial part',
    source: gray('Adductor magnus'),
    units: [
      {
        id: 'adductor_magnus_proximal_l',
        displayName: 'Adductor magnus, proximal part, left',
        origin: 'adductor_magnus_origin_l_inferior_pubic_ramus',
        insertion: 'adductor_magnus_insertion_l_gluteal_tuberosity',
        path: [],
        parameters: {
          maxIsometricForce: 575.376,
          optimalFiberLength: 0.1056,
          tendonSlackLength: 0.040324,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoLegs('addmagProx_r'),
        },
      },
      {
        id: 'adductor_magnus_middle_l',
        displayName: 'Adductor magnus, middle part, left',
        origin: 'adductor_magnus_origin_l_ramus_of_ischium',
        insertion: 'adductor_magnus_insertion_l_linea_aspera',
        path: [],
        parameters: {
          maxIsometricForce: 577.178,
          optimalFiberLength: 0.137701,
          tendonSlackLength: 0.0466272,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoLegs('addmagMid_r'),
        },
      },
      {
        id: 'adductor_magnus_distal_l',
        displayName: 'Adductor magnus, distal part, left',
        origin: 'adductor_magnus_origin_l_ischial_tuberosity',
        insertion: 'adductor_magnus_insertion_l_medial_supracondylar_line',
        path: [],
        parameters: {
          maxIsometricForce: 576.186,
          optimalFiberLength: 0.1772,
          tendonSlackLength: 0.087381,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoLegs('addmagDist_r'),
        },
      },
      {
        id: 'adductor_magnus_ischiocondylar_l',
        displayName: 'Adductor magnus, ischiocondylar part, left',
        origin: 'adductor_magnus_origin_l_ischial_tuberosity',
        insertion: 'adductor_magnus_insertion_l_adductor_tubercle',
        path: [],
        parameters: {
          maxIsometricForce: 564.689,
          optimalFiberLength: 0.1562,
          tendonSlackLength: 0.216343,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoLegs('addmagIsch_r'),
        },
      },
    ],
  },
  {
    id: 'piriformis_l',
    displayName: 'Piriformis, left',
    taTerm: 'Musculus piriformis',
    innervation: 'Nerve to piriformis, from the sacral plexus',
    source: gray('Piriformis'),
    units: [
      {
        id: 'piriformis_l',
        displayName: 'Piriformis, left',
        origin: 'piriformis_origin_l_pelvic_surface_of_sacrum',
        insertion: 'piriformis_insertion_l_greater_trochanter',
        path: [],
        parameters: {
          maxIsometricForce: 819.319,
          optimalFiberLength: 0.0421451,
          tendonSlackLength: 0.0911449,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoLegs('piri_r'),
        },
      },
    ],
  },
  {
    id: 'tensor_fasciae_latae_l',
    displayName: 'Tensor fasciae latae, left',
    taTerm: 'Musculus tensor fasciae latae',
    innervation: 'Superior gluteal nerve',
    source: gray('Tensor fasciae latae'),
    units: [
      {
        id: 'tensor_fasciae_latae_l',
        displayName: 'Tensor fasciae latae, left',
        origin: 'tensor_fasciae_latae_origin_l_footprint',
        insertion: 'tensor_fasciae_latae_insertion_l_tubercle_of_iliotibial_tract',
        path: [
          { kind: 'site', site: 'tensor_fasciae_latae_l__via_1' },
          { kind: 'site', site: 'tensor_fasciae_latae_l__via_2' },
        ],
        parameters: {
          maxIsometricForce: 265.756,
          optimalFiberLength: 0.158036,
          tendonSlackLength: 0.357317,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoLegs('tfl_r'),
        },
      },
    ],
  },
  {
    id: 'gracilis_l',
    displayName: 'Gracilis, left',
    taTerm: 'Musculus gracilis',
    innervation: 'Obturator nerve',
    source: gray('Gracilis'),
    units: [
      {
        id: 'gracilis_l',
        displayName: 'Gracilis, left',
        origin: 'gracilis_origin_l_footprint',
        insertion: 'gracilis_insertion_l_medial_surface_of_tibia',
        path: [{ kind: 'site', site: 'gracilis_l__via_1' }],
        parameters: {
          maxIsometricForce: 280.917,
          optimalFiberLength: 0.2278,
          tendonSlackLength: 0.172014,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoLegs('grac_r'),
        },
      },
    ],
  },
  {
    id: 'sartorius_l',
    displayName: 'Sartorius, left',
    taTerm: 'Musculus sartorius',
    innervation: 'Femoral nerve',
    source: gray('Sartorius'),
    units: [
      {
        id: 'sartorius_l',
        displayName: 'Sartorius, left',
        origin: 'sartorius_origin_l_anterior_superior_iliac_spine',
        insertion: 'sartorius_insertion_l_medial_surface_of_tibia',
        path: [
          { kind: 'site', site: 'sartorius_l__via_1' },
          { kind: 'site', site: 'sartorius_l__via_2' },
          { kind: 'site', site: 'sartorius_l__via_3' },
        ],
        parameters: {
          maxIsometricForce: 245.514,
          optimalFiberLength: 0.403002,
          tendonSlackLength: 0.123998,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoLegs('sart_r'),
        },
      },
    ],
  },
];

/** Every unit in the set, flattened, in a stable order. */
export const HIP_UNITS = HIP_MUSCLES.flatMap((group) => group.units);
