/**
 * How long each muscle gets over the range of the joints it crosses.
 *
 * **Generated by `pnpm measure:muscle-ranges`. Do not edit.**
 *
 * Measured on this skeleton with the path solver, by sweeping each crossed coordinate through its
 * own range with the others at neutral and taking the extremes. What it is for is the tendon fit
 * in `compileMuscleSet`: a tendon slack length decides which part of its force-length curve a
 * muscle's fibers work over, and fitting that without knowing how far the muscle travels leaves
 * it against one end of the curve. The knee flexors were the case that showed it -- fitted to the
 * rest pose, which is the one where they are longest, their fibers ran down to a third of optimal
 * by deep flexion and made almost no force there, so a fully driven leg stopped bending at 84
 * degrees.
 *
 * Ratios of each muscle's own length at the rest pose, not metres, so they survive a change of
 * stature: every path here scales with it and the ratio does not.
 *
 * A muscle crossing two joints has its true extremes at a combination of angles, and sweeping one
 * coordinate at a time finds a narrower range than it really has. The error is in the safe
 * direction -- a narrower range fits the fibers into a smaller band than they need, which costs a
 * little of the curve rather than putting the muscle outside it.
 */

export interface MuscleLengthRange {
  readonly unit: string;
  /** Shortest the path gets, as a fraction of its length at the rest pose. */
  readonly shortest: number;
  /** Longest it gets, likewise. */
  readonly longest: number;
  /** The coordinates it crosses, as the moment module names them. */
  readonly crosses: string;
}

export const MUSCLE_LENGTH_RANGES: readonly MuscleLengthRange[] = [
  {
    unit: 'biceps_brachii_long_r',
    shortest: 0.87269,
    longest: 1.00562,
    crosses:
      'glenohumeral_r/plane_of_elevation, glenohumeral_r/elevation, glenohumeral_r/internal_rotation, elbow_r/flexion, radioulnar_r/pronation',
  },
  {
    unit: 'biceps_brachii_short_r',
    shortest: 0.851843,
    longest: 1.33116,
    crosses:
      'glenohumeral_r/plane_of_elevation, glenohumeral_r/elevation, glenohumeral_r/internal_rotation, elbow_r/flexion, radioulnar_r/pronation',
  },
  {
    unit: 'brachialis_r',
    shortest: 0.507496,
    longest: 1,
    crosses: 'elbow_r/flexion',
  },
  {
    unit: 'brachioradialis_r',
    shortest: 0.7066,
    longest: 1.02255,
    crosses: 'elbow_r/flexion, radioulnar_r/pronation',
  },
  {
    unit: 'triceps_brachii_long_r',
    shortest: 0.97139,
    longest: 1.14004,
    crosses:
      'glenohumeral_r/plane_of_elevation, glenohumeral_r/elevation, glenohumeral_r/internal_rotation, elbow_r/flexion',
  },
  {
    unit: 'triceps_brachii_lateral_r',
    shortest: 1,
    longest: 1.14169,
    crosses: 'elbow_r/flexion',
  },
  {
    unit: 'triceps_brachii_medial_r',
    shortest: 1,
    longest: 1.1498,
    crosses: 'elbow_r/flexion',
  },
  {
    unit: 'biceps_brachii_long_l',
    shortest: 0.87269,
    longest: 1.00558,
    crosses:
      'glenohumeral_l/plane_of_elevation, glenohumeral_l/elevation, glenohumeral_l/internal_rotation, elbow_l/flexion, radioulnar_l/pronation',
  },
  {
    unit: 'biceps_brachii_short_l',
    shortest: 0.851843,
    longest: 1.33116,
    crosses:
      'glenohumeral_l/plane_of_elevation, glenohumeral_l/elevation, glenohumeral_l/internal_rotation, elbow_l/flexion, radioulnar_l/pronation',
  },
  {
    unit: 'brachialis_l',
    shortest: 0.507494,
    longest: 1,
    crosses: 'elbow_l/flexion',
  },
  {
    unit: 'brachioradialis_l',
    shortest: 0.7066,
    longest: 1.02253,
    crosses: 'elbow_l/flexion, radioulnar_l/pronation',
  },
  {
    unit: 'triceps_brachii_long_l',
    shortest: 0.97139,
    longest: 1.14004,
    crosses:
      'glenohumeral_l/plane_of_elevation, glenohumeral_l/elevation, glenohumeral_l/internal_rotation, elbow_l/flexion',
  },
  {
    unit: 'triceps_brachii_lateral_l',
    shortest: 1,
    longest: 1.14169,
    crosses: 'elbow_l/flexion',
  },
  {
    unit: 'triceps_brachii_medial_l',
    shortest: 1,
    longest: 1.1498,
    crosses: 'elbow_l/flexion',
  },
  {
    unit: 'deltoid_anterior_r',
    shortest: 0.947988,
    longest: 1.34006,
    crosses:
      'glenohumeral_r/plane_of_elevation, glenohumeral_r/elevation, glenohumeral_r/internal_rotation, acromioclavicular_r/unrotate_clavicle_elevation, acromioclavicular_r/unrotate_clavicle_protraction, acromioclavicular_r/protraction, acromioclavicular_r/upward_rotation, acromioclavicular_r/tilt',
  },
  {
    unit: 'deltoid_middle_r',
    shortest: 0.851283,
    longest: 1,
    crosses:
      'glenohumeral_r/plane_of_elevation, glenohumeral_r/elevation, glenohumeral_r/internal_rotation',
  },
  {
    unit: 'deltoid_posterior_r',
    shortest: 0.975555,
    longest: 1.2658,
    crosses:
      'glenohumeral_r/plane_of_elevation, glenohumeral_r/elevation, glenohumeral_r/internal_rotation',
  },
  {
    unit: 'supraspinatus_r',
    shortest: 0.939643,
    longest: 1.18656,
    crosses:
      'glenohumeral_r/plane_of_elevation, glenohumeral_r/elevation, glenohumeral_r/internal_rotation',
  },
  {
    unit: 'infraspinatus_r',
    shortest: 0.737781,
    longest: 1.05453,
    crosses:
      'glenohumeral_r/plane_of_elevation, glenohumeral_r/elevation, glenohumeral_r/internal_rotation',
  },
  {
    unit: 'subscapularis_r',
    shortest: 0.84152,
    longest: 1.03381,
    crosses:
      'glenohumeral_r/plane_of_elevation, glenohumeral_r/elevation, glenohumeral_r/internal_rotation',
  },
  {
    unit: 'teres_minor_r',
    shortest: 0.787423,
    longest: 1.02759,
    crosses:
      'glenohumeral_r/plane_of_elevation, glenohumeral_r/elevation, glenohumeral_r/internal_rotation',
  },
  {
    unit: 'teres_major_r',
    shortest: 0.989921,
    longest: 1.4396,
    crosses:
      'glenohumeral_r/plane_of_elevation, glenohumeral_r/elevation, glenohumeral_r/internal_rotation',
  },
  {
    unit: 'coracobrachialis_r',
    shortest: 0.852351,
    longest: 1.0464,
    crosses:
      'glenohumeral_r/plane_of_elevation, glenohumeral_r/elevation, glenohumeral_r/internal_rotation',
  },
  {
    unit: 'deltoid_anterior_l',
    shortest: 0.948221,
    longest: 1.34047,
    crosses:
      'glenohumeral_l/plane_of_elevation, glenohumeral_l/elevation, glenohumeral_l/internal_rotation, acromioclavicular_l/unrotate_clavicle_elevation, acromioclavicular_l/unrotate_clavicle_protraction, acromioclavicular_l/protraction, acromioclavicular_l/upward_rotation, acromioclavicular_l/tilt',
  },
  {
    unit: 'deltoid_middle_l',
    shortest: 0.851283,
    longest: 1,
    crosses:
      'glenohumeral_l/plane_of_elevation, glenohumeral_l/elevation, glenohumeral_l/internal_rotation',
  },
  {
    unit: 'deltoid_posterior_l',
    shortest: 0.975555,
    longest: 1.2658,
    crosses:
      'glenohumeral_l/plane_of_elevation, glenohumeral_l/elevation, glenohumeral_l/internal_rotation',
  },
  {
    unit: 'supraspinatus_l',
    shortest: 0.939643,
    longest: 1.18656,
    crosses:
      'glenohumeral_l/plane_of_elevation, glenohumeral_l/elevation, glenohumeral_l/internal_rotation',
  },
  {
    unit: 'infraspinatus_l',
    shortest: 0.73778,
    longest: 1.05453,
    crosses:
      'glenohumeral_l/plane_of_elevation, glenohumeral_l/elevation, glenohumeral_l/internal_rotation',
  },
  {
    unit: 'subscapularis_l',
    shortest: 0.84152,
    longest: 1.03381,
    crosses:
      'glenohumeral_l/plane_of_elevation, glenohumeral_l/elevation, glenohumeral_l/internal_rotation',
  },
  {
    unit: 'teres_minor_l',
    shortest: 0.787423,
    longest: 1.02759,
    crosses:
      'glenohumeral_l/plane_of_elevation, glenohumeral_l/elevation, glenohumeral_l/internal_rotation',
  },
  {
    unit: 'teres_major_l',
    shortest: 0.989921,
    longest: 1.43959,
    crosses:
      'glenohumeral_l/plane_of_elevation, glenohumeral_l/elevation, glenohumeral_l/internal_rotation',
  },
  {
    unit: 'coracobrachialis_l',
    shortest: 0.852351,
    longest: 1.0464,
    crosses:
      'glenohumeral_l/plane_of_elevation, glenohumeral_l/elevation, glenohumeral_l/internal_rotation',
  },
  {
    unit: 'rectus_femoris_r',
    shortest: 0.831655,
    longest: 1.14352,
    crosses: 'hip_r/flexion, hip_r/adduction, hip_r/internal_rotation, knee_r/flexion',
  },
  {
    unit: 'vastus_lateralis_r',
    shortest: 0.999888,
    longest: 1.20419,
    crosses: 'knee_r/flexion',
  },
  {
    unit: 'vastus_medialis_r',
    shortest: 0.999861,
    longest: 1.25454,
    crosses: 'knee_r/flexion',
  },
  {
    unit: 'vastus_intermedius_r',
    shortest: 0.999872,
    longest: 1.24055,
    crosses: 'knee_r/flexion',
  },
  {
    unit: 'biceps_femoris_long_r',
    shortest: 0.817994,
    longest: 1.24123,
    crosses: 'hip_r/flexion, hip_r/adduction, hip_r/internal_rotation, knee_r/flexion',
  },
  {
    unit: 'biceps_femoris_short_r',
    shortest: 0.718052,
    longest: 1,
    crosses: 'knee_r/flexion',
  },
  {
    unit: 'semitendinosus_r',
    shortest: 0.786884,
    longest: 1.21841,
    crosses: 'hip_r/flexion, hip_r/adduction, hip_r/internal_rotation, knee_r/flexion',
  },
  {
    unit: 'semimembranosus_r',
    shortest: 0.845376,
    longest: 1.25472,
    crosses: 'hip_r/flexion, hip_r/adduction, hip_r/internal_rotation, knee_r/flexion',
  },
  {
    unit: 'gastrocnemius_lateral_r',
    shortest: 0.90454,
    longest: 1.03305,
    crosses: 'knee_r/flexion, talocrural_r/dorsiflexion, subtalar_r/inversion',
  },
  {
    unit: 'gastrocnemius_medial_r',
    shortest: 0.896699,
    longest: 1.0334,
    crosses: 'knee_r/flexion, talocrural_r/dorsiflexion, subtalar_r/inversion',
  },
  {
    unit: 'rectus_femoris_l',
    shortest: 0.831655,
    longest: 1.14352,
    crosses: 'hip_l/flexion, hip_l/adduction, hip_l/internal_rotation, knee_l/flexion',
  },
  {
    unit: 'vastus_lateralis_l',
    shortest: 0.999888,
    longest: 1.20419,
    crosses: 'knee_l/flexion',
  },
  {
    unit: 'vastus_medialis_l',
    shortest: 0.999861,
    longest: 1.25454,
    crosses: 'knee_l/flexion',
  },
  {
    unit: 'vastus_intermedius_l',
    shortest: 0.999872,
    longest: 1.24055,
    crosses: 'knee_l/flexion',
  },
  {
    unit: 'biceps_femoris_long_l',
    shortest: 0.817994,
    longest: 1.24123,
    crosses: 'hip_l/flexion, hip_l/adduction, hip_l/internal_rotation, knee_l/flexion',
  },
  {
    unit: 'biceps_femoris_short_l',
    shortest: 0.718052,
    longest: 1,
    crosses: 'knee_l/flexion',
  },
  {
    unit: 'semitendinosus_l',
    shortest: 0.786884,
    longest: 1.21841,
    crosses: 'hip_l/flexion, hip_l/adduction, hip_l/internal_rotation, knee_l/flexion',
  },
  {
    unit: 'semimembranosus_l',
    shortest: 0.845376,
    longest: 1.25472,
    crosses: 'hip_l/flexion, hip_l/adduction, hip_l/internal_rotation, knee_l/flexion',
  },
  {
    unit: 'gastrocnemius_lateral_l',
    shortest: 0.90454,
    longest: 1.03305,
    crosses: 'knee_l/flexion, talocrural_l/dorsiflexion, subtalar_l/inversion',
  },
  {
    unit: 'gastrocnemius_medial_l',
    shortest: 0.896699,
    longest: 1.0334,
    crosses: 'knee_l/flexion, talocrural_l/dorsiflexion, subtalar_l/inversion',
  },
  {
    unit: 'gluteus_maximus_superior_r',
    shortest: 0.863756,
    longest: 1.12482,
    crosses: 'hip_r/flexion, hip_r/adduction, hip_r/internal_rotation',
  },
  {
    unit: 'gluteus_maximus_middle_r',
    shortest: 0.899084,
    longest: 1.1196,
    crosses: 'hip_r/flexion, hip_r/adduction, hip_r/internal_rotation',
  },
  {
    unit: 'gluteus_maximus_inferior_r',
    shortest: 0.742568,
    longest: 2.37811,
    crosses: 'hip_r/flexion, hip_r/adduction, hip_r/internal_rotation',
  },
  {
    unit: 'gluteus_medius_anterior_r',
    shortest: 0.60669,
    longest: 1.16681,
    crosses: 'hip_r/flexion, hip_r/adduction, hip_r/internal_rotation',
  },
  {
    unit: 'gluteus_medius_middle_r',
    shortest: 0.677048,
    longest: 1.1398,
    crosses: 'hip_r/flexion, hip_r/adduction, hip_r/internal_rotation',
  },
  {
    unit: 'gluteus_medius_posterior_r',
    shortest: 0.760893,
    longest: 1.09854,
    crosses: 'hip_r/flexion, hip_r/adduction, hip_r/internal_rotation',
  },
  {
    unit: 'gluteus_minimus_anterior_r',
    shortest: 0.60669,
    longest: 1.16681,
    crosses: 'hip_r/flexion, hip_r/adduction, hip_r/internal_rotation',
  },
  {
    unit: 'gluteus_minimus_middle_r',
    shortest: 0.543425,
    longest: 1.19343,
    crosses: 'hip_r/flexion, hip_r/adduction, hip_r/internal_rotation',
  },
  {
    unit: 'gluteus_minimus_posterior_r',
    shortest: 0.532314,
    longest: 1.21594,
    crosses: 'hip_r/flexion, hip_r/adduction, hip_r/internal_rotation',
  },
  {
    unit: 'iliacus_r',
    shortest: 0.700707,
    longest: 1.03674,
    crosses: 'hip_r/flexion, hip_r/adduction, hip_r/internal_rotation',
  },
  {
    unit: 'psoas_major_r',
    shortest: 0.816957,
    longest: 1.04793,
    crosses:
      'l5_s1/flexion, l5_s1/lateral_bending_right, l5_s1/axial_rotation_left, l4_l5/flexion, l4_l5/lateral_bending_right, l4_l5/axial_rotation_left, l3_l4/flexion, l3_l4/lateral_bending_right, l3_l4/axial_rotation_left, hip_r/flexion, hip_r/adduction, hip_r/internal_rotation',
  },
  {
    unit: 'adductor_longus_r',
    shortest: 0.745056,
    longest: 1.1925,
    crosses: 'hip_r/flexion, hip_r/adduction, hip_r/internal_rotation',
  },
  {
    unit: 'adductor_brevis_r',
    shortest: 0.710321,
    longest: 1.37233,
    crosses: 'hip_r/flexion, hip_r/adduction, hip_r/internal_rotation',
  },
  {
    unit: 'adductor_magnus_proximal_r',
    shortest: 0.730807,
    longest: 1.3357,
    crosses: 'hip_r/flexion, hip_r/adduction, hip_r/internal_rotation',
  },
  {
    unit: 'adductor_magnus_middle_r',
    shortest: 0.886604,
    longest: 1.46553,
    crosses: 'hip_r/flexion, hip_r/adduction, hip_r/internal_rotation',
  },
  {
    unit: 'adductor_magnus_distal_r',
    shortest: 0.943507,
    longest: 1.30637,
    crosses: 'hip_r/flexion, hip_r/adduction, hip_r/internal_rotation',
  },
  {
    unit: 'adductor_magnus_ischiocondylar_r',
    shortest: 0.945497,
    longest: 1.2963,
    crosses: 'hip_r/flexion, hip_r/adduction, hip_r/internal_rotation',
  },
  {
    unit: 'piriformis_r',
    shortest: 0.882739,
    longest: 1.0327,
    crosses: 'hip_r/flexion, hip_r/adduction, hip_r/internal_rotation',
  },
  {
    unit: 'tensor_fasciae_latae_r',
    shortest: 0.751286,
    longest: 1.02804,
    crosses: 'hip_r/flexion, hip_r/adduction, hip_r/internal_rotation, knee_r/flexion',
  },
  {
    unit: 'gracilis_r',
    shortest: 0.836134,
    longest: 1.07675,
    crosses: 'hip_r/flexion, hip_r/adduction, hip_r/internal_rotation, knee_r/flexion',
  },
  {
    unit: 'sartorius_r',
    shortest: 0.729474,
    longest: 1.01776,
    crosses: 'hip_r/flexion, hip_r/adduction, hip_r/internal_rotation, knee_r/flexion',
  },
  {
    unit: 'gluteus_maximus_superior_l',
    shortest: 0.863755,
    longest: 1.12482,
    crosses: 'hip_l/flexion, hip_l/adduction, hip_l/internal_rotation',
  },
  {
    unit: 'gluteus_maximus_middle_l',
    shortest: 0.884459,
    longest: 1.13434,
    crosses: 'hip_l/flexion, hip_l/adduction, hip_l/internal_rotation',
  },
  {
    unit: 'gluteus_maximus_inferior_l',
    shortest: 0.743402,
    longest: 2.37811,
    crosses: 'hip_l/flexion, hip_l/adduction, hip_l/internal_rotation',
  },
  {
    unit: 'gluteus_medius_anterior_l',
    shortest: 0.60669,
    longest: 1.1703,
    crosses: 'hip_l/flexion, hip_l/adduction, hip_l/internal_rotation',
  },
  {
    unit: 'gluteus_medius_middle_l',
    shortest: 0.677048,
    longest: 1.14431,
    crosses: 'hip_l/flexion, hip_l/adduction, hip_l/internal_rotation',
  },
  {
    unit: 'gluteus_medius_posterior_l',
    shortest: 0.760893,
    longest: 1.09854,
    crosses: 'hip_l/flexion, hip_l/adduction, hip_l/internal_rotation',
  },
  {
    unit: 'gluteus_minimus_anterior_l',
    shortest: 0.60669,
    longest: 1.1703,
    crosses: 'hip_l/flexion, hip_l/adduction, hip_l/internal_rotation',
  },
  {
    unit: 'gluteus_minimus_middle_l',
    shortest: 0.543425,
    longest: 1.19167,
    crosses: 'hip_l/flexion, hip_l/adduction, hip_l/internal_rotation',
  },
  {
    unit: 'gluteus_minimus_posterior_l',
    shortest: 0.532314,
    longest: 1.20199,
    crosses: 'hip_l/flexion, hip_l/adduction, hip_l/internal_rotation',
  },
  {
    unit: 'iliacus_l',
    shortest: 0.700707,
    longest: 1.03674,
    crosses: 'hip_l/flexion, hip_l/adduction, hip_l/internal_rotation',
  },
  {
    unit: 'psoas_major_l',
    shortest: 0.808536,
    longest: 1.04279,
    crosses:
      'l5_s1/flexion, l5_s1/lateral_bending_right, l5_s1/axial_rotation_left, l4_l5/flexion, l4_l5/lateral_bending_right, l4_l5/axial_rotation_left, l3_l4/flexion, l3_l4/lateral_bending_right, l3_l4/axial_rotation_left, hip_l/flexion, hip_l/adduction, hip_l/internal_rotation',
  },
  {
    unit: 'adductor_longus_l',
    shortest: 0.745056,
    longest: 1.1925,
    crosses: 'hip_l/flexion, hip_l/adduction, hip_l/internal_rotation',
  },
  {
    unit: 'adductor_brevis_l',
    shortest: 0.727661,
    longest: 1.37233,
    crosses: 'hip_l/flexion, hip_l/adduction, hip_l/internal_rotation',
  },
  {
    unit: 'adductor_magnus_proximal_l',
    shortest: 0.744368,
    longest: 1.3357,
    crosses: 'hip_l/flexion, hip_l/adduction, hip_l/internal_rotation',
  },
  {
    unit: 'adductor_magnus_middle_l',
    shortest: 0.885147,
    longest: 1.46553,
    crosses: 'hip_l/flexion, hip_l/adduction, hip_l/internal_rotation',
  },
  {
    unit: 'adductor_magnus_distal_l',
    shortest: 0.943507,
    longest: 1.30637,
    crosses: 'hip_l/flexion, hip_l/adduction, hip_l/internal_rotation',
  },
  {
    unit: 'adductor_magnus_ischiocondylar_l',
    shortest: 0.945497,
    longest: 1.2963,
    crosses: 'hip_l/flexion, hip_l/adduction, hip_l/internal_rotation',
  },
  {
    unit: 'piriformis_l',
    shortest: 0.875695,
    longest: 1.04045,
    crosses: 'hip_l/flexion, hip_l/adduction, hip_l/internal_rotation',
  },
  {
    unit: 'tensor_fasciae_latae_l',
    shortest: 0.751286,
    longest: 1.02804,
    crosses: 'hip_l/flexion, hip_l/adduction, hip_l/internal_rotation, knee_l/flexion',
  },
  {
    unit: 'gracilis_l',
    shortest: 0.836134,
    longest: 1.07675,
    crosses: 'hip_l/flexion, hip_l/adduction, hip_l/internal_rotation, knee_l/flexion',
  },
  {
    unit: 'sartorius_l',
    shortest: 0.729474,
    longest: 1.01776,
    crosses: 'hip_l/flexion, hip_l/adduction, hip_l/internal_rotation, knee_l/flexion',
  },
  {
    unit: 'soleus_r',
    shortest: 0.905844,
    longest: 1.0439,
    crosses: 'talocrural_r/dorsiflexion, subtalar_r/inversion',
  },
  {
    unit: 'tibialis_anterior_r',
    shortest: 0.875123,
    longest: 1.1043,
    crosses: 'talocrural_r/dorsiflexion',
  },
  {
    unit: 'tibialis_posterior_r',
    shortest: 0.883544,
    longest: 1.09418,
    crosses: 'talocrural_r/dorsiflexion',
  },
  {
    unit: 'fibularis_longus_r',
    shortest: 0.970629,
    longest: 1.04041,
    crosses: 'talocrural_r/dorsiflexion',
  },
  {
    unit: 'fibularis_brevis_r',
    shortest: 0.967506,
    longest: 1.04821,
    crosses: 'talocrural_r/dorsiflexion',
  },
  {
    unit: 'extensor_digitorum_longus_r',
    shortest: 0.823821,
    longest: 1.15193,
    crosses: 'talocrural_r/dorsiflexion',
  },
  {
    unit: 'extensor_hallucis_longus_r',
    shortest: 0.813575,
    longest: 1.14165,
    crosses: 'talocrural_r/dorsiflexion',
  },
  {
    unit: 'flexor_digitorum_longus_r',
    shortest: 0.909557,
    longest: 1.06355,
    crosses: 'talocrural_r/dorsiflexion',
  },
  {
    unit: 'flexor_hallucis_longus_r',
    shortest: 0.881866,
    longest: 1.08443,
    crosses: 'talocrural_r/dorsiflexion',
  },
  {
    unit: 'soleus_l',
    shortest: 0.905844,
    longest: 1.0439,
    crosses: 'talocrural_l/dorsiflexion, subtalar_l/inversion',
  },
  {
    unit: 'tibialis_anterior_l',
    shortest: 0.875123,
    longest: 1.1043,
    crosses: 'talocrural_l/dorsiflexion',
  },
  {
    unit: 'tibialis_posterior_l',
    shortest: 0.883544,
    longest: 1.09418,
    crosses: 'talocrural_l/dorsiflexion',
  },
  {
    unit: 'fibularis_longus_l',
    shortest: 0.970629,
    longest: 1.04041,
    crosses: 'talocrural_l/dorsiflexion',
  },
  {
    unit: 'fibularis_brevis_l',
    shortest: 0.967506,
    longest: 1.04821,
    crosses: 'talocrural_l/dorsiflexion',
  },
  {
    unit: 'extensor_digitorum_longus_l',
    shortest: 0.823821,
    longest: 1.15193,
    crosses: 'talocrural_l/dorsiflexion',
  },
  {
    unit: 'extensor_hallucis_longus_l',
    shortest: 0.813575,
    longest: 1.14165,
    crosses: 'talocrural_l/dorsiflexion',
  },
  {
    unit: 'flexor_digitorum_longus_l',
    shortest: 0.909557,
    longest: 1.06355,
    crosses: 'talocrural_l/dorsiflexion',
  },
  {
    unit: 'flexor_hallucis_longus_l',
    shortest: 0.881866,
    longest: 1.08443,
    crosses: 'talocrural_l/dorsiflexion',
  },
  {
    unit: 'latissimus_dorsi_thoracic_r',
    shortest: 0.739937,
    longest: 1.42993,
    crosses:
      'sternoclavicular_r/protraction, sternoclavicular_r/elevation, glenohumeral_r/plane_of_elevation, glenohumeral_r/elevation, glenohumeral_r/internal_rotation, t7_t8/flexion, t7_t8/lateral_bending_right, t7_t8/axial_rotation_left, t6_t7/flexion, t6_t7/lateral_bending_right, t6_t7/axial_rotation_left, t5_t6/flexion, t5_t6/lateral_bending_right, t5_t6/axial_rotation_left, t4_t5/flexion, t4_t5/lateral_bending_right, t4_t5/axial_rotation_left, t3_t4/flexion, t3_t4/lateral_bending_right, t3_t4/axial_rotation_left, t2_t3/flexion, t2_t3/lateral_bending_right, t2_t3/axial_rotation_left, t1_t2/flexion, t1_t2/lateral_bending_right, t1_t2/axial_rotation_left, costovertebral_1_r/elevation, acromioclavicular_r/unrotate_clavicle_elevation, acromioclavicular_r/unrotate_clavicle_protraction, acromioclavicular_r/protraction, acromioclavicular_r/upward_rotation, acromioclavicular_r/tilt',
  },
  {
    unit: 'latissimus_dorsi_lumbar_r',
    shortest: 0.92099,
    longest: 1.08691,
    crosses:
      'l5_s1/flexion, l5_s1/lateral_bending_right, l5_s1/axial_rotation_left, l4_l5/flexion, l4_l5/lateral_bending_right, l4_l5/axial_rotation_left, l3_l4/flexion, l3_l4/lateral_bending_right, l3_l4/axial_rotation_left, l2_l3/flexion, l2_l3/lateral_bending_right, l2_l3/axial_rotation_left, l1_l2/flexion, l1_l2/lateral_bending_right, l1_l2/axial_rotation_left, t12_l1/flexion, t12_l1/lateral_bending_right, t12_l1/axial_rotation_left, sternoclavicular_r/protraction, sternoclavicular_r/elevation, glenohumeral_r/plane_of_elevation, glenohumeral_r/elevation, glenohumeral_r/internal_rotation, t11_t12/flexion, t11_t12/lateral_bending_right, t11_t12/axial_rotation_left, t10_t11/flexion, t10_t11/lateral_bending_right, t10_t11/axial_rotation_left, t9_t10/flexion, t9_t10/lateral_bending_right, t9_t10/axial_rotation_left, t8_t9/flexion, t8_t9/lateral_bending_right, t8_t9/axial_rotation_left, t7_t8/flexion, t7_t8/lateral_bending_right, t7_t8/axial_rotation_left, t6_t7/flexion, t6_t7/lateral_bending_right, t6_t7/axial_rotation_left, t5_t6/flexion, t5_t6/lateral_bending_right, t5_t6/axial_rotation_left, t4_t5/flexion, t4_t5/lateral_bending_right, t4_t5/axial_rotation_left, t3_t4/flexion, t3_t4/lateral_bending_right, t3_t4/axial_rotation_left, t2_t3/flexion, t2_t3/lateral_bending_right, t2_t3/axial_rotation_left, t1_t2/flexion, t1_t2/lateral_bending_right, t1_t2/axial_rotation_left, costovertebral_1_r/elevation, acromioclavicular_r/unrotate_clavicle_elevation, acromioclavicular_r/unrotate_clavicle_protraction, acromioclavicular_r/protraction, acromioclavicular_r/upward_rotation, acromioclavicular_r/tilt',
  },
  {
    unit: 'latissimus_dorsi_iliac_r',
    shortest: 0.893219,
    longest: 1.38194,
    crosses:
      'l5_s1/flexion, l5_s1/lateral_bending_right, l5_s1/axial_rotation_left, l4_l5/flexion, l4_l5/lateral_bending_right, l4_l5/axial_rotation_left, l3_l4/flexion, l3_l4/lateral_bending_right, l3_l4/axial_rotation_left, l2_l3/flexion, l2_l3/lateral_bending_right, l2_l3/axial_rotation_left, l1_l2/flexion, l1_l2/lateral_bending_right, l1_l2/axial_rotation_left, t12_l1/flexion, t12_l1/lateral_bending_right, t12_l1/axial_rotation_left, sternoclavicular_r/protraction, sternoclavicular_r/elevation, glenohumeral_r/plane_of_elevation, glenohumeral_r/elevation, glenohumeral_r/internal_rotation, t11_t12/flexion, t11_t12/lateral_bending_right, t11_t12/axial_rotation_left, t10_t11/flexion, t10_t11/lateral_bending_right, t10_t11/axial_rotation_left, t9_t10/flexion, t9_t10/lateral_bending_right, t9_t10/axial_rotation_left, t8_t9/flexion, t8_t9/lateral_bending_right, t8_t9/axial_rotation_left, t7_t8/flexion, t7_t8/lateral_bending_right, t7_t8/axial_rotation_left, t6_t7/flexion, t6_t7/lateral_bending_right, t6_t7/axial_rotation_left, t5_t6/flexion, t5_t6/lateral_bending_right, t5_t6/axial_rotation_left, t4_t5/flexion, t4_t5/lateral_bending_right, t4_t5/axial_rotation_left, t3_t4/flexion, t3_t4/lateral_bending_right, t3_t4/axial_rotation_left, t2_t3/flexion, t2_t3/lateral_bending_right, t2_t3/axial_rotation_left, t1_t2/flexion, t1_t2/lateral_bending_right, t1_t2/axial_rotation_left, costovertebral_1_r/elevation, acromioclavicular_r/unrotate_clavicle_elevation, acromioclavicular_r/unrotate_clavicle_protraction, acromioclavicular_r/protraction, acromioclavicular_r/upward_rotation, acromioclavicular_r/tilt',
  },
  {
    unit: 'pectoralis_major_clavicular_r',
    shortest: 0.750894,
    longest: 1.05084,
    crosses:
      'glenohumeral_r/plane_of_elevation, glenohumeral_r/elevation, glenohumeral_r/internal_rotation, acromioclavicular_r/unrotate_clavicle_elevation, acromioclavicular_r/unrotate_clavicle_protraction, acromioclavicular_r/protraction, acromioclavicular_r/upward_rotation, acromioclavicular_r/tilt',
  },
  {
    unit: 'pectoralis_major_sternal_r',
    shortest: 0.89803,
    longest: 1.12297,
    crosses:
      'sternoclavicular_r/protraction, sternoclavicular_r/elevation, glenohumeral_r/plane_of_elevation, glenohumeral_r/elevation, glenohumeral_r/internal_rotation, acromioclavicular_r/unrotate_clavicle_elevation, acromioclavicular_r/unrotate_clavicle_protraction, acromioclavicular_r/protraction, acromioclavicular_r/upward_rotation, acromioclavicular_r/tilt',
  },
  {
    unit: 'pectoralis_major_abdominal_r',
    shortest: 0.876324,
    longest: 2.07888,
    crosses:
      'sternoclavicular_r/protraction, sternoclavicular_r/elevation, glenohumeral_r/plane_of_elevation, glenohumeral_r/elevation, glenohumeral_r/internal_rotation, t5_t6/flexion, t5_t6/lateral_bending_right, t5_t6/axial_rotation_left, t4_t5/flexion, t4_t5/lateral_bending_right, t4_t5/axial_rotation_left, t3_t4/flexion, t3_t4/lateral_bending_right, t3_t4/axial_rotation_left, t2_t3/flexion, t2_t3/lateral_bending_right, t2_t3/axial_rotation_left, t1_t2/flexion, t1_t2/lateral_bending_right, t1_t2/axial_rotation_left, costovertebral_1_r/elevation, costovertebral_6_r/elevation, acromioclavicular_r/unrotate_clavicle_elevation, acromioclavicular_r/unrotate_clavicle_protraction, acromioclavicular_r/protraction, acromioclavicular_r/upward_rotation, acromioclavicular_r/tilt',
  },
  {
    unit: 'latissimus_dorsi_thoracic_l',
    shortest: 0.760609,
    longest: 1.43257,
    crosses:
      'sternoclavicular_l/protraction, sternoclavicular_l/elevation, glenohumeral_l/plane_of_elevation, glenohumeral_l/elevation, glenohumeral_l/internal_rotation, t7_t8/flexion, t7_t8/lateral_bending_right, t7_t8/axial_rotation_left, t6_t7/flexion, t6_t7/lateral_bending_right, t6_t7/axial_rotation_left, t5_t6/flexion, t5_t6/lateral_bending_right, t5_t6/axial_rotation_left, t4_t5/flexion, t4_t5/lateral_bending_right, t4_t5/axial_rotation_left, t3_t4/flexion, t3_t4/lateral_bending_right, t3_t4/axial_rotation_left, t2_t3/flexion, t2_t3/lateral_bending_right, t2_t3/axial_rotation_left, t1_t2/flexion, t1_t2/lateral_bending_right, t1_t2/axial_rotation_left, costovertebral_1_r/elevation, acromioclavicular_l/unrotate_clavicle_elevation, acromioclavicular_l/unrotate_clavicle_protraction, acromioclavicular_l/protraction, acromioclavicular_l/upward_rotation, acromioclavicular_l/tilt',
  },
  {
    unit: 'latissimus_dorsi_lumbar_l',
    shortest: 0.927727,
    longest: 1.09224,
    crosses:
      'l5_s1/flexion, l5_s1/lateral_bending_right, l5_s1/axial_rotation_left, l4_l5/flexion, l4_l5/lateral_bending_right, l4_l5/axial_rotation_left, l3_l4/flexion, l3_l4/lateral_bending_right, l3_l4/axial_rotation_left, l2_l3/flexion, l2_l3/lateral_bending_right, l2_l3/axial_rotation_left, l1_l2/flexion, l1_l2/lateral_bending_right, l1_l2/axial_rotation_left, t12_l1/flexion, t12_l1/lateral_bending_right, t12_l1/axial_rotation_left, sternoclavicular_l/protraction, sternoclavicular_l/elevation, glenohumeral_l/plane_of_elevation, glenohumeral_l/elevation, glenohumeral_l/internal_rotation, t11_t12/flexion, t11_t12/lateral_bending_right, t11_t12/axial_rotation_left, t10_t11/flexion, t10_t11/lateral_bending_right, t10_t11/axial_rotation_left, t9_t10/flexion, t9_t10/lateral_bending_right, t9_t10/axial_rotation_left, t8_t9/flexion, t8_t9/lateral_bending_right, t8_t9/axial_rotation_left, t7_t8/flexion, t7_t8/lateral_bending_right, t7_t8/axial_rotation_left, t6_t7/flexion, t6_t7/lateral_bending_right, t6_t7/axial_rotation_left, t5_t6/flexion, t5_t6/lateral_bending_right, t5_t6/axial_rotation_left, t4_t5/flexion, t4_t5/lateral_bending_right, t4_t5/axial_rotation_left, t3_t4/flexion, t3_t4/lateral_bending_right, t3_t4/axial_rotation_left, t2_t3/flexion, t2_t3/lateral_bending_right, t2_t3/axial_rotation_left, t1_t2/flexion, t1_t2/lateral_bending_right, t1_t2/axial_rotation_left, costovertebral_1_r/elevation, acromioclavicular_l/unrotate_clavicle_elevation, acromioclavicular_l/unrotate_clavicle_protraction, acromioclavicular_l/protraction, acromioclavicular_l/upward_rotation, acromioclavicular_l/tilt',
  },
  {
    unit: 'latissimus_dorsi_iliac_l',
    shortest: 0.89403,
    longest: 1.3956,
    crosses:
      'l5_s1/flexion, l5_s1/lateral_bending_right, l5_s1/axial_rotation_left, l4_l5/flexion, l4_l5/lateral_bending_right, l4_l5/axial_rotation_left, l3_l4/flexion, l3_l4/lateral_bending_right, l3_l4/axial_rotation_left, l2_l3/flexion, l2_l3/lateral_bending_right, l2_l3/axial_rotation_left, l1_l2/flexion, l1_l2/lateral_bending_right, l1_l2/axial_rotation_left, t12_l1/flexion, t12_l1/lateral_bending_right, t12_l1/axial_rotation_left, sternoclavicular_l/protraction, sternoclavicular_l/elevation, glenohumeral_l/plane_of_elevation, glenohumeral_l/elevation, glenohumeral_l/internal_rotation, t11_t12/flexion, t11_t12/lateral_bending_right, t11_t12/axial_rotation_left, t10_t11/flexion, t10_t11/lateral_bending_right, t10_t11/axial_rotation_left, t9_t10/flexion, t9_t10/lateral_bending_right, t9_t10/axial_rotation_left, t8_t9/flexion, t8_t9/lateral_bending_right, t8_t9/axial_rotation_left, t7_t8/flexion, t7_t8/lateral_bending_right, t7_t8/axial_rotation_left, t6_t7/flexion, t6_t7/lateral_bending_right, t6_t7/axial_rotation_left, t5_t6/flexion, t5_t6/lateral_bending_right, t5_t6/axial_rotation_left, t4_t5/flexion, t4_t5/lateral_bending_right, t4_t5/axial_rotation_left, t3_t4/flexion, t3_t4/lateral_bending_right, t3_t4/axial_rotation_left, t2_t3/flexion, t2_t3/lateral_bending_right, t2_t3/axial_rotation_left, t1_t2/flexion, t1_t2/lateral_bending_right, t1_t2/axial_rotation_left, costovertebral_1_r/elevation, acromioclavicular_l/unrotate_clavicle_elevation, acromioclavicular_l/unrotate_clavicle_protraction, acromioclavicular_l/protraction, acromioclavicular_l/upward_rotation, acromioclavicular_l/tilt',
  },
  {
    unit: 'pectoralis_major_clavicular_l',
    shortest: 0.745621,
    longest: 1.05084,
    crosses:
      'glenohumeral_l/plane_of_elevation, glenohumeral_l/elevation, glenohumeral_l/internal_rotation, acromioclavicular_l/unrotate_clavicle_elevation, acromioclavicular_l/unrotate_clavicle_protraction, acromioclavicular_l/protraction, acromioclavicular_l/upward_rotation, acromioclavicular_l/tilt',
  },
  {
    unit: 'pectoralis_major_sternal_l',
    shortest: 0.890135,
    longest: 1.11768,
    crosses:
      'sternoclavicular_l/protraction, sternoclavicular_l/elevation, glenohumeral_l/plane_of_elevation, glenohumeral_l/elevation, glenohumeral_l/internal_rotation, acromioclavicular_l/unrotate_clavicle_elevation, acromioclavicular_l/unrotate_clavicle_protraction, acromioclavicular_l/protraction, acromioclavicular_l/upward_rotation, acromioclavicular_l/tilt',
  },
  {
    unit: 'pectoralis_major_abdominal_l',
    shortest: 0.892298,
    longest: 2.12761,
    crosses:
      'sternoclavicular_l/protraction, sternoclavicular_l/elevation, glenohumeral_l/plane_of_elevation, glenohumeral_l/elevation, glenohumeral_l/internal_rotation, t5_t6/flexion, t5_t6/lateral_bending_right, t5_t6/axial_rotation_left, t4_t5/flexion, t4_t5/lateral_bending_right, t4_t5/axial_rotation_left, t3_t4/flexion, t3_t4/lateral_bending_right, t3_t4/axial_rotation_left, t2_t3/flexion, t2_t3/lateral_bending_right, t2_t3/axial_rotation_left, t1_t2/flexion, t1_t2/lateral_bending_right, t1_t2/axial_rotation_left, costovertebral_1_r/elevation, costovertebral_6_l/elevation, acromioclavicular_l/unrotate_clavicle_elevation, acromioclavicular_l/unrotate_clavicle_protraction, acromioclavicular_l/protraction, acromioclavicular_l/upward_rotation, acromioclavicular_l/tilt',
  },
  {
    unit: 'pronator_teres_r',
    shortest: 0.983461,
    longest: 1.0614,
    crosses: 'elbow_r/flexion, radioulnar_r/pronation',
  },
  {
    unit: 'pronator_quadratus_r',
    shortest: 0.990685,
    longest: 1.01244,
    crosses: 'radioulnar_r/pronation',
  },
  {
    unit: 'supinator_r',
    shortest: 0.998488,
    longest: 1.06364,
    crosses: 'radioulnar_r/pronation',
  },
  {
    unit: 'anconeus_r',
    shortest: 0.978198,
    longest: 1,
    crosses: 'elbow_r/flexion',
  },
  {
    unit: 'flexor_carpi_radialis_r',
    shortest: 0.963553,
    longest: 1.00832,
    crosses: 'elbow_r/flexion, radioulnar_r/pronation, wrist_r/flexion, wrist_r/ulnar_deviation',
  },
  {
    unit: 'flexor_carpi_ulnaris_r',
    shortest: 0.96284,
    longest: 1.00811,
    crosses: 'elbow_r/flexion, radioulnar_r/pronation, wrist_r/flexion, wrist_r/ulnar_deviation',
  },
  {
    unit: 'extensor_carpi_radialis_longus_r',
    shortest: 0.943626,
    longest: 1.03849,
    crosses: 'elbow_r/flexion, radioulnar_r/pronation, wrist_r/flexion, wrist_r/ulnar_deviation',
  },
  {
    unit: 'extensor_carpi_radialis_brevis_r',
    shortest: 0.955433,
    longest: 1.05051,
    crosses: 'elbow_r/flexion, radioulnar_r/pronation, wrist_r/flexion, wrist_r/ulnar_deviation',
  },
  {
    unit: 'pronator_teres_l',
    shortest: 0.983461,
    longest: 1.06125,
    crosses: 'elbow_l/flexion, radioulnar_l/pronation',
  },
  {
    unit: 'pronator_quadratus_l',
    shortest: 0.99065,
    longest: 1.01238,
    crosses: 'radioulnar_l/pronation',
  },
  {
    unit: 'supinator_l',
    shortest: 0.998446,
    longest: 1.06338,
    crosses: 'radioulnar_l/pronation',
  },
  {
    unit: 'anconeus_l',
    shortest: 0.978198,
    longest: 1,
    crosses: 'elbow_l/flexion',
  },
  {
    unit: 'flexor_carpi_radialis_l',
    shortest: 0.963528,
    longest: 1.00832,
    crosses: 'elbow_l/flexion, radioulnar_l/pronation, wrist_l/flexion, wrist_l/ulnar_deviation',
  },
  {
    unit: 'flexor_carpi_ulnaris_l',
    shortest: 0.962814,
    longest: 1.00811,
    crosses: 'elbow_l/flexion, radioulnar_l/pronation, wrist_l/flexion, wrist_l/ulnar_deviation',
  },
  {
    unit: 'extensor_carpi_radialis_longus_l',
    shortest: 0.943626,
    longest: 1.03845,
    crosses: 'elbow_l/flexion, radioulnar_l/pronation, wrist_l/flexion, wrist_l/ulnar_deviation',
  },
  {
    unit: 'extensor_carpi_radialis_brevis_l',
    shortest: 0.955433,
    longest: 1.05045,
    crosses: 'elbow_l/flexion, radioulnar_l/pronation, wrist_l/flexion, wrist_l/ulnar_deviation',
  },
  {
    unit: 'erector_spinae_r',
    shortest: 0.963215,
    longest: 1.06756,
    crosses:
      'l5_s1/flexion, l5_s1/lateral_bending_right, l5_s1/axial_rotation_left, l4_l5/flexion, l4_l5/lateral_bending_right, l4_l5/axial_rotation_left, l3_l4/flexion, l3_l4/lateral_bending_right, l3_l4/axial_rotation_left, l2_l3/flexion, l2_l3/lateral_bending_right, l2_l3/axial_rotation_left, l1_l2/flexion, l1_l2/lateral_bending_right, l1_l2/axial_rotation_left, t12_l1/flexion, t12_l1/lateral_bending_right, t12_l1/axial_rotation_left, t11_t12/flexion, t11_t12/lateral_bending_right, t11_t12/axial_rotation_left, t10_t11/flexion, t10_t11/lateral_bending_right, t10_t11/axial_rotation_left, t9_t10/flexion, t9_t10/lateral_bending_right, t9_t10/axial_rotation_left, t8_t9/flexion, t8_t9/lateral_bending_right, t8_t9/axial_rotation_left, t7_t8/flexion, t7_t8/lateral_bending_right, t7_t8/axial_rotation_left, t6_t7/flexion, t6_t7/lateral_bending_right, t6_t7/axial_rotation_left, costovertebral_6_r/elevation',
  },
  {
    unit: 'rectus_abdominis_r',
    shortest: 0.676015,
    longest: 1.09895,
    crosses:
      'l5_s1/flexion, l5_s1/lateral_bending_right, l5_s1/axial_rotation_left, l4_l5/flexion, l4_l5/lateral_bending_right, l4_l5/axial_rotation_left, l3_l4/flexion, l3_l4/lateral_bending_right, l3_l4/axial_rotation_left, l2_l3/flexion, l2_l3/lateral_bending_right, l2_l3/axial_rotation_left, l1_l2/flexion, l1_l2/lateral_bending_right, l1_l2/axial_rotation_left, t12_l1/flexion, t12_l1/lateral_bending_right, t12_l1/axial_rotation_left, t11_t12/flexion, t11_t12/lateral_bending_right, t11_t12/axial_rotation_left, t10_t11/flexion, t10_t11/lateral_bending_right, t10_t11/axial_rotation_left, t9_t10/flexion, t9_t10/lateral_bending_right, t9_t10/axial_rotation_left, t8_t9/flexion, t8_t9/lateral_bending_right, t8_t9/axial_rotation_left, t7_t8/flexion, t7_t8/lateral_bending_right, t7_t8/axial_rotation_left, t6_t7/flexion, t6_t7/lateral_bending_right, t6_t7/axial_rotation_left, t5_t6/flexion, t5_t6/lateral_bending_right, t5_t6/axial_rotation_left, t4_t5/flexion, t4_t5/lateral_bending_right, t4_t5/axial_rotation_left, t3_t4/flexion, t3_t4/lateral_bending_right, t3_t4/axial_rotation_left, t2_t3/flexion, t2_t3/lateral_bending_right, t2_t3/axial_rotation_left, t1_t2/flexion, t1_t2/lateral_bending_right, t1_t2/axial_rotation_left, costovertebral_1_r/elevation',
  },
  {
    unit: 'external_oblique_r',
    shortest: 0.846218,
    longest: 1.05885,
    crosses:
      'l5_s1/flexion, l5_s1/lateral_bending_right, l5_s1/axial_rotation_left, l4_l5/flexion, l4_l5/lateral_bending_right, l4_l5/axial_rotation_left, l3_l4/flexion, l3_l4/lateral_bending_right, l3_l4/axial_rotation_left, l2_l3/flexion, l2_l3/lateral_bending_right, l2_l3/axial_rotation_left, l1_l2/flexion, l1_l2/lateral_bending_right, l1_l2/axial_rotation_left, t12_l1/flexion, t12_l1/lateral_bending_right, t12_l1/axial_rotation_left, t11_t12/flexion, t11_t12/lateral_bending_right, t11_t12/axial_rotation_left, t10_t11/flexion, t10_t11/lateral_bending_right, t10_t11/axial_rotation_left, t9_t10/flexion, t9_t10/lateral_bending_right, t9_t10/axial_rotation_left, t8_t9/flexion, t8_t9/lateral_bending_right, t8_t9/axial_rotation_left, t7_t8/flexion, t7_t8/lateral_bending_right, t7_t8/axial_rotation_left, t6_t7/flexion, t6_t7/lateral_bending_right, t6_t7/axial_rotation_left, costovertebral_6_r/elevation',
  },
  {
    unit: 'internal_oblique_r',
    shortest: 0.788455,
    longest: 1.15343,
    crosses:
      'l5_s1/flexion, l5_s1/lateral_bending_right, l5_s1/axial_rotation_left, l4_l5/flexion, l4_l5/lateral_bending_right, l4_l5/axial_rotation_left, l3_l4/flexion, l3_l4/lateral_bending_right, l3_l4/axial_rotation_left, l2_l3/flexion, l2_l3/lateral_bending_right, l2_l3/axial_rotation_left, l1_l2/flexion, l1_l2/lateral_bending_right, l1_l2/axial_rotation_left, t12_l1/flexion, t12_l1/lateral_bending_right, t12_l1/axial_rotation_left, t11_t12/flexion, t11_t12/lateral_bending_right, t11_t12/axial_rotation_left, t10_t11/flexion, t10_t11/lateral_bending_right, t10_t11/axial_rotation_left, t9_t10/flexion, t9_t10/lateral_bending_right, t9_t10/axial_rotation_left, t8_t9/flexion, t8_t9/lateral_bending_right, t8_t9/axial_rotation_left, t7_t8/flexion, t7_t8/lateral_bending_right, t7_t8/axial_rotation_left, t6_t7/flexion, t6_t7/lateral_bending_right, t6_t7/axial_rotation_left, costovertebral_6_r/elevation',
  },
  {
    unit: 'erector_spinae_l',
    shortest: 0.963215,
    longest: 1.06756,
    crosses:
      'l5_s1/flexion, l5_s1/lateral_bending_right, l5_s1/axial_rotation_left, l4_l5/flexion, l4_l5/lateral_bending_right, l4_l5/axial_rotation_left, l3_l4/flexion, l3_l4/lateral_bending_right, l3_l4/axial_rotation_left, l2_l3/flexion, l2_l3/lateral_bending_right, l2_l3/axial_rotation_left, l1_l2/flexion, l1_l2/lateral_bending_right, l1_l2/axial_rotation_left, t12_l1/flexion, t12_l1/lateral_bending_right, t12_l1/axial_rotation_left, t11_t12/flexion, t11_t12/lateral_bending_right, t11_t12/axial_rotation_left, t10_t11/flexion, t10_t11/lateral_bending_right, t10_t11/axial_rotation_left, t9_t10/flexion, t9_t10/lateral_bending_right, t9_t10/axial_rotation_left, t8_t9/flexion, t8_t9/lateral_bending_right, t8_t9/axial_rotation_left, t7_t8/flexion, t7_t8/lateral_bending_right, t7_t8/axial_rotation_left, t6_t7/flexion, t6_t7/lateral_bending_right, t6_t7/axial_rotation_left, costovertebral_6_l/elevation',
  },
  {
    unit: 'rectus_abdominis_l',
    shortest: 0.676015,
    longest: 1.09895,
    crosses:
      'l5_s1/flexion, l5_s1/lateral_bending_right, l5_s1/axial_rotation_left, l4_l5/flexion, l4_l5/lateral_bending_right, l4_l5/axial_rotation_left, l3_l4/flexion, l3_l4/lateral_bending_right, l3_l4/axial_rotation_left, l2_l3/flexion, l2_l3/lateral_bending_right, l2_l3/axial_rotation_left, l1_l2/flexion, l1_l2/lateral_bending_right, l1_l2/axial_rotation_left, t12_l1/flexion, t12_l1/lateral_bending_right, t12_l1/axial_rotation_left, t11_t12/flexion, t11_t12/lateral_bending_right, t11_t12/axial_rotation_left, t10_t11/flexion, t10_t11/lateral_bending_right, t10_t11/axial_rotation_left, t9_t10/flexion, t9_t10/lateral_bending_right, t9_t10/axial_rotation_left, t8_t9/flexion, t8_t9/lateral_bending_right, t8_t9/axial_rotation_left, t7_t8/flexion, t7_t8/lateral_bending_right, t7_t8/axial_rotation_left, t6_t7/flexion, t6_t7/lateral_bending_right, t6_t7/axial_rotation_left, t5_t6/flexion, t5_t6/lateral_bending_right, t5_t6/axial_rotation_left, t4_t5/flexion, t4_t5/lateral_bending_right, t4_t5/axial_rotation_left, t3_t4/flexion, t3_t4/lateral_bending_right, t3_t4/axial_rotation_left, t2_t3/flexion, t2_t3/lateral_bending_right, t2_t3/axial_rotation_left, t1_t2/flexion, t1_t2/lateral_bending_right, t1_t2/axial_rotation_left, costovertebral_1_r/elevation',
  },
  {
    unit: 'external_oblique_l',
    shortest: 0.846218,
    longest: 1.05891,
    crosses:
      'l5_s1/flexion, l5_s1/lateral_bending_right, l5_s1/axial_rotation_left, l4_l5/flexion, l4_l5/lateral_bending_right, l4_l5/axial_rotation_left, l3_l4/flexion, l3_l4/lateral_bending_right, l3_l4/axial_rotation_left, l2_l3/flexion, l2_l3/lateral_bending_right, l2_l3/axial_rotation_left, l1_l2/flexion, l1_l2/lateral_bending_right, l1_l2/axial_rotation_left, t12_l1/flexion, t12_l1/lateral_bending_right, t12_l1/axial_rotation_left, t11_t12/flexion, t11_t12/lateral_bending_right, t11_t12/axial_rotation_left, t10_t11/flexion, t10_t11/lateral_bending_right, t10_t11/axial_rotation_left, t9_t10/flexion, t9_t10/lateral_bending_right, t9_t10/axial_rotation_left, t8_t9/flexion, t8_t9/lateral_bending_right, t8_t9/axial_rotation_left, t7_t8/flexion, t7_t8/lateral_bending_right, t7_t8/axial_rotation_left, t6_t7/flexion, t6_t7/lateral_bending_right, t6_t7/axial_rotation_left, costovertebral_6_l/elevation',
  },
  {
    unit: 'internal_oblique_l',
    shortest: 0.788455,
    longest: 1.15357,
    crosses:
      'l5_s1/flexion, l5_s1/lateral_bending_right, l5_s1/axial_rotation_left, l4_l5/flexion, l4_l5/lateral_bending_right, l4_l5/axial_rotation_left, l3_l4/flexion, l3_l4/lateral_bending_right, l3_l4/axial_rotation_left, l2_l3/flexion, l2_l3/lateral_bending_right, l2_l3/axial_rotation_left, l1_l2/flexion, l1_l2/lateral_bending_right, l1_l2/axial_rotation_left, t12_l1/flexion, t12_l1/lateral_bending_right, t12_l1/axial_rotation_left, t11_t12/flexion, t11_t12/lateral_bending_right, t11_t12/axial_rotation_left, t10_t11/flexion, t10_t11/lateral_bending_right, t10_t11/axial_rotation_left, t9_t10/flexion, t9_t10/lateral_bending_right, t9_t10/axial_rotation_left, t8_t9/flexion, t8_t9/lateral_bending_right, t8_t9/axial_rotation_left, t7_t8/flexion, t7_t8/lateral_bending_right, t7_t8/axial_rotation_left, t6_t7/flexion, t6_t7/lateral_bending_right, t6_t7/axial_rotation_left, costovertebral_6_l/elevation',
  },
  {
    unit: 'sternocleidomastoid_r',
    shortest: 0.931524,
    longest: 1.06146,
    crosses:
      'c7_t1/flexion, c7_t1/lateral_bending_right, c7_t1/axial_rotation_left, c6_c7/flexion, c6_c7/lateral_bending_right, c6_c7/axial_rotation_left, c5_c6/flexion, c5_c6/lateral_bending_right, c5_c6/axial_rotation_left, c4_c5/flexion, c4_c5/lateral_bending_right, c4_c5/axial_rotation_left, c3_c4/flexion, c3_c4/lateral_bending_right, c3_c4/axial_rotation_left, c2_c3/flexion, c2_c3/lateral_bending_right, c2_c3/axial_rotation_left, c1_c2/flexion, c1_c2/lateral_bending_right, c1_c2/axial_rotation_left, c0_c1/flexion, c0_c1/lateral_bending_right, c0_c1/axial_rotation_left, costovertebral_1_r/elevation',
  },
  {
    unit: 'splenius_capitis_r',
    shortest: 0.936265,
    longest: 1.06231,
    crosses:
      't2_t3/flexion, t2_t3/lateral_bending_right, t2_t3/axial_rotation_left, t1_t2/flexion, t1_t2/lateral_bending_right, t1_t2/axial_rotation_left, c7_t1/flexion, c7_t1/lateral_bending_right, c7_t1/axial_rotation_left, c6_c7/flexion, c6_c7/lateral_bending_right, c6_c7/axial_rotation_left, c5_c6/flexion, c5_c6/lateral_bending_right, c5_c6/axial_rotation_left, c4_c5/flexion, c4_c5/lateral_bending_right, c4_c5/axial_rotation_left, c3_c4/flexion, c3_c4/lateral_bending_right, c3_c4/axial_rotation_left, c2_c3/flexion, c2_c3/lateral_bending_right, c2_c3/axial_rotation_left, c1_c2/flexion, c1_c2/lateral_bending_right, c1_c2/axial_rotation_left, c0_c1/flexion, c0_c1/lateral_bending_right, c0_c1/axial_rotation_left',
  },
  {
    unit: 'splenius_cervicis_r',
    shortest: 0.988617,
    longest: 1.0112,
    crosses:
      't4_t5/flexion, t4_t5/lateral_bending_right, t4_t5/axial_rotation_left, t3_t4/flexion, t3_t4/lateral_bending_right, t3_t4/axial_rotation_left, t2_t3/flexion, t2_t3/lateral_bending_right, t2_t3/axial_rotation_left, t1_t2/flexion, t1_t2/lateral_bending_right, t1_t2/axial_rotation_left, c7_t1/flexion, c7_t1/lateral_bending_right, c7_t1/axial_rotation_left, c6_c7/flexion, c6_c7/lateral_bending_right, c6_c7/axial_rotation_left, c5_c6/flexion, c5_c6/lateral_bending_right, c5_c6/axial_rotation_left, c4_c5/flexion, c4_c5/lateral_bending_right, c4_c5/axial_rotation_left, c3_c4/flexion, c3_c4/lateral_bending_right, c3_c4/axial_rotation_left, c2_c3/flexion, c2_c3/lateral_bending_right, c2_c3/axial_rotation_left',
  },
  {
    unit: 'semispinalis_capitis_r',
    shortest: 0.953201,
    longest: 1.05321,
    crosses:
      't3_t4/flexion, t3_t4/lateral_bending_right, t3_t4/axial_rotation_left, t2_t3/flexion, t2_t3/lateral_bending_right, t2_t3/axial_rotation_left, t1_t2/flexion, t1_t2/lateral_bending_right, t1_t2/axial_rotation_left, c7_t1/flexion, c7_t1/lateral_bending_right, c7_t1/axial_rotation_left, c6_c7/flexion, c6_c7/lateral_bending_right, c6_c7/axial_rotation_left, c5_c6/flexion, c5_c6/lateral_bending_right, c5_c6/axial_rotation_left, c4_c5/flexion, c4_c5/lateral_bending_right, c4_c5/axial_rotation_left, c3_c4/flexion, c3_c4/lateral_bending_right, c3_c4/axial_rotation_left, c2_c3/flexion, c2_c3/lateral_bending_right, c2_c3/axial_rotation_left, c1_c2/flexion, c1_c2/lateral_bending_right, c1_c2/axial_rotation_left, c0_c1/flexion, c0_c1/lateral_bending_right, c0_c1/axial_rotation_left',
  },
  {
    unit: 'longissimus_capitis_r',
    shortest: 0.959009,
    longest: 1.07213,
    crosses:
      't2_t3/flexion, t2_t3/lateral_bending_right, t2_t3/axial_rotation_left, t1_t2/flexion, t1_t2/lateral_bending_right, t1_t2/axial_rotation_left, c7_t1/flexion, c7_t1/lateral_bending_right, c7_t1/axial_rotation_left, c6_c7/flexion, c6_c7/lateral_bending_right, c6_c7/axial_rotation_left, c5_c6/flexion, c5_c6/lateral_bending_right, c5_c6/axial_rotation_left, c4_c5/flexion, c4_c5/lateral_bending_right, c4_c5/axial_rotation_left, c3_c4/flexion, c3_c4/lateral_bending_right, c3_c4/axial_rotation_left, c2_c3/flexion, c2_c3/lateral_bending_right, c2_c3/axial_rotation_left, c1_c2/flexion, c1_c2/lateral_bending_right, c1_c2/axial_rotation_left, c0_c1/flexion, c0_c1/lateral_bending_right, c0_c1/axial_rotation_left',
  },
  {
    unit: 'longissimus_cervicis_r',
    shortest: 0.973761,
    longest: 1.02685,
    crosses:
      't3_t4/flexion, t3_t4/lateral_bending_right, t3_t4/axial_rotation_left, t2_t3/flexion, t2_t3/lateral_bending_right, t2_t3/axial_rotation_left, t1_t2/flexion, t1_t2/lateral_bending_right, t1_t2/axial_rotation_left, c7_t1/flexion, c7_t1/lateral_bending_right, c7_t1/axial_rotation_left, c6_c7/flexion, c6_c7/lateral_bending_right, c6_c7/axial_rotation_left, c5_c6/flexion, c5_c6/lateral_bending_right, c5_c6/axial_rotation_left, c4_c5/flexion, c4_c5/lateral_bending_right, c4_c5/axial_rotation_left',
  },
  {
    unit: 'scalenus_anterior_r',
    shortest: 0.933504,
    longest: 1.06408,
    crosses:
      'c7_t1/flexion, c7_t1/lateral_bending_right, c7_t1/axial_rotation_left, c6_c7/flexion, c6_c7/lateral_bending_right, c6_c7/axial_rotation_left, c5_c6/flexion, c5_c6/lateral_bending_right, c5_c6/axial_rotation_left, c4_c5/flexion, c4_c5/lateral_bending_right, c4_c5/axial_rotation_left, costovertebral_1_r/elevation',
  },
  {
    unit: 'scalenus_medius_r',
    shortest: 0.931558,
    longest: 1.06723,
    crosses:
      'c7_t1/flexion, c7_t1/lateral_bending_right, c7_t1/axial_rotation_left, c6_c7/flexion, c6_c7/lateral_bending_right, c6_c7/axial_rotation_left, c5_c6/flexion, c5_c6/lateral_bending_right, c5_c6/axial_rotation_left, costovertebral_1_r/elevation',
  },
  {
    unit: 'scalenus_posterior_r',
    shortest: 0.950174,
    longest: 1.06927,
    crosses:
      't1_t2/flexion, t1_t2/lateral_bending_right, t1_t2/axial_rotation_left, c7_t1/flexion, c7_t1/lateral_bending_right, c7_t1/axial_rotation_left, c6_c7/flexion, c6_c7/lateral_bending_right, c6_c7/axial_rotation_left, costovertebral_2_r/elevation',
  },
  {
    unit: 'longus_colli_r',
    shortest: 0.970946,
    longest: 1.02209,
    crosses:
      't1_t2/flexion, t1_t2/lateral_bending_right, t1_t2/axial_rotation_left, c7_t1/flexion, c7_t1/lateral_bending_right, c7_t1/axial_rotation_left, c6_c7/flexion, c6_c7/lateral_bending_right, c6_c7/axial_rotation_left, c5_c6/flexion, c5_c6/lateral_bending_right, c5_c6/axial_rotation_left, c4_c5/flexion, c4_c5/lateral_bending_right, c4_c5/axial_rotation_left, c3_c4/flexion, c3_c4/lateral_bending_right, c3_c4/axial_rotation_left, c2_c3/flexion, c2_c3/lateral_bending_right, c2_c3/axial_rotation_left, c1_c2/flexion, c1_c2/lateral_bending_right, c1_c2/axial_rotation_left',
  },
  {
    unit: 'longus_capitis_r',
    shortest: 0.963746,
    longest: 1.0417,
    crosses:
      'c3_c4/flexion, c3_c4/lateral_bending_right, c3_c4/axial_rotation_left, c2_c3/flexion, c2_c3/lateral_bending_right, c2_c3/axial_rotation_left, c1_c2/flexion, c1_c2/lateral_bending_right, c1_c2/axial_rotation_left, c0_c1/flexion, c0_c1/lateral_bending_right, c0_c1/axial_rotation_left',
  },
  {
    unit: 'sternocleidomastoid_l',
    shortest: 0.931679,
    longest: 1.06209,
    crosses:
      'c7_t1/flexion, c7_t1/lateral_bending_right, c7_t1/axial_rotation_left, c6_c7/flexion, c6_c7/lateral_bending_right, c6_c7/axial_rotation_left, c5_c6/flexion, c5_c6/lateral_bending_right, c5_c6/axial_rotation_left, c4_c5/flexion, c4_c5/lateral_bending_right, c4_c5/axial_rotation_left, c3_c4/flexion, c3_c4/lateral_bending_right, c3_c4/axial_rotation_left, c2_c3/flexion, c2_c3/lateral_bending_right, c2_c3/axial_rotation_left, c1_c2/flexion, c1_c2/lateral_bending_right, c1_c2/axial_rotation_left, c0_c1/flexion, c0_c1/lateral_bending_right, c0_c1/axial_rotation_left, costovertebral_1_r/elevation',
  },
  {
    unit: 'splenius_capitis_l',
    shortest: 0.936128,
    longest: 1.06197,
    crosses:
      't2_t3/flexion, t2_t3/lateral_bending_right, t2_t3/axial_rotation_left, t1_t2/flexion, t1_t2/lateral_bending_right, t1_t2/axial_rotation_left, c7_t1/flexion, c7_t1/lateral_bending_right, c7_t1/axial_rotation_left, c6_c7/flexion, c6_c7/lateral_bending_right, c6_c7/axial_rotation_left, c5_c6/flexion, c5_c6/lateral_bending_right, c5_c6/axial_rotation_left, c4_c5/flexion, c4_c5/lateral_bending_right, c4_c5/axial_rotation_left, c3_c4/flexion, c3_c4/lateral_bending_right, c3_c4/axial_rotation_left, c2_c3/flexion, c2_c3/lateral_bending_right, c2_c3/axial_rotation_left, c1_c2/flexion, c1_c2/lateral_bending_right, c1_c2/axial_rotation_left, c0_c1/flexion, c0_c1/lateral_bending_right, c0_c1/axial_rotation_left',
  },
  {
    unit: 'splenius_cervicis_l',
    shortest: 0.988611,
    longest: 1.0112,
    crosses:
      't4_t5/flexion, t4_t5/lateral_bending_right, t4_t5/axial_rotation_left, t3_t4/flexion, t3_t4/lateral_bending_right, t3_t4/axial_rotation_left, t2_t3/flexion, t2_t3/lateral_bending_right, t2_t3/axial_rotation_left, t1_t2/flexion, t1_t2/lateral_bending_right, t1_t2/axial_rotation_left, c7_t1/flexion, c7_t1/lateral_bending_right, c7_t1/axial_rotation_left, c6_c7/flexion, c6_c7/lateral_bending_right, c6_c7/axial_rotation_left, c5_c6/flexion, c5_c6/lateral_bending_right, c5_c6/axial_rotation_left, c4_c5/flexion, c4_c5/lateral_bending_right, c4_c5/axial_rotation_left, c3_c4/flexion, c3_c4/lateral_bending_right, c3_c4/axial_rotation_left, c2_c3/flexion, c2_c3/lateral_bending_right, c2_c3/axial_rotation_left',
  },
  {
    unit: 'semispinalis_capitis_l',
    shortest: 0.953201,
    longest: 1.05321,
    crosses:
      't3_t4/flexion, t3_t4/lateral_bending_right, t3_t4/axial_rotation_left, t2_t3/flexion, t2_t3/lateral_bending_right, t2_t3/axial_rotation_left, t1_t2/flexion, t1_t2/lateral_bending_right, t1_t2/axial_rotation_left, c7_t1/flexion, c7_t1/lateral_bending_right, c7_t1/axial_rotation_left, c6_c7/flexion, c6_c7/lateral_bending_right, c6_c7/axial_rotation_left, c5_c6/flexion, c5_c6/lateral_bending_right, c5_c6/axial_rotation_left, c4_c5/flexion, c4_c5/lateral_bending_right, c4_c5/axial_rotation_left, c3_c4/flexion, c3_c4/lateral_bending_right, c3_c4/axial_rotation_left, c2_c3/flexion, c2_c3/lateral_bending_right, c2_c3/axial_rotation_left, c1_c2/flexion, c1_c2/lateral_bending_right, c1_c2/axial_rotation_left, c0_c1/flexion, c0_c1/lateral_bending_right, c0_c1/axial_rotation_left',
  },
  {
    unit: 'longissimus_capitis_l',
    shortest: 0.959014,
    longest: 1.07209,
    crosses:
      't2_t3/flexion, t2_t3/lateral_bending_right, t2_t3/axial_rotation_left, t1_t2/flexion, t1_t2/lateral_bending_right, t1_t2/axial_rotation_left, c7_t1/flexion, c7_t1/lateral_bending_right, c7_t1/axial_rotation_left, c6_c7/flexion, c6_c7/lateral_bending_right, c6_c7/axial_rotation_left, c5_c6/flexion, c5_c6/lateral_bending_right, c5_c6/axial_rotation_left, c4_c5/flexion, c4_c5/lateral_bending_right, c4_c5/axial_rotation_left, c3_c4/flexion, c3_c4/lateral_bending_right, c3_c4/axial_rotation_left, c2_c3/flexion, c2_c3/lateral_bending_right, c2_c3/axial_rotation_left, c1_c2/flexion, c1_c2/lateral_bending_right, c1_c2/axial_rotation_left, c0_c1/flexion, c0_c1/lateral_bending_right, c0_c1/axial_rotation_left',
  },
  {
    unit: 'longissimus_cervicis_l',
    shortest: 0.973747,
    longest: 1.02688,
    crosses:
      't3_t4/flexion, t3_t4/lateral_bending_right, t3_t4/axial_rotation_left, t2_t3/flexion, t2_t3/lateral_bending_right, t2_t3/axial_rotation_left, t1_t2/flexion, t1_t2/lateral_bending_right, t1_t2/axial_rotation_left, c7_t1/flexion, c7_t1/lateral_bending_right, c7_t1/axial_rotation_left, c6_c7/flexion, c6_c7/lateral_bending_right, c6_c7/axial_rotation_left, c5_c6/flexion, c5_c6/lateral_bending_right, c5_c6/axial_rotation_left, c4_c5/flexion, c4_c5/lateral_bending_right, c4_c5/axial_rotation_left',
  },
  {
    unit: 'scalenus_anterior_l',
    shortest: 0.933329,
    longest: 1.06425,
    crosses:
      'c7_t1/flexion, c7_t1/lateral_bending_right, c7_t1/axial_rotation_left, c6_c7/flexion, c6_c7/lateral_bending_right, c6_c7/axial_rotation_left, c5_c6/flexion, c5_c6/lateral_bending_right, c5_c6/axial_rotation_left, c4_c5/flexion, c4_c5/lateral_bending_right, c4_c5/axial_rotation_left, costovertebral_1_l/elevation',
  },
  {
    unit: 'scalenus_medius_l',
    shortest: 0.931558,
    longest: 1.06723,
    crosses:
      'c7_t1/flexion, c7_t1/lateral_bending_right, c7_t1/axial_rotation_left, c6_c7/flexion, c6_c7/lateral_bending_right, c6_c7/axial_rotation_left, c5_c6/flexion, c5_c6/lateral_bending_right, c5_c6/axial_rotation_left, costovertebral_1_l/elevation',
  },
  {
    unit: 'scalenus_posterior_l',
    shortest: 0.950169,
    longest: 1.06927,
    crosses:
      't1_t2/flexion, t1_t2/lateral_bending_right, t1_t2/axial_rotation_left, c7_t1/flexion, c7_t1/lateral_bending_right, c7_t1/axial_rotation_left, c6_c7/flexion, c6_c7/lateral_bending_right, c6_c7/axial_rotation_left, costovertebral_2_l/elevation',
  },
  {
    unit: 'longus_colli_l',
    shortest: 0.970946,
    longest: 1.02209,
    crosses:
      't1_t2/flexion, t1_t2/lateral_bending_right, t1_t2/axial_rotation_left, c7_t1/flexion, c7_t1/lateral_bending_right, c7_t1/axial_rotation_left, c6_c7/flexion, c6_c7/lateral_bending_right, c6_c7/axial_rotation_left, c5_c6/flexion, c5_c6/lateral_bending_right, c5_c6/axial_rotation_left, c4_c5/flexion, c4_c5/lateral_bending_right, c4_c5/axial_rotation_left, c3_c4/flexion, c3_c4/lateral_bending_right, c3_c4/axial_rotation_left, c2_c3/flexion, c2_c3/lateral_bending_right, c2_c3/axial_rotation_left, c1_c2/flexion, c1_c2/lateral_bending_right, c1_c2/axial_rotation_left',
  },
  {
    unit: 'longus_capitis_l',
    shortest: 0.963572,
    longest: 1.04182,
    crosses:
      'c3_c4/flexion, c3_c4/lateral_bending_right, c3_c4/axial_rotation_left, c2_c3/flexion, c2_c3/lateral_bending_right, c2_c3/axial_rotation_left, c1_c2/flexion, c1_c2/lateral_bending_right, c1_c2/axial_rotation_left, c0_c1/flexion, c0_c1/lateral_bending_right, c0_c1/axial_rotation_left',
  },
  {
    unit: 'trapezius_upper_r',
    shortest: 0.837712,
    longest: 1.10754,
    crosses:
      'sternoclavicular_r/protraction, sternoclavicular_r/elevation, c7_t1/flexion, c7_t1/lateral_bending_right, c7_t1/axial_rotation_left, c6_c7/flexion, c6_c7/lateral_bending_right, c6_c7/axial_rotation_left, c5_c6/flexion, c5_c6/lateral_bending_right, c5_c6/axial_rotation_left, c4_c5/flexion, c4_c5/lateral_bending_right, c4_c5/axial_rotation_left, c3_c4/flexion, c3_c4/lateral_bending_right, c3_c4/axial_rotation_left, c2_c3/flexion, c2_c3/lateral_bending_right, c2_c3/axial_rotation_left, c1_c2/flexion, c1_c2/lateral_bending_right, c1_c2/axial_rotation_left, c0_c1/flexion, c0_c1/lateral_bending_right, c0_c1/axial_rotation_left, costovertebral_1_r/elevation',
  },
  {
    unit: 'trapezius_middle_r',
    shortest: 0.537603,
    longest: 1.02386,
    crosses:
      'sternoclavicular_r/protraction, sternoclavicular_r/elevation, c7_t1/flexion, c7_t1/lateral_bending_right, c7_t1/axial_rotation_left, costovertebral_1_r/elevation, acromioclavicular_r/unrotate_clavicle_elevation, acromioclavicular_r/unrotate_clavicle_protraction, acromioclavicular_r/protraction, acromioclavicular_r/upward_rotation, acromioclavicular_r/tilt',
  },
  {
    unit: 'trapezius_lower_r',
    shortest: 0.790991,
    longest: 1.17319,
    crosses:
      'sternoclavicular_r/protraction, sternoclavicular_r/elevation, t7_t8/flexion, t7_t8/lateral_bending_right, t7_t8/axial_rotation_left, t6_t7/flexion, t6_t7/lateral_bending_right, t6_t7/axial_rotation_left, t5_t6/flexion, t5_t6/lateral_bending_right, t5_t6/axial_rotation_left, t4_t5/flexion, t4_t5/lateral_bending_right, t4_t5/axial_rotation_left, t3_t4/flexion, t3_t4/lateral_bending_right, t3_t4/axial_rotation_left, t2_t3/flexion, t2_t3/lateral_bending_right, t2_t3/axial_rotation_left, t1_t2/flexion, t1_t2/lateral_bending_right, t1_t2/axial_rotation_left, costovertebral_1_r/elevation, acromioclavicular_r/unrotate_clavicle_elevation, acromioclavicular_r/unrotate_clavicle_protraction, acromioclavicular_r/protraction, acromioclavicular_r/upward_rotation, acromioclavicular_r/tilt',
  },
  {
    unit: 'levator_scapulae_r',
    shortest: 0.89341,
    longest: 1.54498,
    crosses:
      'sternoclavicular_r/protraction, sternoclavicular_r/elevation, c7_t1/flexion, c7_t1/lateral_bending_right, c7_t1/axial_rotation_left, c6_c7/flexion, c6_c7/lateral_bending_right, c6_c7/axial_rotation_left, c5_c6/flexion, c5_c6/lateral_bending_right, c5_c6/axial_rotation_left, c4_c5/flexion, c4_c5/lateral_bending_right, c4_c5/axial_rotation_left, c3_c4/flexion, c3_c4/lateral_bending_right, c3_c4/axial_rotation_left, c2_c3/flexion, c2_c3/lateral_bending_right, c2_c3/axial_rotation_left, costovertebral_1_r/elevation, acromioclavicular_r/unrotate_clavicle_elevation, acromioclavicular_r/unrotate_clavicle_protraction, acromioclavicular_r/protraction, acromioclavicular_r/upward_rotation, acromioclavicular_r/tilt',
  },
  {
    unit: 'rhomboid_minor_r',
    shortest: 0.750072,
    longest: 1.8894,
    crosses:
      'sternoclavicular_r/protraction, sternoclavicular_r/elevation, c7_t1/flexion, c7_t1/lateral_bending_right, c7_t1/axial_rotation_left, costovertebral_1_r/elevation, acromioclavicular_r/unrotate_clavicle_elevation, acromioclavicular_r/unrotate_clavicle_protraction, acromioclavicular_r/protraction, acromioclavicular_r/upward_rotation, acromioclavicular_r/tilt',
  },
  {
    unit: 'rhomboid_major_r',
    shortest: 0.609044,
    longest: 2.7524,
    crosses:
      'sternoclavicular_r/protraction, sternoclavicular_r/elevation, t2_t3/flexion, t2_t3/lateral_bending_right, t2_t3/axial_rotation_left, t1_t2/flexion, t1_t2/lateral_bending_right, t1_t2/axial_rotation_left, costovertebral_1_r/elevation, acromioclavicular_r/unrotate_clavicle_elevation, acromioclavicular_r/unrotate_clavicle_protraction, acromioclavicular_r/protraction, acromioclavicular_r/upward_rotation, acromioclavicular_r/tilt',
  },
  {
    unit: 'serratus_anterior_superior_r',
    shortest: 0.769062,
    longest: 1.84645,
    crosses:
      'sternoclavicular_r/protraction, sternoclavicular_r/elevation, t1_t2/flexion, t1_t2/lateral_bending_right, t1_t2/axial_rotation_left, costovertebral_1_r/elevation, costovertebral_2_r/elevation, acromioclavicular_r/unrotate_clavicle_elevation, acromioclavicular_r/unrotate_clavicle_protraction, acromioclavicular_r/protraction, acromioclavicular_r/upward_rotation, acromioclavicular_r/tilt',
  },
  {
    unit: 'serratus_anterior_middle_r',
    shortest: 0.713813,
    longest: 1.47941,
    crosses:
      'sternoclavicular_r/protraction, sternoclavicular_r/elevation, t4_t5/flexion, t4_t5/lateral_bending_right, t4_t5/axial_rotation_left, t3_t4/flexion, t3_t4/lateral_bending_right, t3_t4/axial_rotation_left, t2_t3/flexion, t2_t3/lateral_bending_right, t2_t3/axial_rotation_left, t1_t2/flexion, t1_t2/lateral_bending_right, t1_t2/axial_rotation_left, costovertebral_1_r/elevation, costovertebral_5_r/elevation, acromioclavicular_r/unrotate_clavicle_elevation, acromioclavicular_r/unrotate_clavicle_protraction, acromioclavicular_r/protraction, acromioclavicular_r/upward_rotation, acromioclavicular_r/tilt',
  },
  {
    unit: 'serratus_anterior_inferior_r',
    shortest: 0.545413,
    longest: 1.70058,
    crosses:
      'sternoclavicular_r/protraction, sternoclavicular_r/elevation, t7_t8/flexion, t7_t8/lateral_bending_right, t7_t8/axial_rotation_left, t6_t7/flexion, t6_t7/lateral_bending_right, t6_t7/axial_rotation_left, t5_t6/flexion, t5_t6/lateral_bending_right, t5_t6/axial_rotation_left, t4_t5/flexion, t4_t5/lateral_bending_right, t4_t5/axial_rotation_left, t3_t4/flexion, t3_t4/lateral_bending_right, t3_t4/axial_rotation_left, t2_t3/flexion, t2_t3/lateral_bending_right, t2_t3/axial_rotation_left, t1_t2/flexion, t1_t2/lateral_bending_right, t1_t2/axial_rotation_left, costovertebral_1_r/elevation, costovertebral_8_r/elevation, acromioclavicular_r/unrotate_clavicle_elevation, acromioclavicular_r/unrotate_clavicle_protraction, acromioclavicular_r/protraction, acromioclavicular_r/upward_rotation, acromioclavicular_r/tilt',
  },
  {
    unit: 'pectoralis_minor_r',
    shortest: 0.865871,
    longest: 1.1676,
    crosses:
      'sternoclavicular_r/protraction, sternoclavicular_r/elevation, t3_t4/flexion, t3_t4/lateral_bending_right, t3_t4/axial_rotation_left, t2_t3/flexion, t2_t3/lateral_bending_right, t2_t3/axial_rotation_left, t1_t2/flexion, t1_t2/lateral_bending_right, t1_t2/axial_rotation_left, costovertebral_1_r/elevation, costovertebral_4_r/elevation, acromioclavicular_r/unrotate_clavicle_elevation, acromioclavicular_r/unrotate_clavicle_protraction, acromioclavicular_r/protraction, acromioclavicular_r/upward_rotation, acromioclavicular_r/tilt',
  },
  {
    unit: 'trapezius_upper_l',
    shortest: 0.821205,
    longest: 1.10752,
    crosses:
      'sternoclavicular_l/protraction, sternoclavicular_l/elevation, c7_t1/flexion, c7_t1/lateral_bending_right, c7_t1/axial_rotation_left, c6_c7/flexion, c6_c7/lateral_bending_right, c6_c7/axial_rotation_left, c5_c6/flexion, c5_c6/lateral_bending_right, c5_c6/axial_rotation_left, c4_c5/flexion, c4_c5/lateral_bending_right, c4_c5/axial_rotation_left, c3_c4/flexion, c3_c4/lateral_bending_right, c3_c4/axial_rotation_left, c2_c3/flexion, c2_c3/lateral_bending_right, c2_c3/axial_rotation_left, c1_c2/flexion, c1_c2/lateral_bending_right, c1_c2/axial_rotation_left, c0_c1/flexion, c0_c1/lateral_bending_right, c0_c1/axial_rotation_left, costovertebral_1_r/elevation',
  },
  {
    unit: 'trapezius_middle_l',
    shortest: 0.529562,
    longest: 1.02386,
    crosses:
      'sternoclavicular_l/protraction, sternoclavicular_l/elevation, c7_t1/flexion, c7_t1/lateral_bending_right, c7_t1/axial_rotation_left, costovertebral_1_r/elevation, acromioclavicular_l/unrotate_clavicle_elevation, acromioclavicular_l/unrotate_clavicle_protraction, acromioclavicular_l/protraction, acromioclavicular_l/upward_rotation, acromioclavicular_l/tilt',
  },
  {
    unit: 'trapezius_lower_l',
    shortest: 0.818434,
    longest: 1.17868,
    crosses:
      'sternoclavicular_l/protraction, sternoclavicular_l/elevation, t7_t8/flexion, t7_t8/lateral_bending_right, t7_t8/axial_rotation_left, t6_t7/flexion, t6_t7/lateral_bending_right, t6_t7/axial_rotation_left, t5_t6/flexion, t5_t6/lateral_bending_right, t5_t6/axial_rotation_left, t4_t5/flexion, t4_t5/lateral_bending_right, t4_t5/axial_rotation_left, t3_t4/flexion, t3_t4/lateral_bending_right, t3_t4/axial_rotation_left, t2_t3/flexion, t2_t3/lateral_bending_right, t2_t3/axial_rotation_left, t1_t2/flexion, t1_t2/lateral_bending_right, t1_t2/axial_rotation_left, costovertebral_1_r/elevation, acromioclavicular_l/unrotate_clavicle_elevation, acromioclavicular_l/unrotate_clavicle_protraction, acromioclavicular_l/protraction, acromioclavicular_l/upward_rotation, acromioclavicular_l/tilt',
  },
  {
    unit: 'levator_scapulae_l',
    shortest: 0.883397,
    longest: 1.54676,
    crosses:
      'sternoclavicular_l/protraction, sternoclavicular_l/elevation, c7_t1/flexion, c7_t1/lateral_bending_right, c7_t1/axial_rotation_left, c6_c7/flexion, c6_c7/lateral_bending_right, c6_c7/axial_rotation_left, c5_c6/flexion, c5_c6/lateral_bending_right, c5_c6/axial_rotation_left, c4_c5/flexion, c4_c5/lateral_bending_right, c4_c5/axial_rotation_left, c3_c4/flexion, c3_c4/lateral_bending_right, c3_c4/axial_rotation_left, c2_c3/flexion, c2_c3/lateral_bending_right, c2_c3/axial_rotation_left, costovertebral_1_r/elevation, acromioclavicular_l/unrotate_clavicle_elevation, acromioclavicular_l/unrotate_clavicle_protraction, acromioclavicular_l/protraction, acromioclavicular_l/upward_rotation, acromioclavicular_l/tilt',
  },
  {
    unit: 'rhomboid_minor_l',
    shortest: 0.76171,
    longest: 1.89346,
    crosses:
      'sternoclavicular_l/protraction, sternoclavicular_l/elevation, c7_t1/flexion, c7_t1/lateral_bending_right, c7_t1/axial_rotation_left, costovertebral_1_r/elevation, acromioclavicular_l/unrotate_clavicle_elevation, acromioclavicular_l/unrotate_clavicle_protraction, acromioclavicular_l/protraction, acromioclavicular_l/upward_rotation, acromioclavicular_l/tilt',
  },
  {
    unit: 'rhomboid_major_l',
    shortest: 0.615218,
    longest: 2.74959,
    crosses:
      'sternoclavicular_l/protraction, sternoclavicular_l/elevation, t2_t3/flexion, t2_t3/lateral_bending_right, t2_t3/axial_rotation_left, t1_t2/flexion, t1_t2/lateral_bending_right, t1_t2/axial_rotation_left, costovertebral_1_r/elevation, acromioclavicular_l/unrotate_clavicle_elevation, acromioclavicular_l/unrotate_clavicle_protraction, acromioclavicular_l/protraction, acromioclavicular_l/upward_rotation, acromioclavicular_l/tilt',
  },
  {
    unit: 'serratus_anterior_superior_l',
    shortest: 0.769066,
    longest: 1.85112,
    crosses:
      'sternoclavicular_l/protraction, sternoclavicular_l/elevation, t1_t2/flexion, t1_t2/lateral_bending_right, t1_t2/axial_rotation_left, costovertebral_1_r/elevation, costovertebral_2_l/elevation, acromioclavicular_l/unrotate_clavicle_elevation, acromioclavicular_l/unrotate_clavicle_protraction, acromioclavicular_l/protraction, acromioclavicular_l/upward_rotation, acromioclavicular_l/tilt',
  },
  {
    unit: 'serratus_anterior_middle_l',
    shortest: 0.712799,
    longest: 1.49895,
    crosses:
      'sternoclavicular_l/protraction, sternoclavicular_l/elevation, t4_t5/flexion, t4_t5/lateral_bending_right, t4_t5/axial_rotation_left, t3_t4/flexion, t3_t4/lateral_bending_right, t3_t4/axial_rotation_left, t2_t3/flexion, t2_t3/lateral_bending_right, t2_t3/axial_rotation_left, t1_t2/flexion, t1_t2/lateral_bending_right, t1_t2/axial_rotation_left, costovertebral_1_r/elevation, costovertebral_5_l/elevation, acromioclavicular_l/unrotate_clavicle_elevation, acromioclavicular_l/unrotate_clavicle_protraction, acromioclavicular_l/protraction, acromioclavicular_l/upward_rotation, acromioclavicular_l/tilt',
  },
  {
    unit: 'serratus_anterior_inferior_l',
    shortest: 0.548594,
    longest: 1.69787,
    crosses:
      'sternoclavicular_l/protraction, sternoclavicular_l/elevation, t7_t8/flexion, t7_t8/lateral_bending_right, t7_t8/axial_rotation_left, t6_t7/flexion, t6_t7/lateral_bending_right, t6_t7/axial_rotation_left, t5_t6/flexion, t5_t6/lateral_bending_right, t5_t6/axial_rotation_left, t4_t5/flexion, t4_t5/lateral_bending_right, t4_t5/axial_rotation_left, t3_t4/flexion, t3_t4/lateral_bending_right, t3_t4/axial_rotation_left, t2_t3/flexion, t2_t3/lateral_bending_right, t2_t3/axial_rotation_left, t1_t2/flexion, t1_t2/lateral_bending_right, t1_t2/axial_rotation_left, costovertebral_1_r/elevation, costovertebral_8_l/elevation, acromioclavicular_l/unrotate_clavicle_elevation, acromioclavicular_l/unrotate_clavicle_protraction, acromioclavicular_l/protraction, acromioclavicular_l/upward_rotation, acromioclavicular_l/tilt',
  },
  {
    unit: 'pectoralis_minor_l',
    shortest: 0.86587,
    longest: 1.18099,
    crosses:
      'sternoclavicular_l/protraction, sternoclavicular_l/elevation, t3_t4/flexion, t3_t4/lateral_bending_right, t3_t4/axial_rotation_left, t2_t3/flexion, t2_t3/lateral_bending_right, t2_t3/axial_rotation_left, t1_t2/flexion, t1_t2/lateral_bending_right, t1_t2/axial_rotation_left, costovertebral_1_r/elevation, costovertebral_4_l/elevation, acromioclavicular_l/unrotate_clavicle_elevation, acromioclavicular_l/unrotate_clavicle_protraction, acromioclavicular_l/protraction, acromioclavicular_l/upward_rotation, acromioclavicular_l/tilt',
  },
  {
    unit: 'external_intercostal_1_r',
    shortest: 0.781141,
    longest: 1.28515,
    crosses:
      't1_t2/flexion, t1_t2/lateral_bending_right, t1_t2/axial_rotation_left, costovertebral_1_r/elevation, costovertebral_2_r/elevation',
  },
  {
    unit: 'external_intercostal_2_r',
    shortest: 0.858312,
    longest: 1.43031,
    crosses:
      't2_t3/flexion, t2_t3/lateral_bending_right, t2_t3/axial_rotation_left, costovertebral_2_r/elevation, costovertebral_3_r/elevation',
  },
  {
    unit: 'external_intercostal_3_r',
    shortest: 0.877615,
    longest: 1.26121,
    crosses:
      't3_t4/flexion, t3_t4/lateral_bending_right, t3_t4/axial_rotation_left, costovertebral_3_r/elevation, costovertebral_4_r/elevation',
  },
  {
    unit: 'external_intercostal_4_r',
    shortest: 0.86607,
    longest: 1.27207,
    crosses:
      't4_t5/flexion, t4_t5/lateral_bending_right, t4_t5/axial_rotation_left, costovertebral_4_r/elevation, costovertebral_5_r/elevation',
  },
  {
    unit: 'external_intercostal_5_r',
    shortest: 0.844506,
    longest: 1.44006,
    crosses:
      't5_t6/flexion, t5_t6/lateral_bending_right, t5_t6/axial_rotation_left, costovertebral_5_r/elevation, costovertebral_6_r/elevation',
  },
  {
    unit: 'external_intercostal_6_r',
    shortest: 0.844393,
    longest: 1.46232,
    crosses:
      't6_t7/flexion, t6_t7/lateral_bending_right, t6_t7/axial_rotation_left, costovertebral_6_r/elevation, costovertebral_7_r/elevation',
  },
  {
    unit: 'external_intercostal_7_r',
    shortest: 0.847244,
    longest: 1.46189,
    crosses:
      't7_t8/flexion, t7_t8/lateral_bending_right, t7_t8/axial_rotation_left, costovertebral_7_r/elevation, costovertebral_8_r/elevation',
  },
  {
    unit: 'external_intercostal_8_r',
    shortest: 0.77659,
    longest: 1.387,
    crosses:
      't8_t9/flexion, t8_t9/lateral_bending_right, t8_t9/axial_rotation_left, costovertebral_8_r/elevation, costovertebral_9_r/elevation',
  },
  {
    unit: 'external_intercostal_9_r',
    shortest: 0.854349,
    longest: 1.35942,
    crosses:
      't9_t10/flexion, t9_t10/lateral_bending_right, t9_t10/axial_rotation_left, costovertebral_9_r/elevation, costovertebral_10_r/elevation',
  },
  {
    unit: 'external_intercostal_10_r',
    shortest: 0.809995,
    longest: 1.47327,
    crosses:
      't10_t11/flexion, t10_t11/lateral_bending_right, t10_t11/axial_rotation_left, costovertebral_10_r/elevation, costovertebral_11_r/elevation',
  },
  {
    unit: 'external_intercostal_11_r',
    shortest: 0.765347,
    longest: 1.25692,
    crosses:
      't11_t12/flexion, t11_t12/lateral_bending_right, t11_t12/axial_rotation_left, costovertebral_11_r/elevation, costovertebral_12_r/elevation',
  },
  {
    unit: 'internal_intercostal_1_r',
    shortest: 0.706741,
    longest: 1.30172,
    crosses:
      't1_t2/flexion, t1_t2/lateral_bending_right, t1_t2/axial_rotation_left, costovertebral_1_r/elevation, costovertebral_2_r/elevation',
  },
  {
    unit: 'internal_intercostal_2_r',
    shortest: 0.58624,
    longest: 1.40551,
    crosses:
      't2_t3/flexion, t2_t3/lateral_bending_right, t2_t3/axial_rotation_left, costovertebral_2_r/elevation, costovertebral_3_r/elevation',
  },
  {
    unit: 'internal_intercostal_3_r',
    shortest: 0.501128,
    longest: 1.49359,
    crosses:
      't3_t4/flexion, t3_t4/lateral_bending_right, t3_t4/axial_rotation_left, costovertebral_3_r/elevation, costovertebral_4_r/elevation',
  },
  {
    unit: 'internal_intercostal_4_r',
    shortest: 0.223185,
    longest: 1.9448,
    crosses:
      't4_t5/flexion, t4_t5/lateral_bending_right, t4_t5/axial_rotation_left, costovertebral_4_r/elevation, costovertebral_5_r/elevation',
  },
  {
    unit: 'internal_intercostal_5_r',
    shortest: 0.365501,
    longest: 1.74358,
    crosses:
      't5_t6/flexion, t5_t6/lateral_bending_right, t5_t6/axial_rotation_left, costovertebral_5_r/elevation, costovertebral_6_r/elevation',
  },
  {
    unit: 'internal_intercostal_6_r',
    shortest: 0.474019,
    longest: 1.71531,
    crosses:
      't6_t7/flexion, t6_t7/lateral_bending_right, t6_t7/axial_rotation_left, costovertebral_6_r/elevation, costovertebral_7_r/elevation',
  },
  {
    unit: 'internal_intercostal_7_r',
    shortest: 0.683712,
    longest: 1.78513,
    crosses:
      't7_t8/flexion, t7_t8/lateral_bending_right, t7_t8/axial_rotation_left, costovertebral_7_r/elevation, costovertebral_8_r/elevation',
  },
  {
    unit: 'internal_intercostal_8_r',
    shortest: 0.545123,
    longest: 1.64545,
    crosses:
      't8_t9/flexion, t8_t9/lateral_bending_right, t8_t9/axial_rotation_left, costovertebral_8_r/elevation, costovertebral_9_r/elevation',
  },
  {
    unit: 'internal_intercostal_9_r',
    shortest: 0.710835,
    longest: 1.79678,
    crosses:
      't9_t10/flexion, t9_t10/lateral_bending_right, t9_t10/axial_rotation_left, costovertebral_9_r/elevation, costovertebral_10_r/elevation',
  },
  {
    unit: 'internal_intercostal_10_r',
    shortest: 0.888784,
    longest: 1.53795,
    crosses:
      't10_t11/flexion, t10_t11/lateral_bending_right, t10_t11/axial_rotation_left, costovertebral_10_r/elevation, costovertebral_11_r/elevation',
  },
  {
    unit: 'internal_intercostal_11_r',
    shortest: 0.872918,
    longest: 1.26287,
    crosses:
      't11_t12/flexion, t11_t12/lateral_bending_right, t11_t12/axial_rotation_left, costovertebral_11_r/elevation, costovertebral_12_r/elevation',
  },
  {
    unit: 'external_intercostal_1_l',
    shortest: 0.78114,
    longest: 1.28515,
    crosses:
      't1_t2/flexion, t1_t2/lateral_bending_right, t1_t2/axial_rotation_left, costovertebral_1_l/elevation, costovertebral_2_l/elevation',
  },
  {
    unit: 'external_intercostal_2_l',
    shortest: 0.85831,
    longest: 1.4303,
    crosses:
      't2_t3/flexion, t2_t3/lateral_bending_right, t2_t3/axial_rotation_left, costovertebral_2_l/elevation, costovertebral_3_l/elevation',
  },
  {
    unit: 'external_intercostal_3_l',
    shortest: 0.877615,
    longest: 1.26121,
    crosses:
      't3_t4/flexion, t3_t4/lateral_bending_right, t3_t4/axial_rotation_left, costovertebral_3_l/elevation, costovertebral_4_l/elevation',
  },
  {
    unit: 'external_intercostal_4_l',
    shortest: 0.86607,
    longest: 1.27207,
    crosses:
      't4_t5/flexion, t4_t5/lateral_bending_right, t4_t5/axial_rotation_left, costovertebral_4_l/elevation, costovertebral_5_l/elevation',
  },
  {
    unit: 'external_intercostal_5_l',
    shortest: 0.8445,
    longest: 1.44007,
    crosses:
      't5_t6/flexion, t5_t6/lateral_bending_right, t5_t6/axial_rotation_left, costovertebral_5_l/elevation, costovertebral_6_l/elevation',
  },
  {
    unit: 'external_intercostal_6_l',
    shortest: 0.844393,
    longest: 1.46232,
    crosses:
      't6_t7/flexion, t6_t7/lateral_bending_right, t6_t7/axial_rotation_left, costovertebral_6_l/elevation, costovertebral_7_l/elevation',
  },
  {
    unit: 'external_intercostal_7_l',
    shortest: 0.847244,
    longest: 1.46189,
    crosses:
      't7_t8/flexion, t7_t8/lateral_bending_right, t7_t8/axial_rotation_left, costovertebral_7_l/elevation, costovertebral_8_l/elevation',
  },
  {
    unit: 'external_intercostal_8_l',
    shortest: 0.77659,
    longest: 1.387,
    crosses:
      't8_t9/flexion, t8_t9/lateral_bending_right, t8_t9/axial_rotation_left, costovertebral_8_l/elevation, costovertebral_9_l/elevation',
  },
  {
    unit: 'external_intercostal_9_l',
    shortest: 0.854349,
    longest: 1.35942,
    crosses:
      't9_t10/flexion, t9_t10/lateral_bending_right, t9_t10/axial_rotation_left, costovertebral_9_l/elevation, costovertebral_10_l/elevation',
  },
  {
    unit: 'external_intercostal_10_l',
    shortest: 0.809996,
    longest: 1.47327,
    crosses:
      't10_t11/flexion, t10_t11/lateral_bending_right, t10_t11/axial_rotation_left, costovertebral_10_l/elevation, costovertebral_11_l/elevation',
  },
  {
    unit: 'external_intercostal_11_l',
    shortest: 0.765347,
    longest: 1.25692,
    crosses:
      't11_t12/flexion, t11_t12/lateral_bending_right, t11_t12/axial_rotation_left, costovertebral_11_l/elevation, costovertebral_12_l/elevation',
  },
  {
    unit: 'internal_intercostal_1_l',
    shortest: 0.706743,
    longest: 1.30172,
    crosses:
      't1_t2/flexion, t1_t2/lateral_bending_right, t1_t2/axial_rotation_left, costovertebral_1_l/elevation, costovertebral_2_l/elevation',
  },
  {
    unit: 'internal_intercostal_2_l',
    shortest: 0.586251,
    longest: 1.4055,
    crosses:
      't2_t3/flexion, t2_t3/lateral_bending_right, t2_t3/axial_rotation_left, costovertebral_2_l/elevation, costovertebral_3_l/elevation',
  },
  {
    unit: 'internal_intercostal_3_l',
    shortest: 0.501128,
    longest: 1.49359,
    crosses:
      't3_t4/flexion, t3_t4/lateral_bending_right, t3_t4/axial_rotation_left, costovertebral_3_l/elevation, costovertebral_4_l/elevation',
  },
  {
    unit: 'internal_intercostal_4_l',
    shortest: 0.223185,
    longest: 1.9448,
    crosses:
      't4_t5/flexion, t4_t5/lateral_bending_right, t4_t5/axial_rotation_left, costovertebral_4_l/elevation, costovertebral_5_l/elevation',
  },
  {
    unit: 'internal_intercostal_5_l',
    shortest: 0.365521,
    longest: 1.74358,
    crosses:
      't5_t6/flexion, t5_t6/lateral_bending_right, t5_t6/axial_rotation_left, costovertebral_5_l/elevation, costovertebral_6_l/elevation',
  },
  {
    unit: 'internal_intercostal_6_l',
    shortest: 0.474019,
    longest: 1.71531,
    crosses:
      't6_t7/flexion, t6_t7/lateral_bending_right, t6_t7/axial_rotation_left, costovertebral_6_l/elevation, costovertebral_7_l/elevation',
  },
  {
    unit: 'internal_intercostal_7_l',
    shortest: 0.683712,
    longest: 1.78512,
    crosses:
      't7_t8/flexion, t7_t8/lateral_bending_right, t7_t8/axial_rotation_left, costovertebral_7_l/elevation, costovertebral_8_l/elevation',
  },
  {
    unit: 'internal_intercostal_8_l',
    shortest: 0.545123,
    longest: 1.64545,
    crosses:
      't8_t9/flexion, t8_t9/lateral_bending_right, t8_t9/axial_rotation_left, costovertebral_8_l/elevation, costovertebral_9_l/elevation',
  },
  {
    unit: 'internal_intercostal_9_l',
    shortest: 0.710836,
    longest: 1.79678,
    crosses:
      't9_t10/flexion, t9_t10/lateral_bending_right, t9_t10/axial_rotation_left, costovertebral_9_l/elevation, costovertebral_10_l/elevation',
  },
  {
    unit: 'internal_intercostal_10_l',
    shortest: 0.888784,
    longest: 1.53795,
    crosses:
      't10_t11/flexion, t10_t11/lateral_bending_right, t10_t11/axial_rotation_left, costovertebral_10_l/elevation, costovertebral_11_l/elevation',
  },
  {
    unit: 'internal_intercostal_11_l',
    shortest: 0.872918,
    longest: 1.26287,
    crosses:
      't11_t12/flexion, t11_t12/lateral_bending_right, t11_t12/axial_rotation_left, costovertebral_11_l/elevation, costovertebral_12_l/elevation',
  },
];

/** One unit's range, or undefined for a unit nothing has measured. */
export function muscleLengthRange(unit: string): MuscleLengthRange | undefined {
  return MUSCLE_LENGTH_RANGES.find((r) => r.unit === unit);
}
