/**
 * The shoulder muscle parameter set -- ticket N2.5, the region after the elbow.
 *
 * **Generated by `pnpm generate:shoulder-muscles`. Do not edit.** The numbers are extracted from
 * the vendored MyoSuite arm model rather than copied out of it, so the value here and the value
 * in the cited file cannot disagree; CI runs the generator with `--check`.
 *
 * ## Where each half comes from
 *
 * The same split as the elbow set, and for the same reason. *Where a muscle attaches* is ours:
 * Gray's anatomical statement located on this subject by the dataset's own markers, in this
 * project's bone frames. *What a muscle can do* is MyoSuite's: peak force, optimal fiber length
 * and tendon slack length are scalars, so they cross frames without reinterpretation.
 *
 * ## Nine units
 *
 * The three heads of deltoid, the four of the rotator cuff, teres major and coracobrachialis --
 * every muscle running from the shoulder girdle to the humerus. Pectoralis major and latissimus
 * dorsi run from the trunk and are their own set.
 *
 * Coracobrachialis was absent for four commits. Its actuator states an operating range and a
 * length range implying a 312 mm fiber on a tendon 45 mm shorter than nothing, and the guard
 * refused it -- until OQ-023 observed that those two come from different halves of the same
 * arithmetic, the fiber from the *width* of the two ranges and the tendon from the *offset*, and
 * that only the offset is contradictory. The tendon is refitted to this skeleton at compile
 * anyway, and the fiber is capped there at a share of its own path, which takes 312 mm down to
 * 135 -- which is a coracobrachialis.
 *
 * ## No wrap surface
 *
 * These paths are held by via points alone. The head of the humerus is in the skeleton as a
 * measured sphere and was tried here first, and every unit came off it again: swept through
 * twenty-four shoulder poses, half never touched it and half touched it between a fifth and two
 * fifths of the time. A wrap that comes and goes changes a path by centimetres from one tick to
 * the next, and a tendon that stiff turns that into kilonewtons -- the arm twitches and its
 * rotation flips.
 *
 * The anatomy agrees with the measurement. The cuff inserts *on* the head, at the tubercles,
 * barely outside it: those muscles lie against the head and attach rather than turning over it,
 * and their leverage is where the tubercle stands rather than a radius.
 */

import { cite } from '@bs-humany/hsdl';
import type { MuscleGroup } from './schema.js';

/** Anatomy: which bony feature a muscle attaches to. The sites themselves are cited in M5.3. */
const gray = (muscle: string) => cite('gray1918', `Part IV, Myology: The ${muscle}`);

/** Parameters: the actuator in the vendored arm model they were derived from. */
const myoArm = (actuator: string) =>
  cite(
    'caggiano2022',
    `myoarm_r_muscle.xml, actuator general name="${actuator}": gainprm force, and optimal fiber ` +
      'length and tendon slack length derived from gainprm range with lengthrange',
  );

export const SHOULDER_MUSCLES: readonly MuscleGroup[] = [
  {
    id: 'deltoid_r',
    displayName: 'Deltoid, right',
    taTerm: 'Musculus deltoideus',
    innervation: 'Axillary nerve',
    source: gray('Deltoid'),
    units: [
      {
        id: 'deltoid_anterior_r',
        displayName: 'Deltoid, anterior part, right',
        origin: 'deltoid_origin_r_acromial_end',
        insertion: 'deltoid_insertion_r_deltoid_tuberosity',
        path: [
          { kind: 'site', site: 'deltoid_anterior_r__via_1' },
          { kind: 'site', site: 'deltoid_anterior_r__via_2' },
        ],
        parameters: {
          maxIsometricForce: 1051.85,
          optimalFiberLength: 0.0982861,
          tendonSlackLength: 0.0902337,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoArm('DELT1'),
        },
      },
      {
        id: 'deltoid_middle_r',
        displayName: 'Deltoid, middle part, right',
        origin: 'deltoid_origin_r_acromion',
        insertion: 'deltoid_insertion_r_deltoid_tuberosity',
        path: [
          { kind: 'site', site: 'deltoid_middle_r__via_1' },
          { kind: 'site', site: 'deltoid_middle_r__via_2' },
        ],
        parameters: {
          maxIsometricForce: 909.342,
          optimalFiberLength: 0.0491894,
          tendonSlackLength: 0.144417,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoArm('DELT2'),
        },
      },
      {
        id: 'deltoid_posterior_r',
        displayName: 'Deltoid, posterior part, right',
        origin: 'deltoid_origin_r_spine_of_scapula',
        insertion: 'deltoid_insertion_r_deltoid_tuberosity',
        path: [{ kind: 'site', site: 'deltoid_posterior_r__via_1' }],
        parameters: {
          maxIsometricForce: 163.23,
          optimalFiberLength: 0.11111,
          tendonSlackLength: 0.0438739,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoArm('DELT3'),
        },
      },
    ],
  },
  {
    id: 'supraspinatus_r',
    displayName: 'Supraspinatus, right',
    taTerm: 'Musculus supraspinatus',
    innervation: 'Suprascapular nerve',
    source: gray('Supraspinatus'),
    units: [
      {
        id: 'supraspinatus_r',
        displayName: 'Supraspinatus, right',
        origin: 'supraspinatus_origin_r_supraspinous_fossa',
        insertion: 'supraspinatus_insertion_r_greater_tubercle',
        path: [{ kind: 'site', site: 'supraspinatus_r__via_1' }],
        parameters: {
          maxIsometricForce: 339.132,
          optimalFiberLength: 0.0895907,
          tendonSlackLength: 0.0121942,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoArm('SUPSP'),
        },
      },
    ],
  },
  {
    id: 'infraspinatus_r',
    displayName: 'Infraspinatus, right',
    taTerm: 'Musculus infraspinatus',
    innervation: 'Suprascapular nerve',
    source: gray('Infraspinatus'),
    units: [
      {
        id: 'infraspinatus_r',
        displayName: 'Infraspinatus, right',
        origin: 'infraspinatus_origin_r_infraspinous_fossa',
        insertion: 'infraspinatus_insertion_r_greater_tubercle',
        path: [{ kind: 'site', site: 'infraspinatus_r__via_1' }],
        parameters: {
          maxIsometricForce: 2150.71,
          optimalFiberLength: 0.102288,
          tendonSlackLength: 0.00465503,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoArm('INFSP'),
        },
      },
    ],
  },
  {
    id: 'subscapularis_r',
    displayName: 'Subscapularis, right',
    taTerm: 'Musculus subscapularis',
    innervation: 'Subscapular nerves',
    source: gray('Subscapularis'),
    units: [
      {
        id: 'subscapularis_r',
        displayName: 'Subscapularis, right',
        origin: 'subscapularis_origin_r_subscapular_fossa',
        insertion: 'subscapularis_insertion_r_lesser_tubercle',
        path: [{ kind: 'site', site: 'subscapularis_r__via_1' }],
        parameters: {
          maxIsometricForce: 1174.3,
          optimalFiberLength: 0.0769059,
          tendonSlackLength: 0.0334929,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoArm('SUBSC'),
        },
      },
    ],
  },
  {
    id: 'teres_minor_r',
    displayName: 'Teres minor, right',
    taTerm: 'Musculus teres minor',
    innervation: 'Axillary nerve',
    source: gray('Teres minor'),
    units: [
      {
        id: 'teres_minor_r',
        displayName: 'Teres minor, right',
        origin: 'teres_minor_origin_r_lateral_border_of_scapula',
        insertion: 'teres_minor_insertion_r_greater_tubercle',
        path: [{ kind: 'site', site: 'teres_minor_r__via_1' }],
        parameters: {
          maxIsometricForce: 539,
          optimalFiberLength: 0.137461,
          tendonSlackLength: 0.00663145,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoArm('TMIN'),
        },
      },
    ],
  },
  {
    id: 'teres_major_r',
    displayName: 'Teres major, right',
    taTerm: 'Musculus teres major',
    innervation: 'Lower subscapular nerve',
    source: gray('Teres major'),
    units: [
      {
        id: 'teres_major_r',
        displayName: 'Teres major, right',
        origin: 'teres_major_origin_r_inferior_angle_of_scapula',
        insertion: 'teres_major_insertion_r_crest_of_lesser_tubercle',
        path: [
          { kind: 'site', site: 'teres_major_r__via_1' },
          { kind: 'site', site: 'teres_major_r__via_2' },
        ],
        parameters: {
          maxIsometricForce: 288,
          optimalFiberLength: 0.133105,
          tendonSlackLength: 0.0694789,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoArm('TMAJ'),
        },
      },
    ],
  },
  {
    id: 'coracobrachialis_r',
    displayName: 'Coracobrachialis, right',
    taTerm: 'Musculus coracobrachialis',
    innervation: 'Musculocutaneous nerve',
    source: gray('Coracobrachialis'),
    units: [
      {
        id: 'coracobrachialis_r',
        displayName: 'Coracobrachialis, right',
        origin: 'coracobrachialis_origin_r_coracoid_process',
        insertion: 'coracobrachialis_insertion_r_medial_border_of_humerus',
        path: [],
        parameters: {
          maxIsometricForce: 172.994,
          optimalFiberLength: 0.311743,
          tendonSlackLength: -0.0449091,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoArm('CORB'),
        },
      },
    ],
  },
  {
    id: 'deltoid_l',
    displayName: 'Deltoid, left',
    taTerm: 'Musculus deltoideus',
    innervation: 'Axillary nerve',
    source: gray('Deltoid'),
    units: [
      {
        id: 'deltoid_anterior_l',
        displayName: 'Deltoid, anterior part, left',
        origin: 'deltoid_origin_l_acromial_end',
        insertion: 'deltoid_insertion_l_deltoid_tuberosity',
        path: [
          { kind: 'site', site: 'deltoid_anterior_l__via_1' },
          { kind: 'site', site: 'deltoid_anterior_l__via_2' },
        ],
        parameters: {
          maxIsometricForce: 1051.85,
          optimalFiberLength: 0.0982861,
          tendonSlackLength: 0.0902337,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoArm('DELT1'),
        },
      },
      {
        id: 'deltoid_middle_l',
        displayName: 'Deltoid, middle part, left',
        origin: 'deltoid_origin_l_acromion',
        insertion: 'deltoid_insertion_l_deltoid_tuberosity',
        path: [
          { kind: 'site', site: 'deltoid_middle_l__via_1' },
          { kind: 'site', site: 'deltoid_middle_l__via_2' },
        ],
        parameters: {
          maxIsometricForce: 909.342,
          optimalFiberLength: 0.0491894,
          tendonSlackLength: 0.144417,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoArm('DELT2'),
        },
      },
      {
        id: 'deltoid_posterior_l',
        displayName: 'Deltoid, posterior part, left',
        origin: 'deltoid_origin_l_spine_of_scapula',
        insertion: 'deltoid_insertion_l_deltoid_tuberosity',
        path: [{ kind: 'site', site: 'deltoid_posterior_l__via_1' }],
        parameters: {
          maxIsometricForce: 163.23,
          optimalFiberLength: 0.11111,
          tendonSlackLength: 0.0438739,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoArm('DELT3'),
        },
      },
    ],
  },
  {
    id: 'supraspinatus_l',
    displayName: 'Supraspinatus, left',
    taTerm: 'Musculus supraspinatus',
    innervation: 'Suprascapular nerve',
    source: gray('Supraspinatus'),
    units: [
      {
        id: 'supraspinatus_l',
        displayName: 'Supraspinatus, left',
        origin: 'supraspinatus_origin_l_supraspinous_fossa',
        insertion: 'supraspinatus_insertion_l_greater_tubercle',
        path: [{ kind: 'site', site: 'supraspinatus_l__via_1' }],
        parameters: {
          maxIsometricForce: 339.132,
          optimalFiberLength: 0.0895907,
          tendonSlackLength: 0.0121942,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoArm('SUPSP'),
        },
      },
    ],
  },
  {
    id: 'infraspinatus_l',
    displayName: 'Infraspinatus, left',
    taTerm: 'Musculus infraspinatus',
    innervation: 'Suprascapular nerve',
    source: gray('Infraspinatus'),
    units: [
      {
        id: 'infraspinatus_l',
        displayName: 'Infraspinatus, left',
        origin: 'infraspinatus_origin_l_infraspinous_fossa',
        insertion: 'infraspinatus_insertion_l_greater_tubercle',
        path: [{ kind: 'site', site: 'infraspinatus_l__via_1' }],
        parameters: {
          maxIsometricForce: 2150.71,
          optimalFiberLength: 0.102288,
          tendonSlackLength: 0.00465503,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoArm('INFSP'),
        },
      },
    ],
  },
  {
    id: 'subscapularis_l',
    displayName: 'Subscapularis, left',
    taTerm: 'Musculus subscapularis',
    innervation: 'Subscapular nerves',
    source: gray('Subscapularis'),
    units: [
      {
        id: 'subscapularis_l',
        displayName: 'Subscapularis, left',
        origin: 'subscapularis_origin_l_subscapular_fossa',
        insertion: 'subscapularis_insertion_l_lesser_tubercle',
        path: [{ kind: 'site', site: 'subscapularis_l__via_1' }],
        parameters: {
          maxIsometricForce: 1174.3,
          optimalFiberLength: 0.0769059,
          tendonSlackLength: 0.0334929,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoArm('SUBSC'),
        },
      },
    ],
  },
  {
    id: 'teres_minor_l',
    displayName: 'Teres minor, left',
    taTerm: 'Musculus teres minor',
    innervation: 'Axillary nerve',
    source: gray('Teres minor'),
    units: [
      {
        id: 'teres_minor_l',
        displayName: 'Teres minor, left',
        origin: 'teres_minor_origin_l_lateral_border_of_scapula',
        insertion: 'teres_minor_insertion_l_greater_tubercle',
        path: [{ kind: 'site', site: 'teres_minor_l__via_1' }],
        parameters: {
          maxIsometricForce: 539,
          optimalFiberLength: 0.137461,
          tendonSlackLength: 0.00663145,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoArm('TMIN'),
        },
      },
    ],
  },
  {
    id: 'teres_major_l',
    displayName: 'Teres major, left',
    taTerm: 'Musculus teres major',
    innervation: 'Lower subscapular nerve',
    source: gray('Teres major'),
    units: [
      {
        id: 'teres_major_l',
        displayName: 'Teres major, left',
        origin: 'teres_major_origin_l_inferior_angle_of_scapula',
        insertion: 'teres_major_insertion_l_crest_of_lesser_tubercle',
        path: [
          { kind: 'site', site: 'teres_major_l__via_1' },
          { kind: 'site', site: 'teres_major_l__via_2' },
        ],
        parameters: {
          maxIsometricForce: 288,
          optimalFiberLength: 0.133105,
          tendonSlackLength: 0.0694789,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoArm('TMAJ'),
        },
      },
    ],
  },
  {
    id: 'coracobrachialis_l',
    displayName: 'Coracobrachialis, left',
    taTerm: 'Musculus coracobrachialis',
    innervation: 'Musculocutaneous nerve',
    source: gray('Coracobrachialis'),
    units: [
      {
        id: 'coracobrachialis_l',
        displayName: 'Coracobrachialis, left',
        origin: 'coracobrachialis_origin_l_coracoid_process',
        insertion: 'coracobrachialis_insertion_l_medial_border_of_humerus',
        path: [],
        parameters: {
          maxIsometricForce: 172.994,
          optimalFiberLength: 0.311743,
          tendonSlackLength: -0.0449091,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoArm('CORB'),
        },
      },
    ],
  },
];

/** Every unit in the set, flattened, in a stable order. */
export const SHOULDER_UNITS = SHOULDER_MUSCLES.flatMap((group) => group.units);
