/**
 * How far each muscle travels on the model its parameters came from, and where that puts it.
 *
 * **Generated by `pnpm measure:source-travel`. Do not edit.**
 *
 * Measured by running the vendored MyoSuite models and sweeping each coordinate a tendon crosses
 * through that model's own range, one at a time with the others at neutral -- the same method
 * `MUSCLE_LENGTH_RANGES` uses on this skeleton, so the two are comparable.
 *
 * What it is for is optimal fiber length, which is architecture: how long a muscle's fibers are
 * against the distance it has to cover. Transcribed onto different bones that number stops saying
 * what it said, because the distance changed. `deriveOptimalFiberLength` carries across the ratio
 * the source chose rather than the length itself -- see OQ-020.
 *
 * `low` and `high` are where the source runs the muscle on its own force-length curve, in units
 * of its optimal fiber length. They are not used to fit anything; they are here because they are
 * the evidence for whether a unit's parameters and its geometry agree in the model they came
 * from, and several of them plainly do not: the source works its own biceps femoris long head
 * between 0.27 and 1.78 of optimal, which no fiber does.
 *
 * Neither model has a left side. Both sides of ours carry the same muscle, so each row is
 * repeated for the left.
 *
 * Every number here is measured on the vendored MyoSuite models -- the same files, at the same
 * pinned commit, that the parameter sets are extracted from.
 */

import { cite } from '@bs-humany/hsdl';

/** Where these measurements come from: the models, run rather than read. */
export const SOURCE_TRAVEL_SOURCE = cite(
  'caggiano2022',
  'myoarm_r_tendon.xml and myolegs_tendon.xml, tendon lengths swept over the joint ranges ' +
    'stated in myoarm_r_chain.xml and myolegs_chain.xml',
);

export interface SourceMuscleTravel {
  readonly unit: string;
  /** Metres, on the source's skeleton, over the source's own joint ranges. */
  readonly travel: number;
  /** Shortest the source's fibers get over that travel, in units of its optimal fiber length. */
  readonly low: number;
  /** Longest they get, likewise. */
  readonly high: number;
}

export const SOURCE_MUSCLE_TRAVEL: readonly SourceMuscleTravel[] = [
  {
    unit: 'biceps_brachii_long_r',
    travel: 0.0850722,
    low: 0.71083,
    high: 1.37965,
  },
  {
    unit: 'biceps_brachii_long_l',
    travel: 0.0850722,
    low: 0.71083,
    high: 1.37965,
  },
  {
    unit: 'biceps_brachii_short_r',
    travel: 0.128003,
    low: 0.625354,
    high: 1.34665,
  },
  {
    unit: 'biceps_brachii_short_l',
    travel: 0.128003,
    low: 0.625354,
    high: 1.34665,
  },
  {
    unit: 'biceps_femoris_long_r',
    travel: 0.184757,
    low: 0.265601,
    high: 1.78154,
  },
  {
    unit: 'biceps_femoris_long_l',
    travel: 0.184757,
    low: 0.265601,
    high: 1.78154,
  },
  {
    unit: 'biceps_femoris_short_r',
    travel: 0.0838545,
    low: 0.459145,
    high: 1.21939,
  },
  {
    unit: 'biceps_femoris_short_l',
    travel: 0.0838545,
    low: 0.459145,
    high: 1.21939,
  },
  {
    unit: 'brachialis_r',
    travel: 0.0364767,
    low: 0.526156,
    high: 1.15917,
  },
  {
    unit: 'brachialis_l',
    travel: 0.0364767,
    low: 0.526156,
    high: 1.15917,
  },
  {
    unit: 'brachioradialis_r',
    travel: 0.129683,
    low: 0.144696,
    high: 1.41639,
  },
  {
    unit: 'brachioradialis_l',
    travel: 0.129683,
    low: 0.144696,
    high: 1.41639,
  },
  {
    unit: 'deltoid_anterior_r',
    travel: 0.0461521,
    low: 0.943812,
    high: 1.41338,
  },
  {
    unit: 'deltoid_anterior_l',
    travel: 0.0461521,
    low: 0.943812,
    high: 1.41338,
  },
  {
    unit: 'deltoid_middle_r',
    travel: 0.0592173,
    low: 0.162982,
    high: 1.36685,
  },
  {
    unit: 'deltoid_middle_l',
    travel: 0.0592173,
    low: 0.162982,
    high: 1.36685,
  },
  {
    unit: 'deltoid_posterior_r',
    travel: 0.0313225,
    low: 0.778298,
    high: 1.0602,
  },
  {
    unit: 'deltoid_posterior_l',
    travel: 0.0313225,
    low: 0.778298,
    high: 1.0602,
  },
  {
    unit: 'gastrocnemius_lateral_r',
    travel: 0.0556193,
    low: 0.794393,
    high: 1.58827,
  },
  {
    unit: 'gastrocnemius_lateral_l',
    travel: 0.0556193,
    low: 0.794393,
    high: 1.58827,
  },
  {
    unit: 'gastrocnemius_medial_r',
    travel: 0.0686399,
    low: 0.656235,
    high: 1.57644,
  },
  {
    unit: 'gastrocnemius_medial_l',
    travel: 0.0686399,
    low: 0.656235,
    high: 1.57644,
  },
  {
    unit: 'infraspinatus_r',
    travel: 0.0483095,
    low: 0.633001,
    high: 1.10529,
  },
  {
    unit: 'infraspinatus_l',
    travel: 0.0483095,
    low: 0.633001,
    high: 1.10529,
  },
  {
    unit: 'rectus_femoris_r',
    travel: 0.192747,
    low: 0.60046,
    high: 1.72934,
  },
  {
    unit: 'rectus_femoris_l',
    travel: 0.192747,
    low: 0.60046,
    high: 1.72934,
  },
  {
    unit: 'semimembranosus_r',
    travel: 0.175742,
    low: 0.321181,
    high: 1.77744,
  },
  {
    unit: 'semimembranosus_l',
    travel: 0.175742,
    low: 0.321181,
    high: 1.77744,
  },
  {
    unit: 'semitendinosus_r',
    travel: 0.21324,
    low: 0.546441,
    high: 1.65131,
  },
  {
    unit: 'semitendinosus_l',
    travel: 0.21324,
    low: 0.546441,
    high: 1.65131,
  },
  {
    unit: 'subscapularis_r',
    travel: 0.0366168,
    low: 0.862879,
    high: 1.339,
  },
  {
    unit: 'subscapularis_l',
    travel: 0.0366168,
    low: 0.862879,
    high: 1.339,
  },
  {
    unit: 'supraspinatus_r',
    travel: 0.0484639,
    low: 0.917603,
    high: 1.45855,
  },
  {
    unit: 'supraspinatus_l',
    travel: 0.0484639,
    low: 0.917603,
    high: 1.45855,
  },
  {
    unit: 'teres_major_r',
    travel: 0.0860472,
    low: 0.577347,
    high: 1.22381,
  },
  {
    unit: 'teres_major_l',
    travel: 0.0860472,
    low: 0.577347,
    high: 1.22381,
  },
  {
    unit: 'teres_minor_r',
    travel: 0.042077,
    low: 0.627878,
    high: 0.933979,
  },
  {
    unit: 'teres_minor_l',
    travel: 0.042077,
    low: 0.627878,
    high: 0.933979,
  },
  {
    unit: 'triceps_brachii_lateral_r',
    travel: 0.0424257,
    low: 0.538328,
    high: 1.20539,
  },
  {
    unit: 'triceps_brachii_lateral_l',
    travel: 0.0424257,
    low: 0.538328,
    high: 1.20539,
  },
  {
    unit: 'triceps_brachii_long_r',
    travel: 0.0745828,
    low: 0.903708,
    high: 1.3201,
  },
  {
    unit: 'triceps_brachii_long_l',
    travel: 0.0745828,
    low: 0.903708,
    high: 1.3201,
  },
  {
    unit: 'triceps_brachii_medial_r',
    travel: 0.0424257,
    low: 0.445244,
    high: 1.27121,
  },
  {
    unit: 'triceps_brachii_medial_l',
    travel: 0.0424257,
    low: 0.445244,
    high: 1.27121,
  },
  {
    unit: 'vastus_intermedius_r',
    travel: 0.0682236,
    low: 0.78566,
    high: 1.17999,
  },
  {
    unit: 'vastus_intermedius_l',
    travel: 0.0682236,
    low: 0.78566,
    high: 1.17999,
  },
  {
    unit: 'vastus_lateralis_r',
    travel: 0.064843,
    low: 0.725701,
    high: 1.10138,
  },
  {
    unit: 'vastus_lateralis_l',
    travel: 0.064843,
    low: 0.725701,
    high: 1.10138,
  },
  {
    unit: 'vastus_medialis_r',
    travel: 0.0639566,
    low: 0.68858,
    high: 1.34931,
  },
  {
    unit: 'vastus_medialis_l',
    travel: 0.0639566,
    low: 0.68858,
    high: 1.34931,
  },
];

/** One unit's source travel, or undefined for a unit that came from somewhere else. */
export function sourceMuscleTravel(unit: string): SourceMuscleTravel | undefined {
  return SOURCE_MUSCLE_TRAVEL.find((r) => r.unit === unit);
}
