/**
 * How far each muscle travels on the model its parameters came from, and where that puts it.
 *
 * **Generated by `pnpm measure:source-travel`. Do not edit.**
 *
 * Measured by running the vendored MyoSuite models and sweeping each coordinate a tendon crosses
 * through that model's own range, one at a time with the others at neutral -- the same method
 * `MUSCLE_LENGTH_RANGES` uses on this skeleton, so the two are comparable.
 *
 * What it is for is optimal fiber length, which is architecture: how long a muscle's fibers are
 * against the distance it has to cover. Transcribed onto different bones that number stops saying
 * what it said, because the distance changed. `deriveOptimalFiberLength` carries across the ratio
 * the source chose rather than the length itself -- see OQ-020.
 *
 * `low` and `high` are where the source runs the muscle on its own force-length curve, in units
 * of its optimal fiber length. They are not used to fit anything; they are here because they are
 * the evidence for whether a unit's parameters and its geometry agree in the model they came
 * from, and several of them plainly do not: the source works its own biceps femoris long head
 * between 0.27 and 1.78 of optimal, which no fiber does.
 *
 * Neither model has a left side. Both sides of ours carry the same muscle, so each row is
 * repeated for the left.
 *
 * Every number here is measured on the vendored MyoSuite models -- the same files, at the same
 * pinned commit, that the parameter sets are extracted from.
 */

import { cite } from '@bs-humany/hsdl';

/** Where these measurements come from: the models, run rather than read. */
export const SOURCE_TRAVEL_SOURCE = cite(
  'caggiano2022',
  'myoarm_r_tendon.xml and myolegs_tendon.xml, tendon lengths swept over the joint ranges ' +
    'stated in myoarm_r_chain.xml and myolegs_chain.xml',
);

export interface SourceMuscleTravel {
  readonly unit: string;
  /** Metres, on the source's skeleton, over the source's own joint ranges. */
  readonly travel: number;
  /** Shortest the source's fibers get over that travel, in units of its optimal fiber length. */
  readonly low: number;
  /** Longest they get, likewise. */
  readonly high: number;
}

export const SOURCE_MUSCLE_TRAVEL: readonly SourceMuscleTravel[] = [
  {
    unit: 'biceps_brachii_long_r',
    travel: 0.0713227,
    low: 0.71083,
    high: 1.27155,
  },
  {
    unit: 'biceps_brachii_long_l',
    travel: 0.0713227,
    low: 0.71083,
    high: 1.27155,
  },
  {
    unit: 'biceps_brachii_short_r',
    travel: 0.119594,
    low: 0.625354,
    high: 1.29927,
  },
  {
    unit: 'biceps_brachii_short_l',
    travel: 0.119594,
    low: 0.625354,
    high: 1.29927,
  },
  {
    unit: 'biceps_femoris_long_r',
    travel: 0.179635,
    low: 0.307632,
    high: 1.78154,
  },
  {
    unit: 'biceps_femoris_long_l',
    travel: 0.179635,
    low: 0.307632,
    high: 1.78154,
  },
  {
    unit: 'biceps_femoris_short_r',
    travel: 0.0755026,
    low: 0.513298,
    high: 1.19782,
  },
  {
    unit: 'biceps_femoris_short_l',
    travel: 0.0755026,
    low: 0.513298,
    high: 1.19782,
  },
  {
    unit: 'brachialis_r',
    travel: 0.0364767,
    low: 0.526156,
    high: 1.15917,
  },
  {
    unit: 'brachialis_l',
    travel: 0.0364767,
    low: 0.526156,
    high: 1.15917,
  },
  {
    unit: 'brachioradialis_r',
    travel: 0.129683,
    low: 0.144696,
    high: 1.41639,
  },
  {
    unit: 'brachioradialis_l',
    travel: 0.129683,
    low: 0.144696,
    high: 1.41639,
  },
  {
    unit: 'deltoid_anterior_r',
    travel: 0.069128,
    low: 0.614152,
    high: 1.31749,
  },
  {
    unit: 'deltoid_anterior_l',
    travel: 0.069128,
    low: 0.614152,
    high: 1.31749,
  },
  {
    unit: 'deltoid_middle_r',
    travel: 0.0449636,
    low: 0.451856,
    high: 1.36595,
  },
  {
    unit: 'deltoid_middle_l',
    travel: 0.0449636,
    low: 0.451856,
    high: 1.36595,
  },
  {
    unit: 'deltoid_posterior_r',
    travel: 0.0389116,
    low: 0.858469,
    high: 1.20868,
  },
  {
    unit: 'deltoid_posterior_l',
    travel: 0.0389116,
    low: 0.858469,
    high: 1.20868,
  },
  {
    unit: 'gastrocnemius_lateral_r',
    travel: 0.0610765,
    low: 0.716499,
    high: 1.58827,
  },
  {
    unit: 'gastrocnemius_lateral_l',
    travel: 0.0610765,
    low: 0.716499,
    high: 1.58827,
  },
  {
    unit: 'gastrocnemius_medial_r',
    travel: 0.0646966,
    low: 0.7091,
    high: 1.57644,
  },
  {
    unit: 'gastrocnemius_medial_l',
    travel: 0.0646966,
    low: 0.7091,
    high: 1.57644,
  },
  {
    unit: 'infraspinatus_r',
    travel: 0.0480683,
    low: 0.635358,
    high: 1.10529,
  },
  {
    unit: 'infraspinatus_l',
    travel: 0.0480683,
    low: 0.635358,
    high: 1.10529,
  },
  {
    unit: 'rectus_femoris_r',
    travel: 0.189632,
    low: 0.618706,
    high: 1.72934,
  },
  {
    unit: 'rectus_femoris_l',
    travel: 0.189632,
    low: 0.618706,
    high: 1.72934,
  },
  {
    unit: 'semimembranosus_r',
    travel: 0.182622,
    low: 0.264175,
    high: 1.77744,
  },
  {
    unit: 'semimembranosus_l',
    travel: 0.182622,
    low: 0.264175,
    high: 1.77744,
  },
  {
    unit: 'semitendinosus_r',
    travel: 0.220824,
    low: 0.507148,
    high: 1.65131,
  },
  {
    unit: 'semitendinosus_l',
    travel: 0.220824,
    low: 0.507148,
    high: 1.65131,
  },
  {
    unit: 'subscapularis_r',
    travel: 0.0381904,
    low: 0.82651,
    high: 1.3231,
  },
  {
    unit: 'subscapularis_l',
    travel: 0.0381904,
    low: 0.82651,
    high: 1.3231,
  },
  {
    unit: 'supraspinatus_r',
    travel: 0.0293475,
    low: 0.991227,
    high: 1.3188,
  },
  {
    unit: 'supraspinatus_l',
    travel: 0.0293475,
    low: 0.991227,
    high: 1.3188,
  },
  {
    unit: 'teres_major_r',
    travel: 0.0822783,
    low: 0.634702,
    high: 1.25285,
  },
  {
    unit: 'teres_major_l',
    travel: 0.0822783,
    low: 0.634702,
    high: 1.25285,
  },
  {
    unit: 'teres_minor_r',
    travel: 0.0455724,
    low: 0.649902,
    high: 0.98143,
  },
  {
    unit: 'teres_minor_l',
    travel: 0.0455724,
    low: 0.649902,
    high: 0.98143,
  },
  {
    unit: 'triceps_brachii_lateral_r',
    travel: 0.0424257,
    low: 0.538328,
    high: 1.20539,
  },
  {
    unit: 'triceps_brachii_lateral_l',
    travel: 0.0424257,
    low: 0.538328,
    high: 1.20539,
  },
  {
    unit: 'triceps_brachii_long_r',
    travel: 0.0712147,
    low: 0.903708,
    high: 1.3013,
  },
  {
    unit: 'triceps_brachii_long_l',
    travel: 0.0712147,
    low: 0.903708,
    high: 1.3013,
  },
  {
    unit: 'triceps_brachii_medial_r',
    travel: 0.0424257,
    low: 0.445244,
    high: 1.27121,
  },
  {
    unit: 'triceps_brachii_medial_l',
    travel: 0.0424257,
    low: 0.445244,
    high: 1.27121,
  },
  {
    unit: 'vastus_intermedius_r',
    travel: 0.0688171,
    low: 0.804137,
    high: 1.2019,
  },
  {
    unit: 'vastus_intermedius_l',
    travel: 0.0688171,
    low: 0.804137,
    high: 1.2019,
  },
  {
    unit: 'vastus_lateralis_r',
    travel: 0.067203,
    low: 0.754638,
    high: 1.14399,
  },
  {
    unit: 'vastus_lateralis_l',
    travel: 0.067203,
    low: 0.754638,
    high: 1.14399,
  },
  {
    unit: 'vastus_medialis_r',
    travel: 0.065879,
    low: 0.725833,
    high: 1.40642,
  },
  {
    unit: 'vastus_medialis_l',
    travel: 0.065879,
    low: 0.725833,
    high: 1.40642,
  },
];

/** One unit's source travel, or undefined for a unit that came from somewhere else. */
export function sourceMuscleTravel(unit: string): SourceMuscleTravel | undefined {
  return SOURCE_MUSCLE_TRAVEL.find((r) => r.unit === unit);
}
