/**
 * The torso muscle parameter set -- the abdominal wall, and a trunk with no extensor.
 *
 * **Generated by `pnpm generate:torso-muscles`. Do not edit.** CI runs the generator with
 * `--check`.
 *
 * The two obliques, which cross: the external runs downward and forward from the ribs to the pubis
 * and the internal upward and forward from the iliac spine to the ribs, and between them they flex
 * the trunk and rotate it.
 *
 * What is missing is erector spinae and rectus abdominis, and the source is why. Both state an
 * operating range and a length range that put the fiber longer than the whole musculotendon --
 * minus 12 mm of tendon for erector spinae and minus 70 for rectus abdominis -- which is the
 * coracobrachialis signature the generator refuses. The reference's detailed lumbar model does not
 * rescue it: 64 of its 210 fascicles pass, unevenly, with multifidus at 6 of 50. So the trunk
 * rotates and flexes and does not extend. OQ-023 records what would change that.
 */

import { cite } from '@bs-humany/hsdl';
import type { MuscleGroup } from './schema.js';

/** Anatomy: which bony feature a muscle attaches to. The sites themselves are cited in M5.3. */
const gray = (muscle: string) => cite('gray1918', `Part IV, Myology: The ${muscle}`);

/** Parameters: the actuator in the vendored torso model they were derived from. */
const myoTorso = (actuator: string) =>
  cite(
    'caggiano2022',
    `myotorso_abdomen_muscle.xml, actuator general name="${actuator}": gainprm force, and optimal fiber ` +
      'length and tendon slack length derived from gainprm range with lengthrange',
  );

export const TORSO_MUSCLES: readonly MuscleGroup[] = [
  {
    id: 'external_oblique_r',
    displayName: 'Obliquus externus abdominis, right',
    taTerm: 'Musculus obliquus externus abdominis',
    innervation: 'Intercostal nerves T7 to T11, subcostal, iliohypogastric and ilioinguinal',
    source: gray('Obliquus externus abdominis'),
    units: [
      {
        id: 'external_oblique_r',
        displayName: 'External oblique, right',
        origin: 'external_oblique_origin_r_body_of_rib',
        insertion: 'external_oblique_insertion_r_pubic_tubercle',
        path: [],
        parameters: {
          maxIsometricForce: 854.402,
          optimalFiberLength: 0.287806,
          tendonSlackLength: 0.0156325,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoTorso('extobl_r'),
        },
      },
    ],
  },
  {
    id: 'internal_oblique_r',
    displayName: 'Obliquus internus abdominis, right',
    taTerm: 'Musculus obliquus internus abdominis',
    innervation: 'Intercostal nerves T7 to T11, subcostal, iliohypogastric and ilioinguinal',
    source: gray('Obliquus internus abdominis'),
    units: [
      {
        id: 'internal_oblique_r',
        displayName: 'Internal oblique, right',
        origin: 'internal_oblique_origin_r_anterior_superior_iliac_spine',
        insertion: 'internal_oblique_insertion_r_body_of_rib',
        path: [],
        parameters: {
          maxIsometricForce: 1353.01,
          optimalFiberLength: 0.185365,
          tendonSlackLength: 0.00956715,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoTorso('intobl_r'),
        },
      },
    ],
  },
  {
    id: 'external_oblique_l',
    displayName: 'Obliquus externus abdominis, left',
    taTerm: 'Musculus obliquus externus abdominis',
    innervation: 'Intercostal nerves T7 to T11, subcostal, iliohypogastric and ilioinguinal',
    source: gray('Obliquus externus abdominis'),
    units: [
      {
        id: 'external_oblique_l',
        displayName: 'External oblique, left',
        origin: 'external_oblique_origin_l_body_of_rib',
        insertion: 'external_oblique_insertion_l_pubic_tubercle',
        path: [],
        parameters: {
          maxIsometricForce: 852.951,
          optimalFiberLength: 0.272474,
          tendonSlackLength: 0.0156627,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoTorso('extobl_l'),
        },
      },
    ],
  },
  {
    id: 'internal_oblique_l',
    displayName: 'Obliquus internus abdominis, left',
    taTerm: 'Musculus obliquus internus abdominis',
    innervation: 'Intercostal nerves T7 to T11, subcostal, iliohypogastric and ilioinguinal',
    source: gray('Obliquus internus abdominis'),
    units: [
      {
        id: 'internal_oblique_l',
        displayName: 'Internal oblique, left',
        origin: 'internal_oblique_origin_l_anterior_superior_iliac_spine',
        insertion: 'internal_oblique_insertion_l_body_of_rib',
        path: [],
        parameters: {
          maxIsometricForce: 1255.29,
          optimalFiberLength: 0.189821,
          tendonSlackLength: 0.00243725,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoTorso('intobl_l'),
        },
      },
    ],
  },
];

/** Every unit in the set, flattened, in a stable order. */
export const TORSO_UNITS = TORSO_MUSCLES.flatMap((group) => group.units);
