/**
 * The torso muscle parameter set -- the abdominal wall, and a trunk with no extensor.
 *
 * **Generated by `pnpm generate:torso-muscles`. Do not edit.** CI runs the generator with
 * `--check`.
 *
 * Erector spinae behind, rectus abdominis in front, and the two obliques crossing between them --
 * the external running downward and forward from the ribs to the pubis and the internal upward
 * and forward from the iliac spine to the ribs. The trunk flexes, extends and rotates.
 *
 * Erector spinae and rectus abdominis both state a tendon shorter than nothing, which refused them
 * until OQ-023: the fiber length comes from the width of the two ranges and the tendon from the
 * offset, and only the offset is contradictory. The tendon is refitted here regardless.
 */

import { cite } from '@bs-humany/hsdl';
import type { MuscleGroup } from './schema.js';

/** Anatomy: which bony feature a muscle attaches to. The sites themselves are cited in M5.3. */
const gray = (muscle: string) => cite('gray1918', `Part IV, Myology: The ${muscle}`);

/** Parameters: the actuator in the vendored torso model they were derived from. */
const myoTorso = (actuator: string) =>
  cite(
    'caggiano2022',
    `myotorso_abdomen_muscle.xml, actuator general name="${actuator}": gainprm force, and optimal fiber ` +
      'length and tendon slack length derived from gainprm range with lengthrange',
  );

/** The two the abdomen model does not carry come from the detailed one instead. */
const myoTorsoLumbar = (actuator: string) =>
  cite(
    'caggiano2022',
    `myotorso_muscle.xml, actuator general name="${actuator}": gainprm force, and optimal ` +
      'fiber length and tendon slack length derived from gainprm range with lengthrange',
  );

export const TORSO_MUSCLES: readonly MuscleGroup[] = [
  {
    id: 'erector_spinae_r',
    displayName: 'Sacrospinalis (erector spinae), right',
    taTerm: 'Musculus erector spinae',
    innervation: 'Dorsal rami of the spinal nerves',
    source: gray('Sacrospinalis (erector spinae)'),
    units: [
      {
        id: 'erector_spinae_r',
        displayName: 'Erector spinae, right',
        origin: 'erector_spinae_origin_r_dorsal_surface_of_sacrum',
        insertion: 'erector_spinae_insertion_r_angle_of_rib',
        path: [
          { kind: 'site', site: 'erector_spinae_insertion_r_spinous_process' },
          { kind: 'site', site: 'erector_spinae_insertion_r_spinous_process_tip' },
        ],
        parameters: {
          maxIsometricForce: 2481.1,
          optimalFiberLength: 0.180453,
          tendonSlackLength: -0.01204,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoTorso('ercspn_r'),
        },
      },
    ],
  },
  {
    id: 'rectus_abdominis_r',
    displayName: 'Rectus abdominis, right',
    taTerm: 'Musculus rectus abdominis',
    innervation: 'Intercostal nerves T7 to T11 and the subcostal',
    source: gray('Rectus abdominis'),
    units: [
      {
        id: 'rectus_abdominis_r',
        displayName: 'Rectus abdominis, right',
        origin: 'rectus_abdominis_origin_r_pubic_crest',
        insertion: 'rectus_abdominis_insertion_r_xiphoid_tip',
        path: [],
        parameters: {
          maxIsometricForce: 296.805,
          optimalFiberLength: 0.325582,
          tendonSlackLength: -0.0695067,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoTorsoLumbar('rect_abd_r'),
        },
      },
    ],
  },
  {
    id: 'external_oblique_r',
    displayName: 'Obliquus externus abdominis, right',
    taTerm: 'Musculus obliquus externus abdominis',
    innervation: 'Intercostal nerves T7 to T11, subcostal, iliohypogastric and ilioinguinal',
    source: gray('Obliquus externus abdominis'),
    units: [
      {
        id: 'external_oblique_r',
        displayName: 'External oblique, right',
        origin: 'external_oblique_origin_r_body_of_rib',
        insertion: 'external_oblique_insertion_r_pubic_tubercle',
        path: [],
        parameters: {
          maxIsometricForce: 854.402,
          optimalFiberLength: 0.287806,
          tendonSlackLength: 0.0156325,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoTorso('extobl_r'),
        },
      },
    ],
  },
  {
    id: 'internal_oblique_r',
    displayName: 'Obliquus internus abdominis, right',
    taTerm: 'Musculus obliquus internus abdominis',
    innervation: 'Intercostal nerves T7 to T11, subcostal, iliohypogastric and ilioinguinal',
    source: gray('Obliquus internus abdominis'),
    units: [
      {
        id: 'internal_oblique_r',
        displayName: 'Internal oblique, right',
        origin: 'internal_oblique_origin_r_anterior_superior_iliac_spine',
        insertion: 'internal_oblique_insertion_r_body_of_rib',
        path: [],
        parameters: {
          maxIsometricForce: 1353.01,
          optimalFiberLength: 0.185365,
          tendonSlackLength: 0.00956715,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoTorso('intobl_r'),
        },
      },
    ],
  },
  {
    id: 'erector_spinae_l',
    displayName: 'Sacrospinalis (erector spinae), left',
    taTerm: 'Musculus erector spinae',
    innervation: 'Dorsal rami of the spinal nerves',
    source: gray('Sacrospinalis (erector spinae)'),
    units: [
      {
        id: 'erector_spinae_l',
        displayName: 'Erector spinae, left',
        origin: 'erector_spinae_origin_l_dorsal_surface_of_sacrum',
        insertion: 'erector_spinae_insertion_l_angle_of_rib',
        path: [
          { kind: 'site', site: 'erector_spinae_insertion_l_spinous_process' },
          { kind: 'site', site: 'erector_spinae_insertion_l_spinous_process_tip' },
        ],
        parameters: {
          maxIsometricForce: 2435.99,
          optimalFiberLength: 0.165819,
          tendonSlackLength: -0.00540829,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoTorso('ercspn_l'),
        },
      },
    ],
  },
  {
    id: 'rectus_abdominis_l',
    displayName: 'Rectus abdominis, left',
    taTerm: 'Musculus rectus abdominis',
    innervation: 'Intercostal nerves T7 to T11 and the subcostal',
    source: gray('Rectus abdominis'),
    units: [
      {
        id: 'rectus_abdominis_l',
        displayName: 'Rectus abdominis, left',
        origin: 'rectus_abdominis_origin_l_pubic_crest',
        insertion: 'rectus_abdominis_insertion_l_xiphoid_tip',
        path: [],
        parameters: {
          maxIsometricForce: 296.805,
          optimalFiberLength: 0.325582,
          tendonSlackLength: -0.0695067,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoTorsoLumbar('rect_abd_l'),
        },
      },
    ],
  },
  {
    id: 'external_oblique_l',
    displayName: 'Obliquus externus abdominis, left',
    taTerm: 'Musculus obliquus externus abdominis',
    innervation: 'Intercostal nerves T7 to T11, subcostal, iliohypogastric and ilioinguinal',
    source: gray('Obliquus externus abdominis'),
    units: [
      {
        id: 'external_oblique_l',
        displayName: 'External oblique, left',
        origin: 'external_oblique_origin_l_body_of_rib',
        insertion: 'external_oblique_insertion_l_pubic_tubercle',
        path: [],
        parameters: {
          maxIsometricForce: 852.951,
          optimalFiberLength: 0.272474,
          tendonSlackLength: 0.0156627,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoTorso('extobl_l'),
        },
      },
    ],
  },
  {
    id: 'internal_oblique_l',
    displayName: 'Obliquus internus abdominis, left',
    taTerm: 'Musculus obliquus internus abdominis',
    innervation: 'Intercostal nerves T7 to T11, subcostal, iliohypogastric and ilioinguinal',
    source: gray('Obliquus internus abdominis'),
    units: [
      {
        id: 'internal_oblique_l',
        displayName: 'Internal oblique, left',
        origin: 'internal_oblique_origin_l_anterior_superior_iliac_spine',
        insertion: 'internal_oblique_insertion_l_body_of_rib',
        path: [],
        parameters: {
          maxIsometricForce: 1255.29,
          optimalFiberLength: 0.189821,
          tendonSlackLength: 0.00243725,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoTorso('intobl_l'),
        },
      },
    ],
  },
];

/** Every unit in the set, flattened, in a stable order. */
export const TORSO_UNITS = TORSO_MUSCLES.flatMap((group) => group.units);
