/**
 * The back and chest muscle parameter set -- the two that hold the arm onto the trunk.
 *
 * **Generated by `pnpm generate:trunk-muscles`. Do not edit.** The numbers are extracted from the
 * vendored MyoSuite arm model rather than copied out of it, so the value here and the value in the
 * cited file cannot disagree; CI runs the generator with `--check`.
 *
 * ## Where each half comes from
 *
 * The same split as every other set. *Where a muscle attaches* is ours: Gray's anatomical
 * statement located on this subject by the dataset's own markers, which for these two means the
 * thoracic spine, the iliac crest, the sternum and the sixth rib. *What a muscle can do* is
 * MyoSuite's. Both lengths are derived against this skeleton at compile.
 *
 * ## Four parts of six
 *
 * The reference carries three of each and two of those six cannot be used: `LAT2` states an
 * operating range and a length range implying a 395 mm fiber on a tendon 60 mm shorter than
 * nothing, and `PECM1` a 189 mm fiber on one 65 mm shorter. The generator refuses them. What is
 * lost is the middle of latissimus, off the thoracolumbar fascia, and the clavicular head of
 * pectoralis major -- so this pectoralis adducts the arm and pulls it down but does not flex it.
 *
 * ## The trunk end of the reference's paths is not carried
 *
 * MyoArm is an arm, and it anchors these two to its own root rather than to a spine it does not
 * have: their last three path points sit on the model's world body. Ours start where Gray says
 * they start, on bones this skeleton has. What is carried is the arm end -- the point on the
 * scapula that routes latissimus around the back, and the points on the humerus.
 */

import { cite } from '@bs-humany/hsdl';
import type { MuscleGroup } from './schema.js';

/** Anatomy: which bony feature a muscle attaches to. The sites themselves are cited in M5.3. */
const gray = (muscle: string) => cite('gray1918', `Part IV, Myology: The ${muscle}`);

/** Parameters: the actuator in the vendored arm model they were derived from. */
const myoArm = (actuator: string) =>
  cite(
    'caggiano2022',
    `myoarm_r_muscle.xml, actuator general name="${actuator}": gainprm force, and optimal fiber ` +
      'length and tendon slack length derived from gainprm range with lengthrange',
  );

export const TRUNK_MUSCLES: readonly MuscleGroup[] = [
  {
    id: 'latissimus_dorsi_r',
    displayName: 'Latissimus dorsi, right',
    taTerm: 'Musculus latissimus dorsi',
    innervation: 'Thoracodorsal nerve',
    source: gray('Latissimus dorsi'),
    units: [
      {
        id: 'latissimus_dorsi_thoracic_r',
        displayName: 'Latissimus dorsi, thoracic part, right',
        origin: 'latissimus_dorsi_origin_r_spinous_process_tip',
        insertion: 'latissimus_dorsi_insertion_r_intertubercular_sulcus',
        path: [
          { kind: 'site', site: 'latissimus_dorsi_thoracic_r__via_1' },
          { kind: 'site', site: 'latissimus_dorsi_thoracic_r__via_2' },
        ],
        parameters: {
          maxIsometricForce: 335.3,
          optimalFiberLength: 0.0778912,
          tendonSlackLength: 0.336571,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoArm('LAT1'),
        },
      },
      {
        id: 'latissimus_dorsi_iliac_r',
        displayName: 'Latissimus dorsi, iliac part, right',
        origin: 'latissimus_dorsi_origin_r_iliac_crest',
        insertion: 'latissimus_dorsi_insertion_r_intertubercular_sulcus',
        path: [
          { kind: 'site', site: 'latissimus_dorsi_iliac_r__via_1' },
          { kind: 'site', site: 'latissimus_dorsi_iliac_r__via_2' },
        ],
        parameters: {
          maxIsometricForce: 179.495,
          optimalFiberLength: 0.153279,
          tendonSlackLength: 0.275731,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoArm('LAT3'),
        },
      },
    ],
  },
  {
    id: 'pectoralis_major_r',
    displayName: 'Pectoralis major, right',
    taTerm: 'Musculus pectoralis major',
    innervation: 'Lateral and medial pectoral nerves',
    source: gray('Pectoralis major'),
    units: [
      {
        id: 'pectoralis_major_sternal_r',
        displayName: 'Pectoralis major, sternocostal head, right',
        origin: 'pectoralis_major_origin_r_manubrium_of_sternum',
        insertion: 'pectoralis_major_insertion_r_crest_of_greater_tubercle',
        path: [{ kind: 'site', site: 'pectoralis_major_sternal_r__via_1' }],
        parameters: {
          maxIsometricForce: 570.669,
          optimalFiberLength: 0.128393,
          tendonSlackLength: 0.0798819,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoArm('PECM2'),
        },
      },
      {
        id: 'pectoralis_major_abdominal_r',
        displayName: 'Pectoralis major, abdominal part, right',
        origin: 'pectoralis_major_origin_r_body_of_rib',
        insertion: 'pectoralis_major_insertion_r_crest_of_greater_tubercle',
        path: [{ kind: 'site', site: 'pectoralis_major_abdominal_r__via_1' }],
        parameters: {
          maxIsometricForce: 418.121,
          optimalFiberLength: 0.116895,
          tendonSlackLength: 0.130227,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoArm('PECM3'),
        },
      },
    ],
  },
  {
    id: 'latissimus_dorsi_l',
    displayName: 'Latissimus dorsi, left',
    taTerm: 'Musculus latissimus dorsi',
    innervation: 'Thoracodorsal nerve',
    source: gray('Latissimus dorsi'),
    units: [
      {
        id: 'latissimus_dorsi_thoracic_l',
        displayName: 'Latissimus dorsi, thoracic part, left',
        origin: 'latissimus_dorsi_origin_l_spinous_process_tip',
        insertion: 'latissimus_dorsi_insertion_l_intertubercular_sulcus',
        path: [
          { kind: 'site', site: 'latissimus_dorsi_thoracic_l__via_1' },
          { kind: 'site', site: 'latissimus_dorsi_thoracic_l__via_2' },
        ],
        parameters: {
          maxIsometricForce: 335.3,
          optimalFiberLength: 0.0778912,
          tendonSlackLength: 0.336571,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoArm('LAT1'),
        },
      },
      {
        id: 'latissimus_dorsi_iliac_l',
        displayName: 'Latissimus dorsi, iliac part, left',
        origin: 'latissimus_dorsi_origin_l_iliac_crest',
        insertion: 'latissimus_dorsi_insertion_l_intertubercular_sulcus',
        path: [
          { kind: 'site', site: 'latissimus_dorsi_iliac_l__via_1' },
          { kind: 'site', site: 'latissimus_dorsi_iliac_l__via_2' },
        ],
        parameters: {
          maxIsometricForce: 179.495,
          optimalFiberLength: 0.153279,
          tendonSlackLength: 0.275731,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoArm('LAT3'),
        },
      },
    ],
  },
  {
    id: 'pectoralis_major_l',
    displayName: 'Pectoralis major, left',
    taTerm: 'Musculus pectoralis major',
    innervation: 'Lateral and medial pectoral nerves',
    source: gray('Pectoralis major'),
    units: [
      {
        id: 'pectoralis_major_sternal_l',
        displayName: 'Pectoralis major, sternocostal head, left',
        origin: 'pectoralis_major_origin_l_manubrium_of_sternum',
        insertion: 'pectoralis_major_insertion_l_crest_of_greater_tubercle',
        path: [{ kind: 'site', site: 'pectoralis_major_sternal_l__via_1' }],
        parameters: {
          maxIsometricForce: 570.669,
          optimalFiberLength: 0.128393,
          tendonSlackLength: 0.0798819,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoArm('PECM2'),
        },
      },
      {
        id: 'pectoralis_major_abdominal_l',
        displayName: 'Pectoralis major, abdominal part, left',
        origin: 'pectoralis_major_origin_l_body_of_rib',
        insertion: 'pectoralis_major_insertion_l_crest_of_greater_tubercle',
        path: [{ kind: 'site', site: 'pectoralis_major_abdominal_l__via_1' }],
        parameters: {
          maxIsometricForce: 418.121,
          optimalFiberLength: 0.116895,
          tendonSlackLength: 0.130227,
          pennationAngle: 0,
          maxContractionVelocity: 10,
          source: myoArm('PECM3'),
        },
      },
    ],
  },
];

/** Every unit in the set, flattened, in a stable order. */
export const TRUNK_UNITS = TRUNK_MUSCLES.flatMap((group) => group.units);
