/**
 * The companion Blender script.
 *
 * Blender's glTF importer maps keyframe times to frames through the scene's frame rate, so a
 * 500 Hz simulation imported into a 24 fps scene lands on fractional frames. Setting the frame
 * rate to the simulation rate first puts every tick on its own integer frame, which is the
 * fidelity the export promises; the script does that, imports the file, and sets the frame
 * range to the capture.
 */

export interface BlenderScriptOptions {
  /** File name of the .glb, expected next to the script. */
  readonly glbFileName: string;
  /** Simulation rate in Hz; becomes the scene frame rate. */
  readonly rate: number;
  /** Number of keyframes in the capture. */
  readonly frames: number;
}

export function blenderImportScript(options: BlenderScriptOptions): string {
  const rate = Math.round(options.rate);
  return `# Generated by bs-humany. Run from Blender's Text Editor or:
#   blender --python ${options.glbFileName.replace(/\\.glb$/, '')}.py
# Imports ${options.glbFileName} with one Blender frame per simulation tick at ${rate} fps.
import os
import bpy

here = os.path.dirname(os.path.abspath(__file__)) if "__file__" in globals() else os.getcwd()
path = os.path.join(here, ${JSON.stringify(options.glbFileName)})

scene = bpy.context.scene
scene.render.fps = ${rate}
scene.render.fps_base = 1.0
scene.frame_start = 0
scene.frame_end = ${Math.max(options.frames - 1, 0)}
bpy.ops.import_scene.gltf(filepath=path)
scene.frame_set(0)
print("bs-humany: imported", path, "at", ${rate}, "fps,", ${options.frames}, "frames")
`;
}
