/**
 * The companion Blender script.
 *
 * Blender's glTF importer maps keyframe times to frames through the scene's frame rate, so a
 * 500 Hz simulation imported into a 24 fps scene lands on fractional frames. Setting the frame
 * rate to the simulation rate first puts every tick on its own integer frame, which is the
 * fidelity the export promises; the script does that, imports the file, and sets the frame
 * range to the capture.
 *
 * The rest of what it does is tidying that the format cannot carry. glTF has no way to say "this
 * empty is a joint centre, draw it small and hide it", or "this mesh is a muscle belly, shade it
 * smooth and give it flesh rather than bone"; all of that is Blender's, so it is done here rather
 * than left for whoever opens the file.
 */

export interface BlenderScriptOptions {
  /** File name of the .glb, expected next to the script. */
  readonly glbFileName: string;
  /** Simulation rate in Hz; becomes the scene frame rate. */
  readonly rate: number;
  /** Number of keyframes in the capture. */
  readonly frames: number;
}

export function blenderImportScript(options: BlenderScriptOptions): string {
  const rate = Math.round(options.rate);
  return `# Generated by bs-humany. Run it from Blender's Text Editor, or:
#   blender --python ${options.glbFileName.replace(/\.glb$/, '')}.py
# Imports ${options.glbFileName} with one Blender frame per simulation tick at ${rate} fps.
#
# If the file is somewhere else, put its full path here and run again.
GLB = ${JSON.stringify(options.glbFileName)}

import os
import bpy

def find_glb():
    """Where the .glb might be, in the order worth trying."""
    if os.path.isabs(GLB):
        return GLB if os.path.isfile(GLB) else None
    roots = []
    # Run with --python, or from the Text Editor in a Blender new enough to set __file__.
    if "__file__" in globals():
        roots.append(os.path.dirname(os.path.abspath(__file__)))
    # Run from the Text Editor: the text block remembers the file it was loaded from.
    for text in bpy.data.texts:
        if text.filepath:
            roots.append(os.path.dirname(bpy.path.abspath(text.filepath)))
    # Next to the .blend, and finally wherever Blender was started.
    if bpy.data.filepath:
        roots.append(os.path.dirname(bpy.path.abspath(bpy.data.filepath)))
    roots.append(os.getcwd())
    for root in roots:
        candidate = os.path.join(root, GLB)
        if os.path.isfile(candidate):
            return candidate
    return None

path = find_glb()
if path is None:
    raise RuntimeError(
        "bs-humany: cannot find " + GLB + ". Save it next to this script, or set GLB at the "
        "top of this file to its full path. Looked in: " + os.getcwd()
    )

scene = bpy.context.scene
scene.render.fps = ${rate}
scene.render.fps_base = 1.0
scene.frame_start = 0
scene.frame_end = ${Math.max(options.frames - 1, 0)}

before = set(bpy.data.objects)
bpy.ops.import_scene.gltf(filepath=path)
imported = [o for o in bpy.data.objects if o not in before]

# Every joint centre is an empty, and Blender draws an empty one metre across by default: a
# hundred of them makes a thicket of axes that hides the skeleton. They are shrunk to a
# centimetre and moved to their own collection, which starts hidden. Un-hide "Joint centres"
# in the outliner to check a pivot against the bone it turns inside.
joints = bpy.data.collections.new("Joint centres")
scene.collection.children.link(joints)
for ob in imported:
    if ob.type != "EMPTY":
        continue
    ob.empty_display_size = 0.01
    if ob.name.startswith("joint__"):
        ob.empty_display_type = "SPHERE"
        for c in list(ob.users_collection):
            c.objects.unlink(ob)
        joints.objects.link(ob)

layer = bpy.context.view_layer.layer_collection.children.get(joints.name)
if layer is not None:
    layer.hide_viewport = True

# The muscles come in as skinned meshes with an armature apiece: one bone per cross-section,
# carrying both the bend of the path and the swell of the belly. Blender draws an armature's
# bones as octahedra over the mesh they deform, which buries the muscle in wireframe, so the
# armatures are drawn as sticks and moved to their own collection; the bellies get smooth
# shading and a red material, because a swept tube flat-shaded looks like a segmented worm.
muscles = bpy.data.collections.new("Muscles")
scene.collection.children.link(muscles)
rigs = bpy.data.collections.new("Muscle rigs")
scene.collection.children.link(rigs)

flesh = bpy.data.materials.new("bs-humany muscle")
flesh.use_nodes = True
surface = flesh.node_tree.nodes.get("Principled BSDF")
if surface is not None:
    surface.inputs["Base Color"].default_value = (0.62, 0.16, 0.16, 1.0)
    roughness = surface.inputs.get("Roughness")
    if roughness is not None:
        roughness.default_value = 0.55

def move_to(ob, collection):
    for c in list(ob.users_collection):
        c.objects.unlink(ob)
    collection.objects.link(ob)

for ob in imported:
    if ob.type == "MESH" and ob.name.startswith("muscle__"):
        move_to(ob, muscles)
        ob.data.materials.clear()
        ob.data.materials.append(flesh)
        for polygon in ob.data.polygons:
            polygon.use_smooth = True
        # The sweep already gives every ring its own frame, so the seam where the tube closes is
        # the only place two vertices sit on top of each other. Merging them stops the smooth
        # shading breaking along that seam.
        ob.data.validate()
    elif ob.type == "ARMATURE":
        move_to(ob, rigs)
        ob.data.display_type = "STICK"
        ob.show_in_front = False

rigLayer = bpy.context.view_layer.layer_collection.children.get(rigs.name)
if rigLayer is not None:
    rigLayer.hide_viewport = True

scene.frame_set(0)
print("bs-humany: imported", path, "at", ${rate}, "fps,", ${options.frames}, "frames")
`;
}
