/**
 * Activation clips: muscle excitation over time, authored as tracks, played by a scenario.
 *
 * The format is the companion file of `docs/sources/humansim-activation-research.md`, which
 * argues for it: tracks target a unit or a weighted functional group, carry a side, and hold
 * keyframes in seconds or in per cent of a cycle; interpolation is monotone cubic, clamped to
 * [0, 1], because an overshoot below zero would be a negative excitation and a muscle never
 * pushes. What this file adds is the reading of it -- every target resolved to real units at
 * load, a `both` checked to be exactly two of them -- and the evaluation: the excitation of
 * every unit a clip touches at a given time, which a scenario script hands to `api.drive` each
 * tick. Excitation, not activation: the muscle module's activation dynamics supply the
 * electromechanical delay, so the clip must not.
 *
 * Where several tracks reach one unit -- the hamstrings sit in both the knee flexors and the hip
 * extensors -- the unit takes the largest demand. A muscle is one thing however many jobs it is
 * asked to do at once.
 */

import clipFile from '../data/activation-clips.json' with { type: 'json' };

export type Side = 'left' | 'right' | 'both';
export type Interpolation = 'monotoneCubic' | 'linear' | 'step';

export interface ClipPoint {
  /** Seconds, for a `seconds` clip. */
  readonly t?: number;
  /** Per cent of the cycle, for a `cyclePercent` clip. */
  readonly p?: number;
  readonly level: number;
}

export interface ClipTrack {
  readonly target: { readonly kind: 'unit' | 'group'; readonly id: string };
  readonly side: Side;
  readonly interpolation?: Interpolation;
  readonly note?: string;
  readonly points: readonly ClipPoint[];
}

export interface ActivationClip {
  readonly id: string;
  readonly displayName: string;
  readonly timebase: 'seconds' | 'cyclePercent';
  readonly duration?: number;
  readonly cycleSeconds?: number;
  readonly loop: boolean;
  readonly provenance: string;
  readonly limitations?: readonly string[];
  readonly tracks: readonly ClipTrack[];
  /** The other side generated by a phase shift, so one edit keeps both legs in step. */
  readonly mirrorRule?: {
    readonly shiftPercent: number;
    readonly appliesToSides: readonly string[];
  };
}

export interface ClipGroup {
  readonly source: string;
  readonly weights: Readonly<Record<string, number>>;
}

export interface ClipFile {
  readonly groups: Readonly<Record<string, ClipGroup | string>>;
  readonly clips: readonly ActivationClip[];
}

/** A curve over time, in seconds; what one track becomes. */
interface Curve {
  readonly xs: Float64Array;
  readonly ys: Float64Array;
  /** Tangents, for the cubic; empty for the other kinds. */
  readonly ms: Float64Array;
  readonly kind: Interpolation;
}

/** One track after expansion: one unit, one weight, one curve, one phase shift. */
export interface CompiledTrack {
  readonly unit: string;
  readonly weight: number;
  readonly shiftSeconds: number;
  readonly curve: Curve;
  readonly source: ClipTrack;
}

/**
 * Fritsch-Carlson tangents: a monotone cubic through the points that never overshoots between
 * them, so a curve through levels in [0, 1] stays in [0, 1] and a flat stretch stays flat.
 */
function monotoneTangents(xs: Float64Array, ys: Float64Array): Float64Array {
  const n = xs.length;
  const ms = new Float64Array(n);
  if (n < 2) return ms;
  const d = new Float64Array(n - 1);
  for (let i = 0; i < n - 1; i++) {
    const h = (xs[i + 1] as number) - (xs[i] as number);
    d[i] = h > 0 ? ((ys[i + 1] as number) - (ys[i] as number)) / h : 0;
  }
  ms[0] = d[0] as number;
  ms[n - 1] = d[n - 2] as number;
  for (let i = 1; i < n - 1; i++) {
    const a = d[i - 1] as number;
    const b = d[i] as number;
    ms[i] = a * b <= 0 ? 0 : (a + b) / 2;
  }
  for (let i = 0; i < n - 1; i++) {
    const slope = d[i] as number;
    if (slope === 0) {
      ms[i] = 0;
      ms[i + 1] = 0;
      continue;
    }
    const alpha = (ms[i] as number) / slope;
    const beta = (ms[i + 1] as number) / slope;
    const s = alpha * alpha + beta * beta;
    if (s > 9) {
      const tau = 3 / Math.sqrt(s);
      ms[i] = tau * alpha * slope;
      ms[i + 1] = tau * beta * slope;
    }
  }
  return ms;
}

function curveOf(
  points: readonly ClipPoint[],
  toSeconds: (p: ClipPoint) => number,
  kind: Interpolation,
): Curve {
  const sorted = [...points].sort((a, b) => toSeconds(a) - toSeconds(b));
  const xs = Float64Array.from(sorted, toSeconds);
  const ys = Float64Array.from(sorted, (p) => Math.min(1, Math.max(0, p.level)));
  return {
    xs,
    ys,
    ms: kind === 'monotoneCubic' ? monotoneTangents(xs, ys) : new Float64Array(0),
    kind,
  };
}

/** The curve at `x`, held flat outside its points. */
function sample(curve: Curve, x: number): number {
  const { xs, ys } = curve;
  const n = xs.length;
  if (n === 0) return 0;
  if (x <= (xs[0] as number)) return ys[0] as number;
  if (x >= (xs[n - 1] as number)) return ys[n - 1] as number;
  let lo = 0;
  let hi = n - 1;
  while (hi - lo > 1) {
    const mid = (lo + hi) >> 1;
    if ((xs[mid] as number) <= x) lo = mid;
    else hi = mid;
  }
  const x0 = xs[lo] as number;
  const x1 = xs[hi] as number;
  const y0 = ys[lo] as number;
  const y1 = ys[hi] as number;
  const h = x1 - x0;
  if (h <= 0) return y1;
  const s = (x - x0) / h;
  switch (curve.kind) {
    case 'step':
      return y0;
    case 'linear':
      return y0 + (y1 - y0) * s;
    default: {
      const m0 = curve.ms[lo] as number;
      const m1 = curve.ms[hi] as number;
      const s2 = s * s;
      const s3 = s2 * s;
      const value =
        (2 * s3 - 3 * s2 + 1) * y0 +
        (s3 - 2 * s2 + s) * h * m0 +
        (-2 * s3 + 3 * s2) * y1 +
        (s3 - s2) * h * m1;
      return Math.min(1, Math.max(0, value));
    }
  }
}

/** A clip resolved against a set of unit ids and ready to evaluate. */
export class CompiledClip {
  readonly id: string;
  readonly displayName: string;
  /** Seconds a cycle, or the clip's length; what time wraps by when it loops. */
  readonly period: number;
  readonly loop: boolean;
  readonly tracks: readonly CompiledTrack[];
  /** Every unit the clip touches, in a fixed order; `levels` answers in this order. */
  readonly units: readonly string[];
  private readonly indexOf: ReadonlyMap<string, number>;
  private readonly trackUnit: Int32Array;
  private readonly out: Float64Array;

  constructor(clip: ActivationClip, tracks: readonly CompiledTrack[]) {
    this.id = clip.id;
    this.displayName = clip.displayName;
    this.loop = clip.loop;
    this.period =
      clip.timebase === 'cyclePercent'
        ? (clip.cycleSeconds ?? 1)
        : (clip.duration ??
          Math.max(0, ...tracks.map((t) => t.curve.xs[t.curve.xs.length - 1] ?? 0)));
    this.tracks = tracks;
    const units = [...new Set(tracks.map((t) => t.unit))];
    this.units = units;
    this.indexOf = new Map(units.map((u, i) => [u, i]));
    this.trackUnit = Int32Array.from(tracks, (t) => this.indexOf.get(t.unit) ?? 0);
    this.out = new Float64Array(units.length);
  }

  /**
   * The excitation of every unit at `time` seconds, in `units` order. The array is reused
   * between calls: copy it if it has to outlive the next one.
   */
  levels(time: number): Float64Array {
    const out = this.out;
    out.fill(0);
    const period = this.period;
    for (let i = 0; i < this.tracks.length; i++) {
      const track = this.tracks[i] as CompiledTrack;
      let x = time - track.shiftSeconds;
      if (this.loop && period > 0) {
        x = ((x % period) + period) % period;
      }
      const level = track.weight * sample(track.curve, x);
      const at = this.trackUnit[i] as number;
      if (level > (out[at] as number)) out[at] = level;
    }
    return out;
  }
}

/** Resolve one clip's tracks against the groups and the unit ids that actually exist. */
export function compileClip(
  clip: ActivationClip,
  groups: Readonly<Record<string, ClipGroup | string>>,
  unitIds: ReadonlySet<string>,
): CompiledClip {
  const period = clip.timebase === 'cyclePercent' ? (clip.cycleSeconds ?? 1) : 1;
  const toSeconds =
    clip.timebase === 'cyclePercent'
      ? (p: ClipPoint) => ((p.p ?? 0) / 100) * period
      : (p: ClipPoint) => p.t ?? 0;
  const mirror = clip.mirrorRule;
  const compiled: CompiledTrack[] = [];

  const sidesOf = (side: Side): ('left' | 'right')[] =>
    side === 'both' ? ['left', 'right'] : [side];
  const sided = (base: string, side: 'left' | 'right') => `${base}_${side === 'left' ? 'l' : 'r'}`;

  for (const track of clip.tracks) {
    if (track.points.length === 0) {
      throw new Error(`${clip.id}: a track on ${track.target.id} has no points.`);
    }
    const curve = curveOf(track.points, toSeconds, track.interpolation ?? 'monotoneCubic');
    const members: [string, number][] =
      track.target.kind === 'unit'
        ? [[track.target.id, 1]]
        : (() => {
            const group = groups[track.target.id];
            if (!group || typeof group === 'string') {
              throw new Error(`${clip.id}: no group called '${track.target.id}'.`);
            }
            return Object.entries(group.weights);
          })();
    // A group with no members -- the scapular stabilisers, which the muscle set lacks -- drives
    // nothing, and says so in the file rather than here.
    const emit = (side: 'left' | 'right', shiftSeconds: number) => {
      for (const [base, weight] of members) {
        const unit = sided(base, side);
        if (!unitIds.has(unit)) {
          throw new Error(
            `${clip.id}: '${unit}' (from ${track.target.id}) is not a unit in the set.`,
          );
        }
        compiled.push({ unit, weight, shiftSeconds, curve, source: track });
      }
    };
    for (const side of sidesOf(track.side)) emit(side, 0);
    // The mirror rule: a right-side track begets a left-side one half a cycle on.
    if (mirror && track.side !== 'both' && mirror.appliesToSides.includes(track.side)) {
      const other = track.side === 'right' ? 'left' : 'right';
      emit(other, (mirror.shiftPercent / 100) * period);
    }
  }
  return new CompiledClip(clip, compiled);
}

/** The clips shipped with the package, compiled against these unit ids. */
export function loadActivationClips(
  unitIds: ReadonlySet<string>,
  file: ClipFile = clipFile as unknown as ClipFile,
): ReadonlyMap<string, CompiledClip> {
  return new Map(file.clips.map((clip) => [clip.id, compileClip(clip, file.groups, unitIds)]));
}

/** The raw file, for anything that wants the notes, the sources and the limitations. */
export const ACTIVATION_CLIP_FILE: ClipFile = clipFile as unknown as ClipFile;

/** The ids of the units every group in the file names, both sides -- what a clip needs to exist. */
export function unitsNamedByClips(file: ClipFile = ACTIVATION_CLIP_FILE): Set<string> {
  const bases = new Set<string>();
  for (const group of Object.values(file.groups)) {
    if (typeof group === 'string') continue;
    for (const base of Object.keys(group.weights)) bases.add(base);
  }
  for (const clip of file.clips) {
    for (const track of clip.tracks) if (track.target.kind === 'unit') bases.add(track.target.id);
  }
  return new Set([...bases].flatMap((b) => [`${b}_r`, `${b}_l`]));
}
